### ISSUE TITLE
How can I get the “Sign in with your browser”  page to pop up

### ISSUE THREAD

**Issue by maikebing** [GitCredentialManager/git-credential-manager#1001]
https://github.com/GitCredentialManager/git-credential-manager/pull/1000
I'm trying to support a new git repository hoster， But I'm having a problem
I tested GitLab related but ran into the same issue. 

1. Run  "C:\Program Files (x86)\Git Credential Manager\GitLab.UI.exe" 
2.  Click "Show"
3. Click "Sign in with your browser"
Nothing happened
How can I get the GitLab page to pop up。

**Comment by ldennington** [comment]
Hi @maikebing - can I ask why you're trying to run the GitLab helper directly? The typical workflow is using GCM to call these types of helpers. It seems like you might be trying to debug a local build, so, for example, you could:

```
cd <path to your local GCM clone>
dotnet build --configuration=WindowsDebug
```
That will create an installer with your changes at:

`<path to your local GCM clone>\out\windows\Installer.Windows\bin\Debug\net472\gcm-win-x86-2.0.889.exe`

Run the installer exe above, then run:

`"C:\Program Files (x86)\Git Credential Manager\git-credential-manager.exe" get`

then (making sure to include the extra CRLF (in other words, a blank line) at the end to terminate your list of attributes):

```
protocol=https
host=gitlab.com

```

You should see the popup at that point. Please let me know if you have any questions.

**Comment by maikebing** [comment]
I want to debug "Sign in with your browse"

**Comment by maikebing** [comment]
![image](https://user-images.githubusercontent.com/3445167/208620254-16b3f150-3af7-4454-ba19-8ce404afac8c.png)

**Comment by maikebing** [comment]
i hope  pop up like this 
![image](https://user-images.githubusercontent.com/3445167/208634530-b4f0ad37-4cb8-4ec4-b78b-86a941a99bb5.png)

**Comment by maikebing** [comment]
@ldennington  The callback URL port of git-credential-manager is always changing, what can fix a port through?
