### ISSUE TITLE
Git error message "warning: could not find UI helper 'git-credential-manager-ui'"

### ISSUE THREAD

**Issue by Nu11u5** [GitCredentialManager/git-credential-manager#1003]
### Version

2.0.877+c7c35983b8

### Operating system

Windows

### OS version or distribution

Windows 10 22H2, x86-64

### Git hosting provider(s)

GitHub, GitLab

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

After running `git pull/push` the UI opens asking to authenticate.

### Actual behavior

When running `git push/pull` the error message "warning: could not find UI helper 'git-credential-manager-ui'" appears in the console output, and it prompts to manually provide authentication on the command line.  This is problematic for GUI tools that run `git` in the background, not interactively.

The latest Git for Windows was installed (2.39.0 64bit), and the binary exists at `"C:\Program Files\Git\mingw64\bin\git-credential-manager-ui.exe"`.

Unsure if this is a Git configuration issue or another problem.

**Comment by ldennington** [comment]
This issue has been fixed in the [latest release](https://github.com/GitCredentialManager/git-credential-manager/releases/tag/v2.0.886). Upgrading should fix it right up for you!
