### ISSUE TITLE
Failed to Authenticate via VSCode

### ISSUE THREAD

**Issue by RjHon** [GitCredentialManager/git-credential-manager#1014]
### Version

2.0.886+ea93cb5158

### Operating system

Windows

### OS version or distribution

Windows 11 Enterprise

### Git hosting provider(s)

Azure DevOps Server (TFS/on-prem)

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

After I click on "Clone Repository" and enter the Repo URL, I expect to see a prompt for credentials which will be stored by the git credential manager for future access.

### Actual behavior

> git clone https://hostname.com/DefaultCollection/Project/_git/Project c:\Users\username\Documents\Git\Project --progress
fatal: Authentication failed for 'https://hostname.com/DefaultCollection/Project/_git/Project'

**Comment by mjcheetham** [comment]
Hello @RjHon! Thanks for opening this issue.

> Logs
> No response

We are unable to diagnose or help you unless you include more detailed information or logs.

To capture trace logs, set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command.

If you are running inside of Windows Subsystem for Linux (WSL), you must also set an additional environment variable to enable tracing: `WSLENV=$WSLENV:GCM_TRACE`. For example:

```shell
WSLENV=$WSLENV:GCM_TRACE:GIT_TRACE GCM_TRACE=1 GIT_TRACE=1 git fetch
```

If you are using GCM version 2.0.567 onwards you can also run `git credential-manager-core diagnose` to collect useful diagnostic information that can be attached here.

**Comment by RjHon** [comment]
Trace log:
12:19:17.133850 exec-cmd.c:237          trace: resolved executable dir: C:/Users/user/AppData/Local/Programs/Git/mingw64/bin
12:19:17.175830 git.c:460               trace: built-in: git clone 'https://hostname.com/DefaultCollection/Project/_git/Project'
Cloning into 'Project'...
12:19:17.545419 run-command.c:655       trace: run_command: git remote-https origin 'https://hostname.com/DefaultCollection/Project/_git/Project'
12:19:17.725999 exec-cmd.c:237          trace: resolved executable dir: C:/Users/user/AppData/Local/Programs/Git/mingw64/libexec/git-core
12:19:17.729000 git.c:750               trace: exec: git-remote-https origin 'https://hostname.com/DefaultCollection/Project/_git/Project'
12:19:17.729000 run-command.c:655       trace: run_command: git-remote-https origin 'https://hostname.com/DefaultCollection/Project/_git/Project'
12:19:18.170841 exec-cmd.c:237          trace: resolved executable dir: C:/Users/user/AppData/Local/Programs/Git/mingw64/libexec/git-core
12:19:18.360761 run-command.c:655       trace: run_command: 'C:/Users/user/AppData/Local/Programs/Git/mingw64/bin/git-credential-manager.exe get'
12:19:20.987868 ...\Application.cs:95   trace: [RunInternalAsync] Version: 2.0.886.37866
12:19:20.991095 ...\Application.cs:96   trace: [RunInternalAsync] Runtime: .NET Framework 4.0.30319.42000
12:19:20.991095 ...\Application.cs:97   trace: [RunInternalAsync] Platform: Windows (x86-64)
12:19:20.991095 ...\Application.cs:98   trace: [RunInternalAsync] OSVersion: 10.0 (build 22000)
12:19:20.991865 ...\Application.cs:99   trace: [RunInternalAsync] AppPath: C:\Users\user\AppData\Local\Programs\Git\mingw64\bin\git-credential-manager.exe
12:19:20.992396 ...\Application.cs:100  trace: [RunInternalAsync] InstallDir: C:\Users\user\AppData\Local\Programs\Git\mingw64\bin\
12:19:20.992396 ...\Application.cs:101  trace: [RunInternalAsync] Arguments: get
12:19:21.046833 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'get' command...
12:19:21.056651 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
12:19:21.057649 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   protocol=https
12:19:21.057649 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   host=hostname.com
12:19:21.265648 ...oviderRegistry.cs:99 trace: [GetProviderAsync] Host provider override was set id='generic'
12:19:21.268645 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'Generic' was selected.
12:19:21.270646 ...\HostProvider.cs:126 trace: [GetCredentialAsync] Looking for existing credential in store with service=https://hostname.com account=...
12:19:22.262367 ...\HostProvider.cs:131 trace: [GetCredentialAsync] No existing credentials found.
12:19:22.263011 ...\HostProvider.cs:134 trace: [GetCredentialAsync] Creating new credential...
12:19:23.340953 ...icHostProvider.cs:63 trace: [GenerateCredentialAsync] Checking host 'https://hostname.com/' for Windows Integrated Authentication...
12:19:23.344084 ...Authentication.cs:34 trace: [GetIsSupportedAsync] HTTP: HEAD https://hostname.com/
12:19:23.347281 ...pClientFactory.cs:58 trace: [CreateClient] Creating new HTTP client instance...
12:19:27.383745 ...Authentication.cs:37 trace: [GetIsSupportedAsync] HTTP: Response code ignored.
12:19:27.384835 ...Authentication.cs:39 trace: [GetIsSupportedAsync] Inspecting WWW-Authenticate headers...
12:19:27.386031 ...Authentication.cs:44 trace: [GetIsSupportedAsync] Found WWW-Authenticate header for Negotiate
12:19:27.386697 ...Authentication.cs:49 trace: [GetIsSupportedAsync] Found WWW-Authenticate header for NTLM
12:19:27.387737 ...icHostProvider.cs:72 trace: [GenerateCredentialAsync] Host supports WIA - generating empty credential...
12:19:27.388696 ...\HostProvider.cs:136 trace: [GetCredentialAsync] Credential created.
12:19:27.389699 ...\GetCommand.cs:39    trace: [ExecuteInternalAsync] Writing credentials to output:
12:19:27.390698 ...\GetCommand.cs:40    trace: [ExecuteInternalAsync]   protocol=https
12:19:27.391693 ...\GetCommand.cs:40    trace: [ExecuteInternalAsync]   host=hostname.com
12:19:27.392695 ...\GetCommand.cs:40    trace: [ExecuteInternalAsync]   username=
12:19:27.401748 ...\GetCommand.cs:40    trace: [ExecuteInternalAsync]   password=********
12:19:27.409699 ...GitCommandBase.cs:54 trace: [ExecuteAsync] End 'get' command...
12:19:27.509786 run-command.c:655       trace: run_command: 'C:/Users/user/AppData/Local/Programs/Git/mingw64/bin/git-credential-manager.exe erase'
12:19:29.770501 ...\Application.cs:95   trace: [RunInternalAsync] Version: 2.0.886.37866
12:19:29.772505 ...\Application.cs:96   trace: [RunInternalAsync] Runtime: .NET Framework 4.0.30319.42000
12:19:29.772505 ...\Application.cs:97   trace: [RunInternalAsync] Platform: Windows (x86-64)
12:19:29.774503 ...\Application.cs:98   trace: [RunInternalAsync] OSVersion: 10.0 (build 22000)
12:19:29.776502 ...\Application.cs:99   trace: [RunInternalAsync] AppPath: C:\Users\user\AppData\Local\Programs\Git\mingw64\bin\git-credential-manager.exe
12:19:29.777503 ...\Application.cs:100  trace: [RunInternalAsync] InstallDir: C:\Users\user\AppData\Local\Programs\Git\mingw64\bin\
12:19:29.777503 ...\Application.cs:101  trace: [RunInternalAsync] Arguments: erase
12:19:29.831502 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'erase' command...
12:19:29.842618 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
12:19:29.843633 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   protocol=https
12:19:29.843633 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   host=hostname.com
12:19:29.843633 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   username=
12:19:29.844394 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   password=********
12:19:30.089798 ...oviderRegistry.cs:99 trace: [GetProviderAsync] Host provider override was set id='generic'
12:19:30.093793 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'Generic' was selected.
12:19:30.094864 ...\HostProvider.cs:173 trace: [EraseCredentialAsync] Erasing stored credential in store with service=https://hostname.com account=...
12:19:31.159923 ...\HostProvider.cs:180 trace: [EraseCredentialAsync] No credential was erased.
12:19:31.161922 ...GitCommandBase.cs:54 trace: [ExecuteAsync] End 'erase' command...
fatal: Authentication failed for 'https://hostname.com/DefaultCollection/Project/_git/Project/'

12:23:34.855140 exec-cmd.c:237          trace: resolved executable dir: C:/Users/user/AppData/Local/Programs/Git/mingw64/bin
12:23:34.900138 git.c:750               trace: exec: git-credential-manager diagnose
12:23:34.900138 run-command.c:655       trace: run_command: git-credential-manager diagnose
12:23:36.953526 ...\Application.cs:95   trace: [RunInternalAsync] Version: 2.0.886.37866
12:23:36.956528 ...\Application.cs:96   trace: [RunInternalAsync] Runtime: .NET Framework 4.0.30319.42000
12:23:36.956528 ...\Application.cs:97   trace: [RunInternalAsync] Platform: Windows (x86-64)
12:23:36.956528 ...\Application.cs:98   trace: [RunInternalAsync] OSVersion: 10.0 (build 22000)
12:23:36.956528 ...\Application.cs:99   trace: [RunInternalAsync] AppPath: C:\Users\user\AppData\Local\Programs\Git\mingw64\bin\git-credential-manager.exe
12:23:36.957544 ...\Application.cs:100  trace: [RunInternalAsync] InstallDir: C:\Users\user\AppData\Local\Programs\Git\mingw64\bin\
12:23:36.957735 ...\Application.cs:101  trace: [RunInternalAsync] Arguments: diagnose
Running diagnostics...

 [ OK ] Environment
 [ OK ] File system
  >>>>  Networking12:23:37.049576 ...pClientFactory.cs:58 trace: [CreateClient] Creating new HTTP client instance...
[ OK ] Networking
 [ OK ] Git
 [ OK ] Credential storage
 [ OK ] Microsoft authentication (AAD/MSA)
  >>>>  GitHub API12:23:43.703151 ...GitHubRestApi.cs:117 trace: [GetMetaInfoAsync] HTTP: GET https://api.github.com/meta
12:23:43.703151 ...pClientFactory.cs:58 trace: [CreateClient] Creating new HTTP client instance...
12:23:45.776696 ...GitHubRestApi.cs:121 trace: [GetMetaInfoAsync] HTTP: Response 200 [OK]
[ OK ] GitHub API

Diagnostic summary: 7 passed, 0 skipped, 0 failed.
Log files:
 [ C:\Users\user\Documents\Git.Guardian\gcm-diagnose.log](url)
[gcm-diagnose.log](https://github.com/GitCredentialManager/git-credential-manager/files/10341436/gcm-diagnose.log)

**Comment by ldennington** [comment]
It seems that your Windows user is different from the user authorized to access the Azure DevOps on-prem instance. The solution is to disable WIA authentication - you can do so by following [these instructions](https://aka.ms/gcm/config#credentialallowwindowsauth). You'll want to set the config value to `false`.

**Comment by RjHon** [comment]
After setting to false, it prompts me for username and password, but it will keep prompting me for credentials. will the git credential manager cache me credential with this config is set to false?

**Comment by ldennington** [comment]
That is odd. GCM should definitely still be storing your credentials. Would you mind attaching some more trace logs for us, ideally across multiple calls to `git pull/push` so we can investigate further?

**Comment by RjHon** [comment]
I found out why, I overwritten the credential.helper, once I set it back to the git credential manager it prompted me for username password and cache my credentials.
