### ISSUE TITLE
Hello @RjHon! Thanks for opening this issue.

### ISSUE THREAD

**Issue by BrocoliG101** [GitCredentialManager/git-credential-manager#1016]
Hello @RjHon! Thanks for opening this issue.

> Logs
> No response

We are unable to diagnose or help you unless you include more detailed information or logs.

To capture trace logs, set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command.

If you are running inside of Windows Subsystem for Linux (WSL), you must also set an additional environment variable to enable tracing: `WSLENV=$WSLENV:GCM_TRACE`. For example:

```shell
WSLENV=$WSLENV:GCM_TRACE:GIT_TRACE GCM_TRACE=1 GIT_TRACE=1 git fetch
```

If you are using GCM version 2.0.567 onwards you can also run `git credential-manager-core diagnose` to collect useful diagnostic information that can be attached here.

_Originally posted by @mjcheetham in https://github.com/GitCredentialManager/git-credential-manager/issues/1014#issuecomment-1370034919_

**Comment by ldennington** [comment]
Closing, as this does not capture any information that is not already covered in #1014.
