### ISSUE TITLE
Documentation on using git credential cache in windows is inconsistent

### ISSUE THREAD

**Issue by phollyni** [GitCredentialManager/git-credential-manager#1039]
In the configuration options document under the credential.credentialStore heading it says gits built in credential cache is supported on windows. (https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/configuration.md#credentialcredentialstore)

However, in the credential stores document under the Git's built-in credential cache heading windows is not in the "available on" list. (https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/credstores.md#gits-built-in-credential-cache)

**Comment by hickford** [comment]
Correct, Git for Windows  doesn't support git-credential-cache https://github.com/git-for-windows/git/issues/3892
