### ISSUE TITLE
> Fixes #145

### ISSUE THREAD

**Issue by Mohammedalanizi92** [GitCredentialManager/git-credential-manager#1042]
> Fixes #145
> 
> tested with https://try.gitea.io/
> 
> ```shell
> git config --global credential.https://try.gitea.io.provider gitea
> git config --global credential.https://try.gitea.io.giteadevclientid 7e8fa8b7-1cae-4bc2-beda-2fb982f2113a
> git config --global credential.https://try.gitea.io.giteadevclientsecret gto_2hehr5mc7hqvrnxmz2gsl7crzhtu7dypfzpfsx6soch4aliehika
> ```

_Originally posted by @Mohammedalanizi92 in https://github.com/GitCredentialManager/git-credential-manager/issues/879#issuecomment-1398027194_

**Comment by dscho** [comment]
Please use your own fork for practicing how to use GitHub.
