### ISSUE TITLE
Whats up

### ISSUE THREAD

**Issue by SaltonSea374** [GitCredentialManager/git-credential-manager#1048]
(invalid)

**Comment by Arezoomohammadalizadeh** [comment]
🙏🌹🥰
    در دوشنبه، 23 ژانویه 2023، ساعت 02:13:38 بامداد به وقت گرینویچ + 3:30، SaltonSea374 ***@***.***> نوشت:  
 
 


https://github.com/pynecone-io/pynecone/actions/runs/3977157480/jobs/6824122910#step:5:1

- 
مستقیماً به این ایمیل پاسخ دهید، آن را در GitHub مشاهده کنید ، یا اشتراک را لغو کنید. 
شما این را دریافت می کنید زیرا در این موضوع مشترک شده اید.شناسه پیام: <GitCredentialManager/git-credential-manager/issues/1048 @ github . com>
