### ISSUE TITLE
Noisy and lagging host detection warnings when a Proxy is in play

### ISSUE THREAD

**Issue by byjrack** [GitCredentialManager/git-credential-manager#1079]
### Version

2.0.886+ea93cb5158

### Operating system

Windows

### OS version or distribution

10

### Git hosting provider(s)

GitHub

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

got operations complete prompting for login as needed and using cached credentials where available.

### Actual behavior

I have tried to set the provider to generic or anything to suppress the auto-detect lag on every operation, but no luck.  Now the proxy isn't the git provider, but it is the only way to get to it.  There is a chance that proxy auth may be at play if GCM doesn't leverage libcurl and those configs.  Also tried to set the timeout to -1 to disable, but there still seems to be a lag in the host detection section.

Experience is similar in CMD and in WSL2 for this operation.

```
Cloning into 'repo'...
warning: failed to probe 'http://proxy.example.com:port/' to detect provider
warning: An error occurred while sending the request.
warning: see https://aka.ms/gcm/autodetect for more information.
warning: failed to probe 'http://proxy.example.com:port/' to detect provider
warning: An error occurred while sending the request.
warning: see https://aka.ms/gcm/autodetect for more information.
remote: Enumerating objects: ...
```

**Comment by CynMali** [comment]
Still kinda new to this site. A little unsure of how to respond to these.

**Comment by ldennington** [comment]
Out of curiosity, have you followed [the official instructions](https://github.com/GitCredentialManager/git-credential-manager/blob/release/docs/netconfig.md#http-proxy) to configure GCM with a proxy?

**Comment by byjrack** [comment]
Yup we have to use a proxy so we use the domain scoped config and curl Negotiate in the most common scenarios.  Works fine with git by itself and while GCM works you just get a ton of warnings as it tries to host detect for the actual proxy and not by using the proxy.

http.https://github.com.proxy=http://:@proxy.example.com:8000

And some folks use env vars with a similar experience.

I am working with GCM_TRACE to see if i can figure out why the ClientFactory is seeing the proxy as an independent remote vs a way to get to the remote.

**Comment by ldennington** [comment]
Are you using Kerberos/NTLM for the proxy authentication? If so, this type of authentication with proxies is unfortunately not supported by the .NET http stack.

**Comment by byjrack** [comment]
Yup you got it.  I thought we could avoid it even trying using a credential.provider statement, but it still seems to try and use the proxy.  I will spend more time in GCM_TRACE tomorrow and see if I can figure out if I can avoid the warns and delays knowing that HttpClient can't handle Negotiate/407.

**Comment by byjrack** [comment]
I must have fat fingered things in my earlier testing 

`credential.proxy.example.com.provider generic` seems to suppress the "auto-detection of host provider took too long (>2000ms)" or "failed to probe 'http://proxy.example.com:8000/' to detect provider" type errors.  Still a bit of lag in the operations, but seems to be expected back and forth with the backend store.

Easy workaround to avoid the lag in the auto-detection routine used for the proxies.  Hopefully someday HttpClient will support Negotiate w Krb/NTLM, but for now it's just a bit of noise in the output.

**Comment by ferderer** [comment]
I get the warning without any proxy.
