### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by gulayciragiloglu79** [GitCredentialManager/git-credential-manager#1109]
### Version

2.0.696+4365b917da

### Operating system

Windows

### OS version or distribution

Windows 10 Pro

### Git hosting provider(s)

Bitbucket Server/DC

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

from my office computer i can login https://git.**.com/projects/PAYCO/repos/online/browse  repo  by using company vpn 
![image](https://user-images.githubusercontent.com/20457323/218398060-673e9e7d-4210-4c94-9a2a-ae1f582b4b95.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/20457323/218398094-93a7bc29-7d41-46ef-a6a7-8c9a9d44cb98.png)

**Comment by rohthegreat** [comment]
Both pics look the same I can't tell which one has the fatal error that you have provided in the description.

Pls provide more information or let's ask someone to see if they see a difference. @mjcheetham

**Comment by ldennington** [comment]
This appears to be an issue with your Git server. The error message you're seeing is coming from within Git itself, not GCM. I would suggest reaching out to https://support.atlassian.com for this issue.
