### ISSUE TITLE
Support `SSLKEYLOGFILE`

### ISSUE THREAD

**Issue by miya789** [GitCredentialManager/git-credential-manager#1122]
### Feature description

Could you please add support for using `SSLKEYLOGFILE` to enable packet decryption for the following Cipher Suite when using Wireshark?
* Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)

It seems that `SSLKEYLOGFILE` is already supported for browsers or Git using curl, but it currently does not support GCM.

**Comment by ldennington** [comment]
I don't think we'll be able to do this, as .NET does not appear to support `SSLKEYLOGFILE `. See [this issue](https://github.com/dotnet/runtime/issues/37915) for details.
