### ISSUE TITLE
Windows Server Core 2022 'msedge' dependency error

### ISSUE THREAD

**Issue by ubidev** [GitCredentialManager/git-credential-manager#1128]
### Version

2.0.886+ea93cb5158

### Operating system

Windows

### OS version or distribution

Windows Server 2022 Core Standard Edition

### Git hosting provider(s)

Azure DevOps

### (Azure DevOps only) What format is your remote URL?

https://{org}.visualstudio.com

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

Hi, I'm getting this dependency error.
I installed GCM via dotnet 6 and configured it

`
dotnet tool install -g git-credential-manager
git-credential-manager configure
`

But git clone repoaddress gives me a missing dependency to msedge error. There is no Edge on Server Core and don't want it there.

I further validated that the error dissapears and GCM works perfectly if I install MSEdge. But I don't understand why this is necessary considering that on other platforms, edge is not required unless I'm mistaken

Thanks in advance for enlightening me :)

### Actual behavior

error: "Windows cannot find 'msedge'. Make sure ou typed the name correctly, and then try again."
![image](https://user-images.githubusercontent.com/14218601/221369790-4308ff2b-de87-4650-8ec9-6fd63a72fa96.png)

**Comment by ubidev** [comment]
Bummer ! Thanks for the info :-)

**Comment by bgavrilMS** [comment]
Hi @ubidev - are you saying that there is no browser at all on Win Server 2022 Core? 

For reference, we do not force "edge", we try any browser first - this is our logic: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/src/client/Microsoft.Identity.Client/Platforms/netcore/NetCorePlatformProxy.cs#L150

**Comment by ubidev** [comment]
Exactly, you get a browser and full desktop if you install the « Desktop Experience » version of the product

**Comment by bgavrilMS** [comment]
Oh, so this is Windows without any UI @ubidev ?

If there is no browser, then GCM can't authenticate you interactively (via browser) and at best it can devolve to DeviceCode flow. 

@mjcheetham @ldennington - I was under the impression that GCM detects if the OS is headless or not before attempting to pop up the browser.

**Comment by ubidev** [comment]
I understand.
Now, since I'm expected to deploy containers on that same server (2022 core), can I expect to be able to use git authentication under wsl? :)
Thanks for your time

**Comment by ldennington** [comment]
On further investigation, we think this is hitting [this case](https://github.com/git-ecosystem/git-credential-manager/blob/c91294385db910f8dd15c0345e100cd034e6482f/src/shared/Core/Interop/Windows/WindowsSessionManager.cs#L36-L38) - this is not something we plan to change, though, given that .NET uses [the same implementation](https://github.com/dotnet/runtime/blob/1c8d37af80667daffb3cb80ce0fe915621e8f039/src/libraries/System.Private.CoreLib/src/System/Environment.Windows.cs#L178-L198).

**Comment by ubidev** [comment]
Thanks for the update :)
