### ISSUE TITLE
Add support for Gitea

### ISSUE THREAD

**Issue by lafriks** [GitCredentialManager/git-credential-manager#145]
Add support for Gitea - https://gitea.io/en-us/

**Comment by dscho** [comment]
@lafriks maybe you can help? See the documentation for an overview of the architecture: https://github.com/microsoft/Git-Credential-Manager-Core/blob/master/docs/architecture.md and I guess you need to implement a [Host Provider](https://github.com/microsoft/Git-Credential-Manager-Core/blob/master/docs/architecture.md#host-provider).

**Comment by lafriks** [comment]
I could help as soon as support to Linux is added as this is currently my only available platform to work on

**Comment by dscho** [comment]
> I could help as soon as support to Linux is added as this is currently my only available platform to work on

Well, quite honestly, there is nothing stopping you from helping on that, too.

**Comment by vtbassmatt** [comment]
@lafriks hey there. We would love to enlist your help building Gitea support now that [we have preliminary Linux support](https://github.com/microsoft/Git-Credential-Manager-Core/issues/135). We can use this issue for tracking and coordinating the effort.

(That goes for anyone else who wants to contribute here or on any other Git hosting implementations, too!)

**Comment by hickford** [comment]
Reading https://docs.gitea.io/en-us/oauth2-provider/ the Gitea OAuth provider looks similar to GitLab's (albeit without scopes), so could follow from https://github.com/GitCredentialManager/git-credential-manager/pull/591

**Comment by mjcheetham** [comment]
We are planning to extend the generic provider to also support OAuth authentication, meaning support for hosts like Gitea could be added easily via config.

https://github.com/GitCredentialManager/git-credential-manager/issues/1047

**Comment by ldennington** [comment]
Closing, as we added support for generic OAuth in #1062, slated to be released Feb. 17. Note that this will come unconfigured, so users will need to create their own Gitea OAuth Registrations - you can use [this documentation](https://docs.gitea.io/en-us/oauth2-provider/) as a guide.
