### ISSUE TITLE
Multi-user support

### ISSUE THREAD

**Issue by TemporalAgent7** [GitCredentialManager/git-credential-manager#189]
Please add the ability to switch between 2 GitHub accounts / identities. Ideally this would be an intuitive UI to pick account whenever you clone a repository (Account 1 / Account 2 / Read-Only) that then **sticks** throughout the life-time of that clone.

I don't know what git / GCM is doing but I often find commits in one repository with the other user's identity even if the user name and email are correctly set up in the repository's .git\config

**Comment by adamwalling** [comment]
This would be incredibly helpful; I generally have to set `git config credential.usehttppath true` for individual repos I need to use a different credential for.
