### ISSUE TITLE
User-specific GitHub credential not being recalled

### ISSUE THREAD

**Issue by vtbassmatt** [GitCredentialManager/git-credential-manager#284]
_This bug was reported by @RyanLamansky and @nero120 in https://github.com/microsoft/Git-Credential-Manager-Core/issues/160. That issue was intended as a feature request, so I'm porting the bug details over here and closing that one._

[Original report](https://github.com/microsoft/Git-Credential-Manager-Core/issues/160#issuecomment-701406055) from @RyanLamansky:

> I was able to get \[the multiple users on GitHub feature\] to work but I was expecting a pop-up when I used a previously-unused account name, instead I had to add the credentials via the command line.  Not a major issue, but a better UX would have saved me several minutes 🙂

@mjcheetham [asked for tracing details](https://github.com/microsoft/Git-Credential-Manager-Core/issues/160#issuecomment-705587571), and @RyanLamansky [replied with](https://github.com/microsoft/Git-Credential-Manager-Core/issues/160#issuecomment-706725067):

> ```
> 10:45:00.085950 ...\Application.cs:69   trace: [RunInternalAsync] Git Credential Manager version 2.0.194-beta+819e6bc120 (Windows, .NET Framework 4.0.30319.42000) 'get'
> 10:45:00.090902 ...\Command.cs:63       trace: [ExecuteAsync] Start 'get' command...
> 10:45:00.096886 ...\Command.cs:74       trace: [ExecuteAsync] Detecting host provider for input:
> 10:45:00.096886 ...\Command.cs:75       trace: [ExecuteAsync]   protocol=https
> 10:45:00.096886 ...\Command.cs:75       trace: [ExecuteAsync]   host=github.com
> 10:45:00.098881 ...\LibGit2.cs:30       trace: [GetConfiguration] Opening default Git configuration...
> 10:45:00.102871 ...\LibGit2.cs:46       trace: [GetConfiguration] Adding local configuration from repository 'C:/ISC/.git/'...
> 10:45:00.105862 ...\LibGit2.cs:111      trace: [.ctor] Creating Git configuration snapshot...
> 10:45:00.106860 ...\LibGit2.cs:139      trace: [Enumerate] Enumerating Git configuration entries...
> 10:45:00.106860 ...\LibGit2.cs:146      trace: [Enumerate] Enumeration complete.
> 10:45:00.107857 ...\LibGit2.cs:199      trace: [TryGetValue] Reading Git configuration entry 'credential.provider'...
> 10:45:00.108855 ...\LibGit2.cs:208      trace: [TryGetValue] No entry found.
> 10:45:00.108855 ...\LibGit2.cs:139      trace: [Enumerate] Enumerating Git configuration entries...
> 10:45:00.108855 ...\LibGit2.cs:146      trace: [Enumerate] Enumeration complete.
> 10:45:00.108855 ...\LibGit2.cs:199      trace: [TryGetValue] Reading Git configuration entry 'credential.authority'...
> 10:45:00.109852 ...\LibGit2.cs:208      trace: [TryGetValue] No entry found.
> 10:45:00.111846 ...viderRegistry.cs:129 trace: [GetProvider] Performing auto-detection of host provider.
> 10:45:00.113841 ...\Command.cs:77       trace: [ExecuteAsync] Host provider 'GitHub' was selected.
> 10:45:00.115836 ...\HostProvider.cs:104 trace: [GetCredentialAsync] Looking for existing credential in store with key 'git:https://github.com'...
> 10:45:00.116833 ...\HostProvider.cs:118 trace: [GetCredentialAsync] Existing credential found.
> 10:45:00.116833 ...\Command.cs:81       trace: [ExecuteAsync] End 'get' command...
> ```
> The expectation is that any repo I clone using the `user123@github` URL format selects `user123` from the credential store when making the call to Github via normal `git` commands. The repo I ran this on was cloned that way, confirmed by checking `git remote get-url --all origin`.
>
> The repository is private, so if the wrong user is configured, `git` acts as if the repo does not exist. My typical usage involves accessing various private repositories that only one of my two accounts can access.

@mjcheetham then asked for [additional tracing](https://github.com/microsoft/Git-Credential-Manager-Core/issues/160#issuecomment-723039680), which hasn't been provided yet. However, @nero120 [chimed in](https://github.com/microsoft/Git-Credential-Manager-Core/issues/160#issuecomment-723361863) with possibly the same problem:

> @mjcheetham I believe I'm seeing the same behaviour, the user portion of the repo url is being ignored and credentials always end up in windows credential manager as `git:https://github.com`.
> 
> I'm using Git Credential Manager version 2.0.252-beta+fe025c12fc (Windows, .NET Framework 4.0.30319.42000)
> 
> ```
> > git credential approve
> > url=https://nero120@github.com
> > password=pass2
> 
> 00:41:06.462509 run-command.c:663       trace: run_command: 'C:/Users/nero120/AppData/Local/Programs/Git\ Credential\ Manager\ Core/git-credential-manager-core.exe store'
> 00:41:06.738764 ...\Application.cs:69   trace: [RunInternalAsync] Git Credential Manager version 2.0.280-beta+1f4c6db90f (Windows, .NET Framework 4.0.30319.42000) 'store'
> 00:41:06.746247 ...\Command.cs:63       trace: [ExecuteAsync] Start 'store' command...
> 00:41:06.757228 ...\Command.cs:74       trace: [ExecuteAsync] Detecting host provider for input:
> 00:41:06.760228 ...\Command.cs:75       trace: [ExecuteAsync]   protocol=https
> 00:41:06.761225 ...\Command.cs:75       trace: [ExecuteAsync]   host=github.com
> 00:41:06.762228 ...\Command.cs:75       trace: [ExecuteAsync]   username=nero120
> 00:41:06.763228 ...\Command.cs:75       trace: [ExecuteAsync]   password=********
> 00:41:06.944266 ...viderRegistry.cs:129 trace: [GetProvider] Performing auto-detection of host provider.
> 00:41:06.947225 ...\Command.cs:77       trace: [ExecuteAsync] Host provider 'GitHub' was selected.
> 00:41:06.949233 ...\HostProvider.cs:149 trace: [StoreCredentialAsync] Storing credential with service=https://github.com account=nero120...
> 00:41:06.956256 ...\HostProvider.cs:151 trace: [StoreCredentialAsync] Credential was successfully stored.
> 00:41:06.958225 ...\Command.cs:81       trace: [ExecuteAsync] End 'store' command...
> ```
> 
> ![image](https://user-images.githubusercontent.com/4236238/98426797-34ea0c80-2092-11eb-99bc-b9594d84d936.png)
>
> None of the following config options are set in my repo:
>
> ```
> git config credential.username
> git config credential.github.com.username
> git config credential.http://github.com.username
> git config credential.https://github.com.username
> ```

**Comment by nero120** [comment]
Thanks @vtbassmatt!

**Comment by mjcheetham** [comment]
Upon further reflection I don't think there's much we can do here except perhaps make the documentation clearer about how to specify the correct user handle/account in either the Git remote URL or Git config.

We are unable to reproduce the problems that were reported in the original issue - that is, as long as the user handle has been set correctly, the correct tokens are returned/saved.
