### ISSUE TITLE
Windows AAD Authentication fails to acquire token without user-interactive 

### ISSUE THREAD

**Issue by heatherjsun** [GitCredentialManager/git-credential-manager#296]
**Which version of GCM Core are you using?**
Git Credential Manager version 2.0.318-beta+44acfafa98 (Windows, .NET Framework 4.0.30319.42000)

**Which Git host provider are you trying to connect to?**

* [x] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

* [ ] Yes
* [ ] No, I get a permission error
* [x] No, for a different reason - running on remote VM with limited browser access

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [ ] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [x] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [x] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully. I do not need to interact via the console. (The credential helper generates an AAD token added stores it in the Windows credential manager.) This is successful using the no-longer-managed Git Credential for Windows.

**Actual behavior**

A fatal error is thrown, and I am prompted to provide the password.
```
fatal: Cannot prompt because user interactivity has been disabled.
Password for 'https://<org>@dev.azure.com/<org>/<project>/_git/<repo>':
```

**Logs**
git config -l
```
diff.astextplain.textconv=astextplain
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
credential.helper=manager-core
pull.rebase=false
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
credential.interactive=false
user.name=<username>
user.email=<username>@<org>.com
```
```
02:39:41.854720 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
02:39:41.854720 git.c:444               trace: built-in: git clone https://<org>@dev.azure.com/<org>/<project>/_git/<repo>
Cloning into 'pkges.codesign.db'...
02:39:41.885971 run-command.c:664       trace: run_command: git remote-https origin https://<org>@dev.azure.com/<org>/<project>/_git/<repo>
02:39:41.995348 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
02:39:41.995348 git.c:730               trace: exec: git-remote-https origin https://<org>@dev.azure.com/<org>/<project>/_git/<repo>
02:39:41.995348 run-command.c:664       trace: run_command: git-remote-https origin https://<org>@dev.azure.com/<org>/<project>/_git/<repo>
02:39:42.576306 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
02:39:42.998190 run-command.c:664       trace: run_command: 'git credential-manager-core get'
02:39:43.279445 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
02:39:43.279445 git.c:730               trace: exec: git-credential-manager-core get
02:39:43.279445 run-command.c:664       trace: run_command: git-credential-manager-core get
02:39:43.451328 ...\Application.cs:69   trace: [RunInternalAsync] Git Credential Manager version 2.0.318-beta+44acfafa98 (Windows, .NET Framework 4.0.30319.42000) 'get'
02:39:43.451328 ...\Command.cs:63       trace: [ExecuteAsync] Start 'get' command...
02:39:43.466950 ...\Command.cs:74       trace: [ExecuteAsync] Detecting host provider for input:
02:39:43.466950 ...\Command.cs:75       trace: [ExecuteAsync]   protocol=https
02:39:43.466950 ...\Command.cs:75       trace: [ExecuteAsync]   host=dev.azure.com
02:39:43.466950 ...\Command.cs:75       trace: [ExecuteAsync]   path=<org>/<project>/_git/<repo>
02:39:43.466950 ...\Command.cs:75       trace: [ExecuteAsync]   username=<org>
02:39:43.873208 ...viderRegistry.cs:129 trace: [GetProvider] Performing auto-detection of host provider.
02:39:43.873208 ...\Command.cs:77       trace: [ExecuteAsync] Host provider 'Azure Repos' was selected.
02:39:43.888835 ...osHostProvider.cs:66 trace: [GetCredentialAsync] Looking for existing credential in store with service=https://dev.azure.com/<org> account=...
02:39:43.888835 ...osHostProvider.cs:71 trace: [GetCredentialAsync] No existing credentials found.
02:39:43.888835 ...osHostProvider.cs:74 trace: [GetCredentialAsync] Creating new credential...
02:39:43.888835 ...sHostProvider.cs:141 trace: [GenerateCredentialAsync] Determining Microsoft Authentication Authority...
02:39:43.904460 ...eDevOpsRestApi.cs:46 trace: [GetAuthorityAsync] HTTP: HEAD https://dev.azure.com/<org>
02:39:43.904460 ...pClientFactory.cs:53 trace: [CreateClient] Creating new HTTP client instance...
02:39:44.935732 ...eDevOpsRestApi.cs:49 trace: [GetAuthorityAsync] HTTP: Response code ignored.
02:39:44.935732 ...eDevOpsRestApi.cs:50 trace: [GetAuthorityAsync] Inspecting headers...
02:39:44.935732 ...eDevOpsRestApi.cs:57 trace: [GetAuthorityAsync] Found WWW-Authenticate header with Bearer authority 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47'.
02:39:44.935732 ...sHostProvider.cs:143 trace: [GenerateCredentialAsync] Authority is 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47'.
02:39:44.935732 ...sHostProvider.cs:146 trace: [GenerateCredentialAsync] Getting Azure AD access token...
02:39:45.216991 ...uthentication.cs:267 trace: [RegisterVisualStudioTokenCacheAsync] Configuring Visual Studio token cache...
02:39:45.232619 ...uthentication.cs:284 trace: [RegisterVisualStudioTokenCacheAsync] Visual Studio token cache configured.
02:39:45.482621 ...enticationBase.cs:78 trace: [ThrowIfUserInteractionDisabled] GCM_INTERACTIVE / credential.interactive is false/never; user interactivity has been disabled.
fatal: Cannot prompt because user interactivity has been disabled.
02:39:45.513870 run-command.c:664       trace: run_command: bash -c 'cat >/dev/tty && read -r -s line </dev/tty && echo "$line" && echo >/dev/tty'
Password for 'https://<org>@dev.azure.com/<org>/<project>/_git/<repo>':
02:41:23.122072 run-command.c:664       trace: run_command: 'git credential-manager-core erase'
02:41:23.325204 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
02:41:23.325204 git.c:730               trace: exec: git-credential-manager-core erase
02:41:23.325204 run-command.c:664       trace: run_command: git-credential-manager-core erase
02:41:23.497081 ...\Application.cs:69   trace: [RunInternalAsync] Git Credential Manager version 2.0.318-beta+44acfafa98 (Windows, .NET Framework 4.0.30319.42000) 'erase'
02:41:23.512728 ...\Command.cs:63       trace: [ExecuteAsync] Start 'erase' command...
02:41:23.512728 ...\Command.cs:74       trace: [ExecuteAsync] Detecting host provider for input:
02:41:23.512728 ...\Command.cs:75       trace: [ExecuteAsync]   protocol=https
02:41:23.512728 ...\Command.cs:75       trace: [ExecuteAsync]   host=dev.azure.com
02:41:23.512728 ...\Command.cs:75       trace: [ExecuteAsync]   path=<org>/<project>/_git/<repo>
02:41:23.512728 ...\Command.cs:75       trace: [ExecuteAsync]   username=<org>
02:41:23.512728 ...\Command.cs:75       trace: [ExecuteAsync]   password=********
02:41:23.934590 ...viderRegistry.cs:129 trace: [GetProvider] Performing auto-detection of host provider.
02:41:23.934590 ...\Command.cs:77       trace: [ExecuteAsync] Host provider 'Azure Repos' was selected.
02:41:23.934590 ...sHostProvider.cs:108 trace: [EraseCredentialAsync] Erasing stored credential in store with service=https://dev.azure.com/<org> account=...
02:41:23.934590 ...sHostProvider.cs:115 trace: [EraseCredentialAsync] No credential was erased.
02:41:23.934590 ...\Command.cs:81       trace: [ExecuteAsync] End 'erase' command...
fatal: Authentication failed for 'https://<org>@dev.azure.com/<org>/<project>/_git/<repo>'
```

**Preliminary Investigation**
From looking at [this test,](https://github.com/microsoft/Git-Credential-Manager-Core/blob/04099e0f7458664b644123405ce14cb396dfecb9/src/shared/Microsoft.Git.CredentialManager.Tests/Authentication/MicrosoftAuthenticationTests.cs#L30) it looks like this is the expected outcome if user interactivity is disabled. I would expect authentication to succeed if a username was passed, but I couldn't find a way to do so. It almost seems like it's not possible given [this code](https://github.com/microsoft/Git-Credential-Manager-Core/blob/04099e0f7458664b644123405ce14cb396dfecb9/src/shared/Microsoft.AzureRepos/AzureReposHostProvider.cs#L154).

**Comment by mjcheetham** [comment]
As you found, this is by design.

In your configuration you have `credential.interactive=false` which means GCM Core will never be able to show an interactive prompt.

GCM for Windows used to also [attempt to use the current Windows domain user](https://github.com/microsoft/Git-Credential-Manager-for-Windows/blob/40d49d9791cea8ad07904bdf901610ed5d8268ee/AzureDevOps.Authentication/Src/Adal.cs#L161) via Windows Integrated Authentication (Kerberos/NTLM) which doesn't require a prompt, but GCM Core does not include support for this `WIA -> AAD token` mechanism.

GCM for Windows used ADAL to 'trigger' this WIA flow by passing an empty `UserCredential`.
In MSAL (that GCM Core uses), there is an explicit call that _can_ be made to [`AcquireTokenByIntegratedWindowsAuth`](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/0ce45ee39b65939e25cf6d669f14ce9c476e0048/src/client/Microsoft.Identity.Client/IPublicClientApplication.cs#L98-L119) to achieve the same thing.

However, we've so far opted not to add this flow because it is not always the case that you want or can use the current domain account to access the particular Azure DevOps organisation. We ask that users confirm and explicitly select the user account they wish to use in GCM Core.

At the moment we have no plans to add this WIA flow back.

Is there a reason you have `credential.interactive=false`?

**Comment by heatherjsun** [comment]
Our scenario occurs during Azure DevOps builds, therefore we cannot interact via prompt. Some tools we call during the build make calls to git, and we have been depending on GCM for Windows to authenticate. We have been looking into setting the `http.extraheader` in the git global config, as a workaround.

**Comment by mjcheetham** [comment]
I wonder how this used to work in the older GCM for Windows then?
Are your Azure DevOps build machines signed-in to a domain user account (and the machine domain joined)?

**Comment by mjcheetham** [comment]
Closing this issue as stale. If there is a feature request to support Windows authentication, or a bug, please open a new issue as appropriate.
