### ISSUE TITLE
Clarification on new GCM GitHub OAuth authorizations

### ISSUE THREAD

**Issue by garretwilson** [GitCredentialManager/git-credential-manager#312]
Could you provide more documentation with clarification on what is going on with this new GCM GitHub OAuth authorization, particularly on Windows 10?

Historically GCM has used the Windows 10 credential manager to store Git passwords, I believe. Today I upgraded to Git for Windows 2.30.2.windows.1. When I did a `git push` to GitHub, it took me to the GitHub page for me to authorize Git Credential Manager. Then my `git push` succeeded.

Familiar with basic OAuth workflows, I infer that rather than storing my GitHub password in the Windows 10 credential manager, GCM will now use GitHub OAuth to get some sort of authorization token, which it will store locally and use for authentication until it expires.

Do I understand that part correctly? (Maybe you could give a quick overview of that somewhere in the intro documentation?)

If so, then so far so good. When I go to https://github.com/settings/applications I see under "Authorized OAuth Apps" the listing "Git Credential Manager".

But what happens when I access GitHub from multiple computers?  Will I have multiple "Git Credential Manager" authorizations listed? How will I know which of them belong to which computer? Will I be able to add names the authorizations in order to tell them apart? Do they already have the device name somewhere that I haven't found?

**Comment by ldennington** [comment]
Hi @garretwilson! I know it's been awhile, but if you're still seeking answers on this, more info on GitHub OAuth Apps can be found [here](https://docs.github.com/en/developers/apps/getting-started-with-apps/differences-between-github-apps-and-oauth-apps). To answer your question about multiple computers and authorizations, according to documentation [here](https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#creating-multiple-tokens-for-oauth-apps) the same token and authorization is used for each user/application/scope combination, up to a maximum of 10 tokens.

**Comment by garretwilson** [comment]
I'm inferring that if I use GitHub personal access tokens then I won't need to mess with or worry about GitHub OAuth authentication?

I originally asked this question because my Git client automatically took me to a GitHub OAuth authorization page, as mentioned in the description. But setting up Git on a new computer I simply generated a personal access token and didn't neet to use OAuth. And "Git Credential Manager" is no longer listed under "Authorized OAuth Apps".

So is OAuth to large extent irrelevant with personal access tokens when working with Git clients?

**Comment by mjcheetham** [comment]
GCM supports both personal access tokens, and OAuth tokens for GitHub. If you prefer to use PATs and manually manage those then yes, you can ignore the OAuth options.

OAuth support was added in 2020 for GitHub and reduces the complexity required on behalf of the user to manually generate and manage PATs.

**Comment by garretwilson** [comment]
Thanks all for the useful information. The link that was given above compares GitHub Apps and OAuth Apps. I wonder if there is a document that discusses the tradeoffs between PATs and OAuth?
