### ISSUE TITLE
VS 2019 16.9.4 using GCM Core with "new Git experience" asks for passphrase on each git remote operation

### ISSUE THREAD

**Issue by david-bakin** [GitCredentialManager/git-credential-manager#328]
```
>git credential-manager-core --version
2.0.394-beta+3fc6791abf
```
Connecting to GitLab from Visual Studio 2019 16.9.4 with "GCM Core" selected in `Options>Source Control>Git Global Settings>Credential Helper`.  Each time I try a remote git operation via the VS 2019 Git menu (new experience) it asks again for a passphrase (via the GCM Core popup window).

Expected: Should only ask for the passphrase once, ever.  Or once/day.  Or even once/VS session.

**Comment by mjcheetham** [comment]
Hi @david-bakin we need some more information to be able to understand what's going on here.
Can you please follow these steps to get some more information and post the results back here?

1. Set the `GCM_TRACE` environment variable to an absolute file path (e.g., `C:\Users\<username>\Desktop\gcm.log`)
2. Restart Visual Studio
3. Perform a remote operation inside of VS (one of push, fetch, pull, clone) and enter credentials when prompted
4. Immediately perform the same operation again (and auth again if prompted)
5. Close VS
6. Open `C:\Program Files (x86)\Microsoft Visual Studio\2019\<edition>\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\libexec\git-core` and right click on `git-credential-manager-core.exe` and pick Properties > Details tab. Reply with the product version listed there.
7. Attach the file that has been created at the file path set in step (1)

Can you also answer the following questions:

- Does the same issue (being prompted for each remote operation) happen when you do remote operations from the command line or only inside of VS?
- Which Git host you are using? GitHub, Azure DevOps, Bitbucket, other
- Is your computer domain joined (or Azure AD joined)?
- Are you using an on-prem on cloud instance?
- Are you connecting over remote desktop?

**Comment by jim-liu** [comment]
I'm having the same issue but with Azure DevOps. Any remote operation will trigger the login prompt and create a new PAT on Azure DevOps. 

For me, 
- GCMC version is 2.0.318-beta+44acfafa98.
- the issue occurs in Visual Studio and when running the git command directly.
- the issue only affects repos with dev.azure.com/[org-name] URLs, but not those with [org-name].visualstudio.com URLs.
- computer is AAD-joined.

The attached log file is after running **git fetch** twice.

[log.txt](https://github.com/microsoft/Git-Credential-Manager-Core/files/6580334/log.txt)

**Comment by mjcheetham** [comment]
@jim-liu please can you run the following command and come back with the output

```
git config --get-all --show-origin credential.https://dev.azure.com.usehttppath
```

From the logs it looks like Git is not sending the full `path` parameter to GCM, which is needed for `dev.azure.com`-style URLs.

Can I also ask what version of Git for Windows you are using? `git --version`, and if you are also running in to this problem inside of an IDE like Visual Studio, or from the command line.

**Comment by jim-liu** [comment]
@mjcheetham running `git config --get-all --show-origin credential.https://dev.azure.com.usehttppath` gives an output that seems to be an empty line.

Git version is 2.29.2.windows.4.

I can reproduce the problem in PowerShell, VS 2019 (16.10.2), and VS Code (1.57.1).

**Comment by Torquai** [comment]
Experiencing the same issues here.

Visual Studio Pro 16.10.4
Git version 2.32.0.windows.2
Credential Manager Core 2.0.475+27

Switching VS->Options->Source Control->Git Global Settings->Credential Helper  to 'GCM For Windows' works for now, but following this issue to see when it gets resolved.

**Comment by mjcheetham** [comment]
Please can you try running the following command to see if this helps?

```shell
git config --global credential.https://dev.azure.com.useHttpPath true
```

**Comment by camachorm** [comment]
### I have the same problem:

```
git credential-manager-core --version
14:18:30.933094 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
14:18:30.934093 git.c:743               trace: exec: git-credential-manager-core --version
14:18:30.934093 run-command.c:668       trace: run_command: git-credential-manager-core --version
**2.0.605+97323d1677**
```

```
git --version
14:20:17.936453 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
14:20:17.937424 git.c:455               trace: built-in: git version
**git version 2.34.1.windows.1**
```

```
git config --get-all --show-origin credential.https://dev.azure.com.usehttppath
14:21:24.476635 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
14:21:24.477635 git.c:455               trace: built-in: git config --get-all --show-origin credential.https://dev.azure.com.usehttppath
14:21:24.478135 run-command.c:668       trace: run_command: unset GIT_PAGER_IN_USE; LESS=FRX LV=-c less
**file:C:/Program Files/Git/etc/gitconfig true
file:C:/Users/.gitconfig     true**
```

```
Microsoft Visual Studio Professional 2019
Version **16.11.8**
```

```
git config --get-all --show-origin credential.helper
14:23:42.579026 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
14:23:42.580531 git.c:455               trace: built-in: git config --get-all --show-origin credential.helper
14:23:42.581037 run-command.c:668       trace: run_command: unset GIT_PAGER_IN_USE; LESS=FRX LV=-c less
**file:C:/Program Files/Git/etc/gitconfig manager-core
file:C:/Users/.gitconfig
file:C:/Users/.gitconfig     manager-core**
```

### When doing two consecutive pulls from devops:

```
git pull devops master
14:25:21.599125 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
14:25:21.600632 git.c:455               trace: built-in: git pull devops master
14:25:21.602134 run-command.c:668       trace: run_command: git fetch --update-head-ok devops master
14:25:21.618130 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
14:25:21.619630 git.c:455               trace: built-in: git fetch --update-head-ok devops master
14:25:21.621631 run-command.c:668       trace: run_command: unset GIT_PREFIX; GIT_PROTOCOL=version=2 'ssh -i D:/authentication/ssh/xxxxx' -o SendEnv=GIT_PROTOCOL git@ssh.dev.azure.com 'git-upload-pack '\''v3/xxxxx'\'''
**Enter passphrase for key** 'D:/authentication/ssh/xxxxx':
14:25:25.982598 run-command.c:668       trace: run_command: git rev-list --objects --stdin --not --all --quiet --alternate-refs
From ssh.dev.azure.com:v3/xxxxxx
 * branch            master     -> FETCH_HEAD
14:25:26.029277 run-command.c:1597      run_processes_parallel: preparing to run up to 1 tasks
14:25:26.029277 run-command.c:1629      run_processes_parallel: done
14:25:26.029277 run-command.c:668       trace: run_command: git maintenance run --auto --no-quiet
14:25:26.044275 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
14:25:26.045776 git.c:455               trace: built-in: git maintenance run --auto --no-quiet
14:25:26.053775 run-command.c:668       trace: run_command: git merge FETCH_HEAD
14:25:26.069843 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
14:25:26.071369 git.c:455               trace: built-in: git merge FETCH_HEAD
Already up to date.

git pull devops master
14:25:39.173135 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
14:25:39.175135 git.c:455               trace: built-in: git pull devops master
14:25:39.176671 run-command.c:668       trace: run_command: git fetch --update-head-ok devops master
14:25:39.193167 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
14:25:39.194134 git.c:455               trace: built-in: git fetch --update-head-ok devops master
14:25:39.197132 run-command.c:668       trace: run_command: unset GIT_PREFIX; GIT_PROTOCOL=version=2 'ssh -i D:/authentication/ssh/xxxxx' -o SendEnv=GIT_PROTOCOL git@ssh.dev.azure.com 'git-upload-pack '\''v3/xxxxx'\'''
**Enter passphrase for key** 'D:/authentication/ssh/xxxxx':
14:25:44.729070 run-command.c:668       trace: run_command: git rev-list --objects --stdin --not --all --quiet --alternate-refs
From ssh.dev.azure.com:v3/xxxxx
 * branch            master     -> FETCH_HEAD
14:25:44.784863 run-command.c:1597      run_processes_parallel: preparing to run up to 1 tasks
14:25:44.784863 run-command.c:1629      run_processes_parallel: done
14:25:44.784863 run-command.c:668       trace: run_command: git maintenance run --auto --no-quiet
14:25:44.799362 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
14:25:44.800861 git.c:455               trace: built-in: git maintenance run --auto --no-quiet
14:25:44.808860 run-command.c:668       trace: run_command: git merge FETCH_HEAD
14:25:44.824859 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
14:25:44.826358 git.c:455               trace: built-in: git merge FETCH_HEAD
Already up to date.
```
I would expect that it would only ask for my passphrase once time and use GCM to store it so that in the same user it would only request the passphrase again after a reboot or preferably never :)

**Comment by mjcheetham** [comment]
Hello @camachorm,

> **Enter passphrase for key** 'D:/authentication/ssh/xxxxx':
> ...
> From ssh.dev.azure.com:v3/xxxxx

You are using SSH, not HTTPS. This mean GCM is not involved at all. Git doesn't consult credential helpers for SSH based remotes.

The passphrase you're being asked for is for the SSH key. You should be able to start the `ssh-agent` service to have it remember your SSH key passphrase for a period of time.

You can find some hopefully helpful instructions on configuring and starting the ssh-agent on Windows here:
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/working-with-ssh-key-passphrases

**Comment by camachorm** [comment]
Hi Matthew and thanks for replying,

I want to highlight that ssh-agent has been started and it was still
requesting the passphrase of the SSH certificate I use.

I will look into the link you provided and see if I had already read it or
if it brings me any new information.

Thanks again!
