### ISSUE TITLE
Authentication failure without prompt in Git for Windows with GCM Core

### ISSUE THREAD

**Issue by bencherian** [GitCredentialManager/git-credential-manager#391]
**Which version of GCM Core are you using?**

From a terminal, run `git-credential-manager-core version` and paste the output.

The above command does not run.

However, I can run `git credential-manager-core --version` which results in the following output:
```
2.0.474+95a180ab30
```

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [x] Other -  Internal Bitbucket server installation

**Can you access the remote repository directly in the browser using the remote URL?**

Yes. The webpage uses SSO.

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [x] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [x] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully. (Or at least I should be prompted for a password if necessary and it should be stored for future use.)

**Actual behavior**

I try running `git push --set-upstream origin master` and get an authenticated failed message without any prompts.

**Logs**

Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command. Review and redact any private information and attach the log.
```
11:56:26.794823 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
11:56:26.797823 git.c:455               trace: built-in: git push --verbose --set-upstream origin master
11:56:26.798823 run-command.c:667       trace: run_command: GIT_DIR=.git git remote-https origin  https://<redacted_username>@<redacted>.<redacted>.<redacted>/scm/<redacted-project>/<redacted-repo-name>.git
11:56:26.814855 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
11:56:26.816855 git.c:744               trace: exec: git-remote-https origin https://<redacted_username>@<redacted>.<redacted>.<redacted>/scm/<redacted-project>/<redacted-repo-name>.git
11:56:26.816855 run-command.c:667       trace: run_command: git-remote-https origin https://<redacted_username>@<redacted>.<redacted>.<redacted>/scm/<redacted-project>/<redacted-repo-name>.git
11:56:26.836854 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
https://<redacted_username>@<redacted>.<redacted>.<redacted>/scm/<redacted-project>/<redacted-repo-name>.git
11:56:27.076154 run-command.c:667       trace: run_command: 'C:/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe get'
11:56:27.232003 ...\Application.cs:80   trace: [RunInternalAsync] Version: 2.0.474.41365
11:56:27.235002 ...\Application.cs:81   trace: [RunInternalAsync] Runtime: .NET Framework 4.0.30319.42000
11:56:27.235002 ...\Application.cs:82   trace: [RunInternalAsync] Platform: Windows (x86-64)
11:56:27.235002 ...\Application.cs:83   trace: [RunInternalAsync] AppPath: C:\Program Files\Git\mingw64\libexec\git-core\git-credential-manager-core
11:56:27.235002 ...\Application.cs:84   trace: [RunInternalAsync] Arguments: get
11:56:27.280002 ...GitCommandBase.cs:35 trace: [ExecuteAsync] Start 'get' command...
11:56:27.287002 ...GitCommandBase.cs:49 trace: [ExecuteAsync] Detecting host provider for input:
11:56:27.287002 ...GitCommandBase.cs:50 trace: [ExecuteAsync]   protocol=https
11:56:27.287002 ...GitCommandBase.cs:50 trace: [ExecuteAsync]   host=<redacted>.<redacted>.<redacted>
11:56:27.287002 ...GitCommandBase.cs:50 trace: [ExecuteAsync]   username=<redacted_correct_username>
11:56:27.368001 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
11:56:27.369001 ...viderRegistry.cs:162 trace: [GetProviderAsync] Checking against 3 host providers registered with priority 'Normal'.
11:56:27.370001 ...viderRegistry.cs:154 trace: [GetProviderAsync] Querying remote URL for host provider auto-detection.
11:56:27.371001 ...pClientFactory.cs:54 trace: [CreateClient] Creating new HTTP client instance...
11:56:28.302004 ...viderRegistry.cs:162 trace: [GetProviderAsync] Checking against 1 host providers registered with priority 'Low'.
11:56:28.302004 ...GitCommandBase.cs:52 trace: [ExecuteAsync] Host provider 'Generic' was selected.
11:56:28.305004 ...\HostProvider.cs:128 trace: [GetCredentialAsync] Looking for existing credential in store with service=https://<redacted>.<redacted>.<redacted> account=<redacted_correct_username>...
11:56:28.308000 ...\HostProvider.cs:133 trace: [GetCredentialAsync] No existing credentials found.
11:56:28.308000 ...\HostProvider.cs:136 trace: [GetCredentialAsync] Creating new credential...
11:56:28.388552 ...icHostProvider.cs:60 trace: [GenerateCredentialAsync] Checking host 'https://<redacted>.<redacted>.<redacted>/' for Windows Integrated Authentication...
11:56:28.389553 ...Authentication.cs:36 trace: [GetIsSupportedAsync] HTTP: HEAD https://<redacted>.<redacted>.<redacted>/
11:56:28.389553 ...pClientFactory.cs:54 trace: [CreateClient] Creating new HTTP client instance...
11:56:29.184970 ...Authentication.cs:39 trace: [GetIsSupportedAsync] HTTP: Response code ignored.
11:56:29.184970 ...Authentication.cs:41 trace: [GetIsSupportedAsync] Inspecting WWW-Authenticate headers...
11:56:29.184970 ...Authentication.cs:46 trace: [GetIsSupportedAsync] Found WWW-Authenticate header for Negotiate
11:56:29.184970 ...icHostProvider.cs:69 trace: [GenerateCredentialAsync] Host supports WIA - generating empty credential...
11:56:29.184970 ...\HostProvider.cs:138 trace: [GetCredentialAsync] Credential created.
11:56:29.185970 ...GitCommandBase.cs:56 trace: [ExecuteAsync] End 'get' command...
11:56:29.239978 run-command.c:667       trace: run_command: 'C:/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe erase'
11:56:29.394089 ...\Application.cs:80   trace: [RunInternalAsync] Version: 2.0.474.41365
11:56:29.398086 ...\Application.cs:81   trace: [RunInternalAsync] Runtime: .NET Framework 4.0.30319.42000
11:56:29.398086 ...\Application.cs:82   trace: [RunInternalAsync] Platform: Windows (x86-64)
11:56:29.398086 ...\Application.cs:83   trace: [RunInternalAsync] AppPath: C:\Program Files\Git\mingw64\libexec\git-core\git-credential-manager-core
11:56:29.398086 ...\Application.cs:84   trace: [RunInternalAsync] Arguments: erase
11:56:29.442093 ...GitCommandBase.cs:35 trace: [ExecuteAsync] Start 'erase' command...
11:56:29.449128 ...GitCommandBase.cs:49 trace: [ExecuteAsync] Detecting host provider for input:
11:56:29.450094 ...GitCommandBase.cs:50 trace: [ExecuteAsync]   protocol=https
11:56:29.450094 ...GitCommandBase.cs:50 trace: [ExecuteAsync]   host=<redacted>.<redacted>.<redacted>
11:56:29.450094 ...GitCommandBase.cs:50 trace: [ExecuteAsync]   username=
11:56:29.450094 ...GitCommandBase.cs:50 trace: [ExecuteAsync]   password=********
11:56:29.531113 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
11:56:29.532114 ...viderRegistry.cs:162 trace: [GetProviderAsync] Checking against 3 host providers registered with priority 'Normal'.
11:56:29.534113 ...viderRegistry.cs:154 trace: [GetProviderAsync] Querying remote URL for host provider auto-detection.
11:56:29.534113 ...pClientFactory.cs:54 trace: [CreateClient] Creating new HTTP client instance...
11:56:30.488650 ...viderRegistry.cs:162 trace: [GetProviderAsync] Checking against 1 host providers registered with priority 'Low'.
11:56:30.489657 ...GitCommandBase.cs:52 trace: [ExecuteAsync] Host provider 'Generic' was selected.
11:56:30.491653 ...\HostProvider.cs:175 trace: [EraseCredentialAsync] Erasing stored credential in store with service=https://<redacted>.<redacted>.<redacted> account=...
11:56:30.494629 ...\HostProvider.cs:182 trace: [EraseCredentialAsync] No credential was erased.
11:56:30.494629 ...GitCommandBase.cs:56 trace: [ExecuteAsync] End 'erase' command...
fatal: Authentication failed for 'https://<redacted>.<redacted>.<redacted>/scm/<redacted-project>/<redacted-repo-name>.git/'
11:56:30.631598 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
11:56:30.633598 git.c:455               trace: built-in: git config --bool core.sparseCheckout
```

**Comment by mjcheetham** [comment]
Hey @bencherian,

```text
11:56:29.184970 ...Authentication.cs:41 trace: [GetIsSupportedAsync] Inspecting WWW-Authenticate headers...
11:56:29.184970 ...Authentication.cs:46 trace: [GetIsSupportedAsync] Found WWW-Authenticate header for Negotiate
11:56:29.184970 ...icHostProvider.cs:69 trace: [GenerateCredentialAsync] Host supports WIA - generating empty credential...
```

It looks like your server is advertising that it supports Windows Integrated Authentication (WIA)/Negotiate (NTLM, Kerberos, etc) and GCM is handing the responsibility for this kind of auth to Git (well, libcurl actually).

I guess in reality you don't want to use Negotiate? You can disable this erroneous WIA detection for that hostname by setting the following config:

```shell
$ git config --global credential.example.com.allowWindowsAuth false
```

..where `example.com` is your internal Git server's hostname ("`<redacted>.<redacted>.<redacted>`" in the logs).

https://aka.ms/gcmcore-config#credentialallowwindowsauth

**Comment by galsi** [comment]
I have the same problem 
Using  Azure DevOps Server (TFS/on-prem) AzureDevops server 2020

> $ GCM_TRACE=1 GIT_TRACE=1 git clone https://mazserver/mcollection/GIT/_git/emptyrepo c:\emptyrepo
> 14:00:36.880056 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
> 14:00:36.880056 git.c:455               trace: built-in: git clone https://mazserver/mcollection/GIT/_git/emptyrepo c:emptyrepo
> Cloning into 'c:emptyrepo'...
> 14:00:37.051950 run-command.c:668       trace: run_command: git remote-https origin https://mazserver/mcollection/GIT/_git/emptyrepo
> 14:00:37.411320 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
> 14:00:37.411320 git.c:743               trace: exec: git-remote-https origin https://mazserver/mcollection/GIT/_git/emptyrepo
> 14:00:37.411320 run-command.c:668       trace: run_command: git-remote-https origin https://mazserver/mcollection/GIT/_git/emptyrepo
> 14:00:37.505054 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
> 14:00:37.583190 run-command.c:668       trace: run_command: 'C:/Program\ Files\ \(x86\)/Git\ Credential\ Manager\ Core/git-credential-manager-core.exe get'
> 14:00:38.895700 ...\Application.cs:95   trace: [RunInternalAsync] Version: 2.0.567.18224
> 14:00:38.911348 ...\Application.cs:96   trace: [RunInternalAsync] Runtime: .NET Framework 4.0.30319.42000
> 14:00:38.911348 ...\Application.cs:97   trace: [RunInternalAsync] Platform: Windows (x86-64)
> 14:00:38.911348 ...\Application.cs:98   trace: [RunInternalAsync] OSVersion: 10.0 (build 17763)
> 14:00:38.911348 ...\Application.cs:99   trace: [RunInternalAsync] AppPath: C:\Program Files (x86)\Git Credential Manager Core\git-credential-manager-core.exe
> 14:00:38.911348 ...\Application.cs:100  trace: [RunInternalAsync] Arguments: get
> 14:00:39.005059 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'get' command...
> 14:00:39.020691 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
> 14:00:39.020691 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   protocol=https
> 14:00:39.020691 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   host=mazserver
> 14:00:40.567582 ...viderRegistry.cs:147 trace: [GetProviderAsync] Performing auto-detection of host provider.
> 14:00:41.380065 ...viderRegistry.cs:152 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
> 14:00:41.380065 ...viderRegistry.cs:160 trace: [GetProviderAsync] Checking against 3 host providers registered with priority 'Normal'.
> 14:00:41.395705 ...viderRegistry.cs:175 trace: [GetProviderAsync] Querying remote URL for host provider auto-detection.
> info: detecting host provider for 'https://mazserver/'...
> 14:00:41.395705 ...pClientFactory.cs:58 trace: [CreateClient] Creating new HTTP client instance...
> 14:00:45.583216 ...etHostProvider.cs:70 trace: [IsSupported] Host isn't supported as Bitbucket
> 14:00:45.583216 ...viderRegistry.cs:160 trace: [GetProviderAsync] Checking against 1 host providers registered with priority 'Low'.
> 14:00:45.583216 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'Generic' was selected.
> 14:00:45.598814 ...\HostProvider.cs:126 trace: [GetCredentialAsync] Looking for existing credential in store with service=https://mazserver account=...
> 14:00:47.192580 ...\HostProvider.cs:131 trace: [GetCredentialAsync] No existing credentials found.
> 14:00:47.192580 ...\HostProvider.cs:134 trace: [GetCredentialAsync] Creating new credential...
> 14:00:48.801937 ...icHostProvider.cs:58 trace: [GenerateCredentialAsync] Checking host 'https://mazserver/' for Windows Integrated Authentication...
> 14:00:48.801937 ...Authentication.cs:34 trace: [GetIsSupportedAsync] HTTP: HEAD https://mazserver/
> 14:00:48.801937 ...pClientFactory.cs:58 trace: [CreateClient] Creating new HTTP client instance...
> 14:00:52.801926 ...Authentication.cs:37 trace: [GetIsSupportedAsync] HTTP: Response code ignored.
> 14:00:52.801926 ...Authentication.cs:39 trace: [GetIsSupportedAsync] Inspecting WWW-Authenticate headers...
> 14:00:52.801926 ...Authentication.cs:44 trace: [GetIsSupportedAsync] Found WWW-Authenticate header for Negotiate
> 14:00:52.801926 ...Authentication.cs:49 trace: [GetIsSupportedAsync] Found WWW-Authenticate header for NTLM
> 14:00:52.801926 ...icHostProvider.cs:67 trace: [GenerateCredentialAsync] Host supports WIA - generating empty credential...
> 14:00:52.801926 ...\HostProvider.cs:136 trace: [GetCredentialAsync] Credential created.
> 14:00:52.801926 ...GitCommandBase.cs:54 trace: [ExecuteAsync] End 'get' command...
> 14:00:52.864462 run-command.c:668       trace: run_command: 'C:/Program\ Files\ \(x86\)/Git\ Credential\ Manager\ Core/git-credential-manager-core.exe erase'
> 14:00:54.098714 ...\Application.cs:95   trace: [RunInternalAsync] Version: 2.0.567.18224
> 14:00:54.114356 ...\Application.cs:96   trace: [RunInternalAsync] Runtime: .NET Framework 4.0.30319.42000
> 14:00:54.114356 ...\Application.cs:97   trace: [RunInternalAsync] Platform: Windows (x86-64)
> 14:00:54.114356 ...\Application.cs:98   trace: [RunInternalAsync] OSVersion: 10.0 (build 17763)
> 14:00:54.114356 ...\Application.cs:99   trace: [RunInternalAsync] AppPath: C:\Program Files (x86)\Git Credential Manager Core\git-credential-manager-core.exe
> 14:00:54.114356 ...\Application.cs:100  trace: [RunInternalAsync] Arguments: erase
> 14:00:54.192471 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'erase' command...
> 14:00:54.208109 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
> 14:00:54.208109 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   protocol=https
> 14:00:54.208109 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   host=mazserver
> 14:00:54.208109 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   username=
> 14:00:54.208109 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   password=********
> 14:00:55.739603 ...viderRegistry.cs:147 trace: [GetProviderAsync] Performing auto-detection of host provider.
> 14:00:56.504978 ...viderRegistry.cs:152 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
> 14:00:56.520622 ...viderRegistry.cs:160 trace: [GetProviderAsync] Checking against 3 host providers registered with priority 'Normal'.
> 14:00:56.520622 ...viderRegistry.cs:175 trace: [GetProviderAsync] Querying remote URL for host provider auto-detection.
> info: detecting host provider for 'https://mazserver/'...
> 14:00:56.520622 ...pClientFactory.cs:58 trace: [CreateClient] Creating new HTTP client instance...
> 14:01:00.708097 ...etHostProvider.cs:70 trace: [IsSupported] Host isn't supported as Bitbucket
> 14:01:00.708097 ...viderRegistry.cs:160 trace: [GetProviderAsync] Checking against 1 host providers registered with priority 'Low'.
> 14:01:00.708097 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'Generic' was selected.
> 14:01:00.708097 ...\HostProvider.cs:173 trace: [EraseCredentialAsync] Erasing stored credential in store with service=https://mazserver account=...
> 14:01:02.333102 ...\HostProvider.cs:180 trace: [EraseCredentialAsync] No credential was erased.
> 14:01:02.333102 ...GitCommandBase.cs:54 trace: [ExecuteAsync] End 'erase' command...
> 14:01:02.348715 run-command.c:668       trace: run_command: 'git credential-manager-core erase'
> 14:01:02.942447 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
> 14:01:02.958096 git.c:743               trace: exec: git-credential-manager-core erase
> 14:01:02.958096 run-command.c:668       trace: run_command: git-credential-manager-core erase
> 14:01:03.926872 ...\Application.cs:95   trace: [RunInternalAsync] Version: 2.0.605.12951
> 14:01:03.942544 ...\Application.cs:96   trace: [RunInternalAsync] Runtime: .NET Framework 4.0.30319.42000
> 14:01:03.942544 ...\Application.cs:97   trace: [RunInternalAsync] Platform: Windows (x86-64)
> 14:01:03.942544 ...\Application.cs:98   trace: [RunInternalAsync] OSVersion: 10.0 (build 17763)
> 14:01:03.942544 ...\Application.cs:99   trace: [RunInternalAsync] AppPath: C:\Program Files\Git\mingw64\libexec\git-core\git-credential-manager-core.exe
> 14:01:03.942544 ...\Application.cs:100  trace: [RunInternalAsync] Arguments: erase
> 14:01:04.051818 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'erase' command...
> 14:01:04.083080 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
> 14:01:04.083080 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   protocol=https
> 14:01:04.083080 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   host=mazserver
> 14:01:04.083080 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   username=
> 14:01:04.083080 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   password=********
> 14:01:05.661261 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
> 14:01:06.489334 ...viderRegistry.cs:158 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
> 14:01:06.489334 ...viderRegistry.cs:166 trace: [GetProviderAsync] Checking against 3 host providers registered with priority 'Normal'.
> 14:01:06.489334 ...viderRegistry.cs:181 trace: [GetProviderAsync] Querying remote URL for host provider auto-detection.
> 14:01:06.505010 ...pClientFactory.cs:58 trace: [CreateClient] Creating new HTTP client instance...
> 14:01:10.676813 ...etHostProvider.cs:70 trace: [IsSupported] Host isn't supported as Bitbucket
> 14:01:10.676813 ...viderRegistry.cs:166 trace: [GetProviderAsync] Checking against 1 host providers registered with priority 'Low'.
> 14:01:10.676813 ...viderRegistry.cs:234 trace: [GetProviderAsync] Remembering host provider for 'https://mazserver/' as 'generic'...
> 14:01:11.098728 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'Generic' was selected.
> 14:01:11.098728 ...\HostProvider.cs:173 trace: [EraseCredentialAsync] Erasing stored credential in store with service=https://mazserver account=...
> 14:01:12.676878 ...\HostProvider.cs:180 trace: [EraseCredentialAsync] No credential was erased.
> 14:01:12.676878 ...GitCommandBase.cs:54 trace: [ExecuteAsync] End 'erase' command...
> 14:01:12.692447 run-command.c:668       trace: run_command: 'C:/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe erase'
> 14:01:13.958122 ...\Application.cs:95   trace: [RunInternalAsync] Version: 2.0.605.12951
> 14:01:13.989335 ...\Application.cs:96   trace: [RunInternalAsync] Runtime: .NET Framework 4.0.30319.42000
> 14:01:13.989335 ...\Application.cs:97   trace: [RunInternalAsync] Platform: Windows (x86-64)
> 14:01:13.989335 ...\Application.cs:98   trace: [RunInternalAsync] OSVersion: 10.0 (build 17763)
> 14:01:13.989335 ...\Application.cs:99   trace: [RunInternalAsync] AppPath: C:\Program Files\Git\mingw64\libexec\git-core\git-credential-manager-core.exe
> 14:01:13.989335 ...\Application.cs:100  trace: [RunInternalAsync] Arguments: erase
> 14:01:14.083119 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'erase' command...
> 14:01:14.098752 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
> 14:01:14.098752 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   protocol=https
> 14:01:14.098752 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   host=mazserver
> 14:01:14.098752 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   username=
> 14:01:14.098752 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   password=********
> 14:01:15.708112 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
> 14:01:16.489340 ...viderRegistry.cs:158 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
> 14:01:16.489340 ...viderRegistry.cs:166 trace: [GetProviderAsync] Checking against 3 host providers registered with priority 'Normal'.
> 14:01:16.489340 ...viderRegistry.cs:181 trace: [GetProviderAsync] Querying remote URL for host provider auto-detection.
> 14:01:16.505055 ...pClientFactory.cs:58 trace: [CreateClient] Creating new HTTP client instance...
> 14:01:20.661258 ...etHostProvider.cs:70 trace: [IsSupported] Host isn't supported as Bitbucket
> 14:01:20.661258 ...viderRegistry.cs:166 trace: [GetProviderAsync] Checking against 1 host providers registered with priority 'Low'.
> 14:01:20.661258 ...viderRegistry.cs:234 trace: [GetProviderAsync] Remembering host provider for 'https://mazserver/' as 'generic'...
> 14:01:21.098783 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'Generic' was selected.
> 14:01:21.098783 ...\HostProvider.cs:173 trace: [EraseCredentialAsync] Erasing stored credential in store with service=https://mazserver account=...
> 14:01:22.942483 ...\HostProvider.cs:180 trace: [EraseCredentialAsync] No credential was erased.
> 14:01:22.942483 ...GitCommandBase.cs:54 trace: [ExecuteAsync] End 'erase' command...
> fatal: Authentication failed for 'https://mazserver/mcollection/GIT/_git/emptyrepo/'

**Comment by mjcheetham** [comment]
> Could I ask why does the Git advertise this Windows Integrated Authentication and fails authentication otherwise by default?

@kolesnykandrii, Git is not advertising the support for Negotiate/WIA authentication.. your Git _server/host_ is advertising it!

---

> I have the same problem
> Using Azure DevOps Server (TFS/on-prem) AzureDevops server 2020

@galsi, Azure DevOps Server supports Negotiate/WIA when configured correctly on your domain. It looks like GCM is letting Git/libcurl try to do authentication via Negotiate but it's failing. One likely reason for this is the _current logged-in Windows user_ does not have permissions on your `https://mazserver` Azure DevOps Server instance.

If you are _not_ using or expecting to use WIA with this server, please force GCM to use a simple username/password prompt by setting the configuration as below:

```batch
git config --global credential.https://mazserver.allowWindowsAuth false
```
