### ISSUE TITLE
Authentication failure in WSL 2 and VS Code DevContainer

### ISSUE THREAD

**Issue by ThomasPiskol** [GitCredentialManager/git-credential-manager#394]
**Which version of GCM Core are you using?**

2.0.475+27fbadca1d

**Which Git host provider are you trying to connect to?**

* [X] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

* [X] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [ ] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [X] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [X] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

Cloning fails and a command prompt is asking for the password. Same behaviour in WSL 2 command line and VS Code running a DevContainer.

Authentication is successful if the git operation is performed directly in Windows 10.

**Logs**

[wsl2.log](https://github.com/microsoft/Git-Credential-Manager-Core/files/6802982/wsl2.log)

**Comment by StevenLiekens** [comment]
I had the same error after updating Git for Windows to 2.33

> fatal: Cannot determine the organization name for this 'dev.azure.com' remote URL. Ensure the `credential.useHttpPath` configuration value is set, or set the organization name as the user in the remote URL '{org}@dev.azure.com'.

I don't know if this is a bug in the new credential manager or what, but this fixed it for me:

``` sh
# in WSL2
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager.exe"
```

**Comment by mjcheetham** [comment]
@ThomasPiskol, @StevenLiekens can I ask you both:

1. How did you configure Git running in WSL to call Git Credential Manager? (what steps did you follow)
2. Do you also have Git for Windows installed, in addition to Git inside of your WSL distribution?

**Comment by StevenLiekens** [comment]
I followed these steps for WSL2
https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-credential-manager-setup

```sh
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe"
```

This was all that was needed. I was running Git for Windows version 2.29 and Git version 2.25 in WSL (ubuntu-20.04). The error started showing the moment I updated Git for Windows to version 2.33. 

I can confirm that setting `useHttpPath` resolves my issue but I do not understand what changed.

**Comment by vtbassmatt** [comment]
@vtbassmatt to document

**Comment by jamesjohnmcguire** [comment]
I'm using: `git version 2.45.2.windows.1`

I found that the correct path to the credential manager was (This path has not been mentioned before):

`C:\Program Files\Git\mingw64\bin\git-credential-manager.exe`

Thus setting the following in WSL, got things working:

`git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager.exe"
`

**Comment by Mr-DJ** [comment]
On some systems now it is `C:\Program Files\Git\mingw64\bin\git-credential-wincred.exe`

Ran  `git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-wincred.exe"` to get it working again.
