### ISSUE TITLE
documentation: Add uninstall instructions for linux

### ISSUE THREAD

**Issue by soypat** [GitCredentialManager/git-credential-manager#413]
Running the following (macOS instructions) did not work.
```shell
sudo /usr/local/share/gcm-core/uninstall.sh
```

**Comment by mjcheetham** [comment]
Hi @soypat, can you elaborate on what happened when you ran the uninstall script?
How did you install GCM Core on macOS? Via Homebrew or the pkg from the releases page?

**Comment by soypat** [comment]
Platform is Linux, not OSx! I managed to "uninstall" it running `git-credential-manager-core unconfigure` and `rm $(which git-credential...)`... but this was blind luck as I took a lucky guess at the unconfigure command and you can barely say removing the binary is a complete uninstall.
