### ISSUE TITLE
Bitbucket authentication workflow should support OAuth only flow

### ISSUE THREAD

**Issue by navneetkarnani** [GitCredentialManager/git-credential-manager#427]
**Which version of GCM Core are you using?**

From a terminal, run `git-credential-manager-core --version` and paste the output.
2.0.498+7ad55fb809 (macOS)

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [x] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**
* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

**Expected behavior**

On `git clone https://bitbucket.org/orgname/reponame`, the workflow should go directly to the browser 2FA or, have a button on the dialog to use 2FA instead. That way, accounts that need a "Login with Google" don't need to unnecessarily create a "app password", which is not required in the case of a 2FA anyways.

**Actual behavior**

On `git clone https://bitbucket.org/orgname/reponame`, the Atlassian Login dialog comes up. This requires that a username/password be entered before the 2FA redirect in the browser is opened. 

**Logs**

Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command. Review and redact any private information and attach the log.

**Comment by mminns** [comment]
Better late than never. :)

OK for Bitbucket Server/DC is looks like the following URL can be used to check login options:

https://stash.atlassian.com/rest/authconfig/1.0/login-options

**Comment by vtbassmatt** [comment]
Lobbing this one to @mminns in case he has time to address.

**Comment by mjcheetham** [comment]
I have implemented a way to go straight to the OAuth flow from the first dialog (avoiding the need to use a valid username and password) in #579. This will be available in the next release.
