### ISSUE TITLE
Authentication fails once, then works.

### ISSUE THREAD

**Issue by Rintse** [GitCredentialManager/git-credential-manager#443]
**Which version of GCM Core are you using?**
`2.0.498+7ad55fb809`

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [X] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

From a terminal, run `git remote -v` to see your remote URL.

* [X] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**Expected behavior**

_When pushing_
I am authenticated and my Git operation completes successfully.

**Actual behavior**

After a reboot (first `git push`), I get the following error:
```
remote: Repository not found.
fatal: Authentication failed for ...
```
Then, after a second `git push`
```
Select an authentication method for 'https://github.com/':
  1. Web browser (default)
  2. Personal access token
option (enter for default): ...
```

Here are the logs for a unsuccessful, and a successful authentication.
[git_bad.log](https://github.com/microsoft/Git-Credential-Manager-Core/files/7145100/git_bad.log)
[git.log](https://github.com/microsoft/Git-Credential-Manager-Core/files/7145101/git.log)

Git is configured as follows:
```
...
[credential]
    credentialStore = secretservice
    helper = /usr/bin/git-credential-manager-core
...
```

**Comment by mjcheetham** [comment]
Hmm.. that's a strange behaviour! I don't see any obvious errors in the trace logs.

It looks like GCM is successfully retrieving the stored credential from the Secret Service (via `libsecret`) and handing this back to Git..

```text
17:41:21.379561 ...er/Application.cs:84 trace: [RunInternalAsync] Arguments: get
17:41:21.510551 ...GitCommandBase.cs:35 trace: [ExecuteAsync] Start 'get' command...
17:41:21.523946 ...GitCommandBase.cs:49 trace: [ExecuteAsync] Detecting host provider for input:
17:41:21.525630 ...GitCommandBase.cs:50 trace: [ExecuteAsync] 	protocol=https
17:41:21.525656 ...GitCommandBase.cs:50 trace: [ExecuteAsync] 	host=github.com
17:41:21.549209 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
17:41:21.551118 ...viderRegistry.cs:162 trace: [GetProviderAsync] Checking against 3 host providers registered with priority 'Normal'.
17:41:21.552985 ...GitCommandBase.cs:52 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
17:41:21.556910 .../HostProvider.cs:128 trace: [GetCredentialAsync] Looking for existing credential in store with service=https://github.com account=...
17:41:21.637491 .../HostProvider.cs:142 trace: [GetCredentialAsync] Existing credential found.
17:41:21.638567 ...GitCommandBase.cs:56 trace: [ExecuteAsync] End 'get' command...
```

.. only to have Git tell us the credential is bad and must be erased..

```text
17:41:21.770178 run-command.c:663       trace: run_command: '/usr/bin/git-credential-manager-core erase'
```


@rintse, a few questions:

1. After a reboot and you try a second `git push` (for example), do you have to keep authenticating each time, or only once/until the next reboot?
2. What is the full remote URL of the repository you are using? Run `git remote -vv` to print out the remote URLs.
3. What distribution and version of Linux are you using?
4. Has this only recently started happening with a new version of GCM or your OS?
5. After you reboot, can you check if your Keyring has been unlocked? On Debian/Ubuntu you can use the [`seahorse` application](https://en.wikipedia.org/wiki/Seahorse_(software)) to see the state of the default/login keyring (locked or unlocked).
6. Have you recently changed your local user computer login password?

Can you try running the following command from a terminal window in **two** instances: once after a successfully authenticated `push`, **and** one _right_ after a reboot, and then compare the output? Are they different?

```shell
printf "url=https://github.com\n\n" | git credential fill
```

You should see something similar to the below in both cases:

```shell
$ printf "url=https://github.com\n\n" | git credential fill
protocol=https
host=github.com
username=Rintse
password=gho_****************
```

**⚠️ Caution ⚠️**
**Please do not post the actual contents of the `password=...` line of the output as this is a secret token value!**

**Comment by Rintse** [comment]
Thanks for taking a look.

1. I only have to successfully authenticate once until reboot.
2. It happens on all my repositories. They all have the shape: `https://github.com/Rintse/xxx.git` for both fetch and push.
3. KDE Neon 5.22.5 (5.11.0-34-generic 20.04.1-Ubuntu)
4. I recently started using GCM. It worked fine for about 2 auths, then broke, resulting in this behaviour.
5. The default keyring is locked upon reboot.
6. No.

It actually seems the problem occurs only after a certain amount of time has expired, rather than after a reboot.
The username is missing the first time I call `fill`, then after a successful authentication, the username appears.

**Comment by mjcheetham** [comment]
> 5. The default keyring is locked upon reboot.

After a reboot, when you try a `git push` do you see a prompt to unlock the default keyring like below?

![image](https://user-images.githubusercontent.com/5658207/135084646-6cfa1c9a-86d4-4388-ad7f-d30393a5da1a.png)

I wonder if there's a problem with unlocking of the keyring in some instances (and the keyring is locked on reboot and after a period of time)? 🤔

**Comment by Rintse** [comment]
Yes, I do get that popup.

**Comment by mjcheetham** [comment]
If you open a tool like [`seahorse`](https://en.wikipedia.org/wiki/Seahorse_(software)) to manage keyrings, do you have any other keyrings listed such as `login`?

Can you try deleting the 'default keyring' if you have a 'login' keyring present too, and retry your Git command?

All I can think of is that there is some problem with the keyring unlocking.. GCM uses whatever the 'default' keyring according to `libsecret`.

**Comment by Rintse** [comment]
I do use seahorse. I have deleted the default keyring, leaving only login (and set login to default). 
No changes.

**Comment by mjcheetham** [comment]
Closing this issue as an external bug. After the investigation we see that libsecret is reporting success but failing to return the data from the credential store correctly, on first boot for this particular distro.

If this is still an issue even on newer versions of the distro/libsecret, it may be worth raising an issue with the distro or libsecret itself. There's not much more we can do to investigate deeper outside of our stack.
