### ISSUE TITLE
Publish packages to packages.microsoft.com/debian

### ISSUE THREAD

**Issue by hickford** [GitCredentialManager/git-credential-manager#447]
Hi. Please publish packages to the Microsoft repos for Debian https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian

    deb https://packages.microsoft.com/debian/11/prod bullseye main
    deb https://packages.microsoft.com/debian/10/prod buster main

**Comment by ldennington** [comment]
@mjcheetham Is this something we want to do? Refer to my comment in #422 about changing the deployment process to once again only use the `git` repo instead of different repos for every distro/version.

**Comment by felipecrs** [comment]
As this project isn't branded as Microsoft anymore, perhaps there is also the option of publishing to https://launchpad.net/~git-core.

**Comment by hickford** [comment]
Good point. And why not Debian itself? https://www.debian.org/devel/wnpp/requested

**Comment by mjcheetham** [comment]
We are no longer a Microsoft branded product, so will be unable to publish to the Microsoft package feeds. We already provide binaries and a Debian package on our [releases page](https://aka.ms/gcm/latest) that can be used.

Regarding publishing packages to other feeds - this isn't something the GCM maintainers are able to take on right now.
