### ISSUE TITLE
Use wingetcreate instead of mjcheetham/update-winget

### ISSUE THREAD

**Issue by vedantmgoyal2009** [GitCredentialManager/git-credential-manager#490]
Since winget team has released `wingetcreate`, we should use it instead of using the Github action. There are two reasons:
- Multi-manifests support more than one installer. By this, we can include both `user` and `all users` installers.
- If there will be any change in the manifest, wingetcreate would include those changes in the future generated manifests. For now, the GitHub action used for submitting the manifest uses the template provided in the `script`.

**Comment by ldennington** [comment]
After a discussion with the team, we dropped the winget release workflow (see #520) to direct users toward the desired path of installing along with Git for Windows instead.
