### ISSUE TITLE
Help deducing slowness with BitBucket

### ISSUE THREAD

**Issue by lugospod** [GitCredentialManager/git-credential-manager#526]
Hi,

I am trying to understand the tracing output received from running the GCM Core. I attached the screenshot where it is visible that it takes 10 seconds to run this command. Any idea how to proceed forward to determine the cause of this delay? I also attached the screenshot with the version of GCM Core.

I also added an issue on Git For Windows since they are calling on each Git get both get and store on credential manager [(Git for Windows Issue)](https://github.com/git-for-windows/git/issues/3531)

![image](https://user-images.githubusercontent.com/29342608/141383544-e4da2a95-01ef-4e0f-a279-c1f17c3935dd.png)
![image](https://user-images.githubusercontent.com/29342608/141383862-501679ce-00f8-417e-81bd-64b8386f68b7.png)

I added logs when running git credential manager core standalone and also two additional logs when running "git fetch" with protocol 1 and 2 (calling with protocol 2 is 50% faster then with protocol 1) but it is curious that that only impacts the times regarding git credential manager core. 
I also added git configuration and used full tracing both on git and on GCM Core.

I also noticed that it takes TWO seconds for each time to start the GCM Core (there is a 2 sec gap between trace log that git.exe is going to execute GET on GCM and first trace line of GCM).

Any hints on why is this happening or how to debug? Meanwhile, I will try to see if I can build GCMCore and switch the current one with my debug version with additional trace info...

[git-credential-manager-core.exe.txt](https://github.com/microsoft/Git-Credential-Manager-Core/files/7527593/git-credential-manager-core.exe.txt)
[log_Protocol_1.txt](https://github.com/microsoft/Git-Credential-Manager-Core/files/7527594/log_Protocol_1.txt)
[log_Protocol_2.txt](https://github.com/microsoft/Git-Credential-Manager-Core/files/7527595/log_Protocol_2.txt)
[config.txt](https://github.com/microsoft/Git-Credential-Manager-Core/files/7527596/config.txt)

tnx

**Comment by mjcheetham** [comment]
Hello @lugospod,

From the trace output it looks like you're running an old version of GCM!

```text
13:09:57.494663 ...\Application.cs:69   trace: [RunInternalAsync] Git Credential Manager version 2.0.280-beta+1f4c6db90f (Windows, .NET Framework 4.0.30319.42000) 'get'
```

The latest version of GCM Core (as bundled with the latest Git for Windows) is 2.0.567.
Please can you report back what version of Git for Windows you are using by running `git version`?

You can grab the latest Git for Windows (that includes the latest GCM Core) from here: https://gitforwindows.org/

**Comment by mjcheetham** [comment]
Closing this issue as no response since Nov 2021. If this is still an issue please can you open a new ticket. Thanks!
