### ISSUE TITLE
GCM in Linux package manager

### ISSUE THREAD

**Issue by gabe-microsoft** [GitCredentialManager/git-credential-manager#548]
**Feature description**

I understand that [GCM was very recently removed from the apt package repos](https://github.com/GitCredentialManager/git-credential-manager/issues/524), but it seems there's no replacement in place for getting the latest GCM version in Debian/Ubuntu. The README suggests downloading the latest .deb package from [https://github.com/GitCredentialManager/git-credential-manager/releases/latest](https://github.com/GitCredentialManager/git-credential-manager/releases/latest), which works fine interactively, but cannot be scripted. **There should be a URI that always points to the latest .deb package.**

The above would be very helpful for install scripts, but what about updates? The other advantage of the apt package was that it would get updated when the user runs `apt-get upgrade`. With the current distribution model, updates will likely never get installed. This seems like it will lead to many security holes going unpatched.

**Comment by dscho** [comment]
> The README suggests downloading the latest .deb package from https://github.com/GitCredentialManager/git-credential-manager/releases/latest, which works fine interactively, but cannot be scripted.

It can actually be scripted very easily. Something like this should get you started:

```sh
url="$(curl -s https://api.github.com/repos/GitCredentialManager/git-credential-manager/releases/latest |
  sed -n 's|.*\(https.*\.deb\).*|\1|p') &&
curl -Lo gcm.deb "$url" &&
sudo dpkg -i gcm.deb
```

> The above would be very helpful for install scripts, but what about updates?

If you have any good idea where to host this, please let's hear it. Since the move out of the `microsoft` org, Git Credential Manager can no longer be hosted on the Microsoft apt-get repositories.

**Comment by gabe-microsoft** [comment]
@dscho thank you for the script to download the latest, that is very helpful!

**Comment by felipecrs** [comment]
> If you have any good idea where to host this, please let's hear it.

The first thing that comes in my mind is PPA. Perhaps even the git-core official PPA? https://launchpad.net/~git-core/+archive/ubuntu/ppa

It would make our lifes soooo much easier.

**Comment by mjcheetham** [comment]
As mentioned in this issue, the team doesn't have the capacity to support publishing to package feeds but perhaps the new install from source script may work better for you:

https://github.com/GitCredentialManager/git-credential-manager/issues/447#issuecomment-1069666771
