### ISSUE TITLE
`brew install --cask git-credential-manager-core` fails

### ISSUE THREAD

**Issue by alexandervandekleutab** [GitCredentialManager/git-credential-manager#557]
This method of installation does not work for me. I get 
```sh
Error: Cask 'git-credential-manager-core' is unavailable: No Cask with this name exists.
```

**Comment by derrickstolee** [comment]
Hello, @alexandervandekleutab!

Did you also run the `tap` subcommand as shown here?

```
brew tap microsoft/git
brew install --cask git-credential-manager-core
```

**Comment by karlhorky** [comment]
Coming to this in 2023, it appears [the cask name is now `git-credential-manager` in the Homebrew installation instructions](https://github.com/git-ecosystem/git-credential-manager/blob/release/docs/install.md#homebrew-star)

(appears there is no longer a need to use the tap, just the command below):

```bash
brew install --cask git-credential-manager
```

**Comment by Yvancg** [comment]
I tried both methods and none work:

```
(base) XXX / % brew tap microsoft/git
==> Tapping microsoft/git
Cloning into '/usr/local/Homebrew/Library/Taps/microsoft/homebrew-git'...
remote: Enumerating objects: 481, done.
remote: Counting objects: 100% (200/200), done.
remote: Compressing objects: 100% (161/161), done.
remote: Total 481 (delta 127), reused 46 (delta 39), pack-reused 281
Receiving objects: 100% (481/481), 106.48 KiB | 879.00 KiB/s, done.
Resolving deltas: 100% (278/278), done.
Tapped 3 casks (35 files, 159.5KB).
(base) XXX / % brew install --cask git-credential-manager
Error: Cask 'git-credential-manager' is unavailable: No Cask with this name exists.
(base) XXX / % brew install --cask git-credential-manager-core
Error: Cask 'git-credential-manager-core' is unavailable: No Cask with this name exists.

```

**Comment by karlhorky** [comment]
@Yvancg not entirely sure what's going on with your problem, but maybe your Homebrew is out of date?

The `git-credential-manager` cask does exist as of Nov 2023:

- https://formulae.brew.sh/cask/git-credential-manager

**Comment by Yvancg** [comment]
Hi there. Thanks for the reply. Actually i downloaded the package instead of trying to install via the terminal and it worked just fine.

**Comment by smohadjer** [comment]
So the installation instructions here need to be updated, right? Brew throws error for me when I follow instructions there.

https://github.com/git-ecosystem/git-credential-manager/blob/release/docs/install.md

**Comment by karlhorky** [comment]
@smohadjer no, instructions match the good versions in the comments above.

Maybe you're experiencing a different issue?

**Comment by smohadjer** [comment]
Probably, on my macOS 10.15 `brew install --cask git-credential-manager` threw errors two days ago so I installed from package, but I tried the brew again and this time it worked.
