### ISSUE TITLE
Bring back brew package for Linux

### ISSUE THREAD

**Issue by marmelin** [GitCredentialManager/git-credential-manager#562]
hello there :) 

is it possible to bring back the brew package for Linux again? 
[https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/git-credential-manager.rb](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/git-credential-manager.rb)

**Comment by ldennington** [comment]
Closing, as we will soon release GCM as a [dotnet tool](https://github.com/GitCredentialManager/git-credential-manager/pull/886).
