### ISSUE TITLE
Latest debian package is broken

### ISSUE THREAD

**Issue by felipecrs** [GitCredentialManager/git-credential-manager#570]
From what it seems, the symlink is broken:

```console
❯ ls -lha /usr/local/bin/git-credential-manager-core
lrwxrwxrwx 1 1001 docker 45 Nov 16 12:45 /usr/local/bin/git-credential-manager-core -> ../share/gcm-core/git-credential-manager-core
```

**Comment by lynshi** [comment]
Seconded, the correct symlink for me is `../share/gcm-core/Release/git-credential-manager-core`.

**Comment by felipecrs** [comment]
Actually, I think the package should actually put files in gcm-core rather than gcm-core/Release, so that the symlink works.

**Comment by caskey** [comment]
@felipecrs I think that's the change that broke things. I worked around it like this:

```
cd /usr/local/bin
sudo ln -sf  ln -sf ../share/gcm-core/Release/git-credential-manager-core 
sudo ln -sf ../share/gcm-core/Release/GitHub.UI
```
When fixed the new package will replace those symlinks.

**Comment by adrientremblay** [comment]
Thirded. For me when I would try the command 
`git-credential-manager-core configure`
I would get 
`git-credential-manager-core: command not found`

So to fix this, I changed all the sym links in /usr/local/bin to point to ../share/gcm-core/**Release**/<file>, with the Release added.

Can someone fix this plz, should be pretty easy. Either change all the sym links to include the Release directory, or remove the Release directory and keep everything in gcm-core.

**Comment by ldennington** [comment]
This issue should be fixed with the [latest release](https://github.com/GitCredentialManager/git-credential-manager/releases/tag/v2.0.632). Please follow the instructions in the [README](https://github.com/GitCredentialManager/git-credential-manager#linux) to install this release.
