### ISSUE TITLE
> Is there a deprecation plan for the shims? It seems like a lot of hassle for low rewards if we have to carry those indefinitely. But if we can document their disappearance in, say, a year...

### ISSUE THREAD

**Issue by Joejoejoejo** [GitCredentialManager/git-credential-manager#571]
> Is there a deprecation plan for the shims? It seems like a lot of hassle for low rewards if we have to carry those indefinitely. But if we can document their disappearance in, say, a year...

That's a good point. I know @dscho was thinking of removing the Windows shim script from Git for Windows "at some future date".

Would you put the "this is temporary" message in the warnings too?

Regarding the rewards; I think this is really most important for Git for Windows users, and those who have installed outside of Homebrew (tarballs, macOS pkg, or Debian deb). Homebrew updates will do an uninstall first of the old one, so keeping clean.

_Originally posted by @mjcheetham in https://github.com/GitCredentialManager/git-credential-manager/issues/551#issuecomment-976659556_

**Comment by mjcheetham** [comment]
Looks like this issue was opened in error?
