### ISSUE TITLE
Add support for OAuth 2 in Bitbucket DC

### ISSUE THREAD

**Issue by mminns** [GitCredentialManager/git-credential-manager#573]
**Feature description**

OAuth 2 support is under development for Bitbucket DC. Currently GCM only supports Basic Auth for use with Bitbucket DC.

Extend the Bitbucket DC support in GCM to allow use of OAuth 2 and hence support using HTTP for remote Git operations in SSO environments.

**Comment by mminns** [comment]
WIP https://github.com/mminns/Git-Credential-Manager-Core/tree/issue/573-OAuth2-support-for-Bitbucket-DC

**Comment by ldennington** [comment]
Closing, since #607 is complete 🎉
