### ISSUE TITLE
Support Homebrew installation on Apple Silicon machines

### ISSUE THREAD

**Issue by ldennington** [GitCredentialManager/git-credential-manager#574]
**Feature description**

The default `HOMEBREW_PREFIX` is `/usr/local` on non-Apple silicon machines, and our macOS scripts assume that GCM will be installed in the `\share` sub-directory located in this path. However, it looks like [for Apple Silicon it's been updated to `/opt/homebrew`](https://docs.brew.sh/FAQ#why-is-the-default-installation-prefix-opthomebrew-on-apple-silicon). We should update our scripts to account for this scenario. For additional context, see #568.

**Comment by iamnae** [comment]
iamnae

**Comment by Datamance** [comment]
What is the workaround for this in the meantime?

**Comment by ldennington** [comment]
You can install this manually: [gcm-osx-arm64-2.0.785.pkg](https://github.com/GitCredentialManager/git-credential-manager/releases/download/v2.0.785/gcm-osx-arm64-2.0.785.pkg).

**Comment by wesleyhamburger-okta** [comment]
Unfortunately manual installation doesn't work for me in this case. Taken from the log - sorry I appreciate the log is not that helpful  

```
An error occurred while running scripts from the package “gcm-osx-arm64-2.0.785 (1).pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/whamburger/Downloads/gcm-osx-arm64-2.0.785%20(1).pkg#com.microsoft.gitcredentialmanager.component.pkg, PKInstallPackageIdentifier=com.microsoft.gitcredentialmanager, NSLocalizedDescription=An error occurred while running scripts from the package “gcm-osx-arm64-2.0.785 (1).pkg
```

**Comment by ldennington** [comment]
Ah yes - I imagine this is related to the changes I'm making here:

https://github.com/GitCredentialManager/git-credential-manager/pull/798/files

However, it's hard to be sure since I unfortunately do not have an M1 Mac 😬.

**Comment by wesleyhamburger-okta** [comment]
I'll wait till the release and see how it goes then and re-post here. I also seemed to have posted the wrong log as thats the arm installation 😢 but it was still the same outcome

**Comment by ldennington** [comment]
Completed with:

https://github.com/mjcheetham/update-homebrew/pull/10
https://github.com/GitCredentialManager/git-credential-manager/pull/798
https://github.com/microsoft/homebrew-git/pull/66

**Comment by solrevdev** [comment]
So, Homebrew did upgrade it but I did get an error that may be of interest

Error:

```bash
==> Upgrading 1 outdated package:
microsoft/git/git-credential-manager-core 2.0.785 -> 2.0.877
==> Upgrading git-credential-manager-core
==> Downloading https://github.com/GitCredentialManager/git-credential-manager/releases/down
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2
######################################################################## 100.0%
==> Running uninstall script /opt/homebrew/share/gcm-core/uninstall.sh
==> Purging files for version 2.0.877 of Cask git-credential-manager-core
Error: microsoft/git/git-credential-manager-core: uninstall script /opt/homebrew/share/gcm-core/uninstall.sh does not exist.
==> Casks with 'auto_updates true' or 'version :latest' will not be upgraded; pass `--greedy
```

Version: 

```bash
git-credential-manager-core --version
2.0.785+6074e4e3d3
```

System:

```
neofetch --off
solrevdev@macmini-2020.local
----------------------------
OS: macOS 13.0.1 22A400 arm64
Host: Macmini9,1
Kernel: 22.1.0
Uptime: 23 mins
Packages: 339 (brew)
Shell: zsh 5.8.1
Resolution: 2560x1440, 2560x1440
DE: Aqua
WM: Quartz Compositor
WM Theme: Blue (Light)
Terminal: iTerm2
Terminal Font: CaskaydiaCoveNerdFontComplete-Regular 16
CPU: Apple M1
GPU: Apple M1
Memory: 2238MiB / 16384MiB
```

**Comment by ldennington** [comment]
https://github.com/GitCredentialManager/git-credential-manager/pull/966 should resolve. Sorry for the pain here!

**Comment by codyzu** [comment]
I got around this by:

```bash
ln -s /usr/local/share/gcm-core /opt/homebrew/share/gcm-core
brew uninstall --cask git-credential-manager-core
brew install git-credential-manager-core
```

**Comment by toddjonker** [comment]
Thanks @codyzu !   I'm guessing one should also `rm /opt/homebrew/share/gcm-core` to cleanup the hack.

**Comment by bektur** [comment]
What helped me was running those commands.  

xcode-select --install
brew install gcc
