### ISSUE TITLE
Use full version in git tags, or remove the build number from the artifacts to ensure they match

### ISSUE THREAD

**Issue by felipecrs** [GitCredentialManager/git-credential-manager#577]
This would simplify a lot of scripts that automates the installation of GCM Core, especially on Linux. This is because, for any other project, it's common to use something like the following:

```bash
latest_version=$(basename "$(curl -fsSL -o /dev/null -w "%{url_effective}" https://github.com/docker/buildx/releases/latest)")

curl -fsSL "https://github.com/docker/buildx/releases/download/${latest_version}/buildx-${latest_version}.darwin-amd64"
```

But the problem of doing something similar with GCM Core is that the git tag does not match the version in the artifact name, and the build number is not guessable. I'm solving this issue by relying on a external service: https://github.com/Contextualist/glare

```bash
latest_version=$(basename "$(curl -fsSL -o /dev/null -w "%{url_effective}" https://github.com/GitCredentialManager/git-credential-manager/releases/latest)")

curl -fsSL "https://glare.vercel.app/GitCredentialManager/git-credential-manager@${latest_version}/gcmcore-linux_amd64.+.tar.gz$"
```

But it would be super cool if I could remove glare from the GCM Core installation flow.

This is especially a problem, because [there is no way to use a APT repository and thus leveraging the version resolution to APT itself.](https://github.com/GitCredentialManager/git-credential-manager/issues/447)

**Comment by mjcheetham** [comment]
As mentioned in this issue the new install from source script may well for this scenario?

https://github.com/GitCredentialManager/git-credential-manager/issues/447#issuecomment-1069666771

**Comment by felipecrs** [comment]
Not quite, it's not a good practice to rely on scripts available on the internet. All I need is to extract the .tar.gz to the correct folder anyway, so, it wasn't supposed to need a script for that.

In my specific case, I use chezmoi to manage my dotfiles, and I use its builtin feature of handling external archives to install my stuff from internet, so I have control over where and how they get installed.

Also, is there any reason why the request cannot be accommodated? It's seems very simple, I would be willing to submit a PR, I think.

**Comment by felipecrs** [comment]
@ldennington thanks a lot for the support!
