### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by hickford** [GitCredentialManager/git-credential-manager#589]
My [GitLab](https://gitlab.com/) account has [two-factor authentication](https://docs.gitlab.com/ee/user/profile/account/two_factor_authentication.html) enabled. When I try to git push, I get an authentication error:

```
Enter basic credentials for 'https://gitlab.com/':
Username: hickford
Password: 
remote: HTTP Basic: Access denied
remote: You must use a personal access token with 'read_repository' or 'write_repository' scope for Git over HTTP.
remote: You can generate one at https://gitlab.com/-/profile/personal_access_tokens
fatal: Authentication failed
```

The same happens with other GitLab instances such as https://gitlab.freedesktop.org/.

It would be awesome to support GitLab in the same way as GitHub, which offers me a choice of authentication methods, including 'web browser' (more convenient than personal access token).

```
Select an authentication method for 'https://github.com/':
  1. Web browser (default)
  2. Device code
  3. Personal access token
option (enter for default): 
```

**Comment by hickford** [comment]
Does this require any changes in GitLab, or could it be implemented by a patch here? GitLab already supports OAuth 2 https://docs.gitlab.com/ee/api/oauth2.html

https://gitlab.com/gitlab-org/gitlab/-/issues/225215

**Comment by vtbassmatt** [comment]
Hey @hickford, thanks for opening this issue and the adjacent PR. We're discussing whether we can add GitLab when (as you can see) they've actively said GCM support isn't on their radar. We want GCM to be excellent for all vendors, but have no interest in entering into a combative or one-way relationship.

Would you be interested in maintaining the GitLab provider in the meantime? We've got a similar arrangement for the Bitbucket provider where `mminns` takes primary responsibility for new features and evolving to match the Bitbucket service. (The GCM core maintainers still handle things like porting to new .NET versions, evolving the UI platform, etc. and do first-round triage on support issues.)

**Comment by vtbassmatt** [comment]
Update: we spoke about this offline and agreed that it's functionality we'd like to see in GCM, assuming you're willing to maintain the feature. GitLab users everywhere will rejoice 😁

**Comment by hickford** [comment]
Yes, definitely! Pull request https://github.com/GitCredentialManager/git-credential-manager/pull/591 is ready for review. It already works for me and solves my two-factor authentication problems.
