### ISSUE TITLE
Allow copying signin link

### ISSUE THREAD

**Issue by EMostafaAli** [GitCredentialManager/git-credential-manager#590]
**Feature description**

The following picture shows the default window for signing in GitHub. If you click the button it will open the link in the default browser. It will be helpful if a user can copy the link and paste it in a non-default browser.

In a frequent workflow, an user might have 2 GitHub accounts and signed different accounts in different browser. If the account signed in the default browser is different from the repository, the authentication will fail. Having the ability to copy the link will allow user to sign with the correct account.

![image](https://user-images.githubusercontent.com/11354102/147692907-4795b078-9a08-4f80-91eb-df3b8cfe837a.png)

**Comment by mjcheetham** [comment]
@EMostafaAli, we have shipped support for the device code flow that might help in this scenario. If you update the version of Git for Windows to the latest, you should see a dialog similar to this now:

![image](https://user-images.githubusercontent.com/5658207/148403776-ec6b468c-8f0a-4f4b-9b52-f7f411bea8c9.png)

Clicking "Sign in with a code" will present this screen and a code:

![image](https://user-images.githubusercontent.com/5658207/148403857-4321dac9-b271-4d5e-b932-f56a68738e91.png)

You can then navigate to <https://github.com/login/device> in your preferred browser/profile, and enter the code to complete sign in. This should unblock you for now.
