### ISSUE TITLE
Unable to use git in WSL - git: 'remote-https' is not a git command

### ISSUE THREAD

**Issue by benc-uk** [GitCredentialManager/git-credential-manager#602]
I have my gitconfig pointing at GCM as follows
```ini
[credential]
    helper = /mnt/c/Tools/gcm/git-credential-manager-core.exe
```

I have set the GIT_EXEC_PATH to my git install
```bash
export GIT_EXEC_PATH=/usr/bin/git
```

> NOTE I have tried also setting it to just `/usr/bin` same problem

When I run git clone I get the following error
```
git: 'remote-https' is not a git command. See 'git --help'.
```

**Comment by dscho** [comment]
> export GIT_EXEC_PATH=/usr/bin/git

This is incorrect: as per [the documentation](https://git-scm.com/docs/git#Documentation/git.txt---exec-pathltpathgt), this is supposed to point to a directory, not to a file. Besides, are you sure you want to hard-code it? It would be better to let the `git` executable figure out where its subcommands are located (hint: it is usually _not_ `/usr/bin/` but `/usr/libexec/git-core/`...).

**Comment by mjcheetham** [comment]
@benc-uk I assume you're trying to use GCM inside of your WSL instance, and use the `git` executable **inside of WSL**, _not_ Git for Windows?

If so, please follow the instructions we have here: https://aka.ms/gcm/wsl#configuring-wsl-without-git-for-windows


You shouldn't need to set the `GIT_EXEC_PATH` variable, but only the `WSLENV` variable inside of _Windows_.

**Comment by dscho** [comment]
@benc-uk would be nice to get an answer.

**Comment by mjcheetham** [comment]
Closing this issue due to lack of response. If the problem still persists, please reopen this issue or create a new one.
