### ISSUE TITLE
GIT_EXEC_PATH being wsl.localhost rather than wsl$

### ISSUE THREAD

**Issue by crlfrnc** [GitCredentialManager/git-credential-manager#611]
Hi,

I'm trying to use the credential manager installed on Windows 11, within WSL2, without Git for Windows installed, following along as per the documentation (Configuring WSL without Git for Windows).

However, whenever I try using a git command from within WSL2, it looks like it's still looking for the Windows executable (git.exe), rather than the Linux executable:

```
Unhandled Exception: System.Exception: Failed to locate 'git.exe' executable on the path.
   at GitCredentialManager.EnvironmentExtensions.LocateExecutable(IEnvironment environment, String program)
   at GitCredentialManager.CommandContext.GetGitPath(IEnvironment environment, IFileSystem fileSystem, ITrace trace)
   at GitCredentialManager.CommandContext..ctor(String appPath)
   at GitCredentialManager.Program.Main(String[] args)
```

This is running version: **2.0.632.34631**.

I had a quick look at how the credential manager works out which executable to use, and noticed that it checks to see if the git exec path starts with `\\wsl$\`.

I'm unsure if I've misconfigured something here, but on my fresh install of Windows 11, the translated path on my machine ends up being `\\wsl.localhost\Ubuntu\usr\lib\git-core`, which I checked with the following command in cmd.exe launched via WSL2:

```
C:\Windows>echo %WSLENV%
WT_SESSION:WT_SESSION::WT_PROFILE_ID:GIT_EXEC_PATH/wp:WT_PROFILE_ID

C:\Windows>echo %GIT_EXEC_PATH%
\\wsl.localhost\Ubuntu\usr\lib\git-core
```

Which I assume doesn't meet the `IsWslPath` check, so it then continues to look for git.exe.

I'm happy to work on a PR to add the additional prefix to the `IsWslPath` check if that ends up being the solution, but otherwise if there's something I've missed in setting this up, would be happy with that solution as well.

**Comment by mjcheetham** [comment]
We've merged in a change to support the new preferred `\\wsl.localhost` style paths to the main branch. This feature will go out in the next release.
