### ISSUE TITLE
Swedish character in password seems to cause authentication to fail

### ISSUE THREAD

**Issue by kria** [GitCredentialManager/git-credential-manager#615]
**Which version of GCM are you using?**

2.0.632+478753bbb7

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [x] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

I have created two new AD users kria_test2 and kria_test3. Both have identical 14 character passwords, except for one character which is an 'å' for kria_test2. If I do a `git fetch` I get *Authentication failed for &lt;url&gt;* for the user with the Swedish char in the password, while the other user authenticates correctly. Both users are able to login to the Azure DevOps Server web UI.

**Logs**
[gcm-successful-auth.txt](https://github.com/GitCredentialManager/git-credential-manager/files/7951889/gcm-successful-auth.txt)
[gcm-failed-auth.txt](https://github.com/GitCredentialManager/git-credential-manager/files/7951890/gcm-failed-auth.txt)

**Comment by mjcheetham** [comment]
Hello @kria please can you also set the `GIT_TRACE` and `GIT_TRACE_CURL` environment variables to capture what's happening on the network and report back?

From what I can see so far, GCM should be passing back the username and password that you enter to Git as UTF-8, which Git for Windows is aware of and should support. There may be a problem inside of Git/cURL or with your Azure DevOps Server. Until I see the curl logs it's hard to diagnose any further.

**Comment by kria** [comment]
Hi @mjcheetham, thanks for looking at this.

I'm attaching logs that also include the curl trace.
Authentication still failed when I bypassed GCM.

[git-successful-auth-220131.txt](https://github.com/GitCredentialManager/git-credential-manager/files/7969731/git-successful-auth-220131.txt)
[git-failed-auth-220131.txt](https://github.com/GitCredentialManager/git-credential-manager/files/7969730/git-failed-auth-220131.txt)
[git-failed-auth-gcm-bypass-220131.txt](https://github.com/GitCredentialManager/git-credential-manager/files/7969729/git-failed-auth-gcm-bypass-220131.txt)

**Comment by mjcheetham** [comment]
> Authentication still failed when I bypassed GCM.

This tells me there's something wrong with the terminal + Git + server interactions and not GCM.

Given this I'd recommend opening an issue on Git for Windows: https://github.com/git-for-windows/git/issues
