### ISSUE TITLE
Git config setting keys are stored in lowercase

### ISSUE THREAD

**Issue by hellznrg** [GitCredentialManager/git-credential-manager#617]
When running GCM for the first time on linux, it may complain that it doesn't know what kind of store to use. It says to either set GCM_CREDENTIAL_STORE environment variable or git config setting "credential.credentialStore" (note the capitalization). However, git config stores setting key names in all-lowercase as shown in the below screenshot.

![image](https://user-images.githubusercontent.com/452590/151640954-57e22eb7-3927-4ace-bbe2-adae1184e1cf.png)

GCM seems to think that git config stores key names with capitalization as-given, which is wrong.

![image](https://user-images.githubusercontent.com/452590/151641681-bb940085-59f7-472e-93c6-6c1d412b25df.png)

After setting the git config key-value pair, GCM doesn't recognize that it has been set because the same message keeps coming up.

**Comment by mjcheetham** [comment]
Git treats config names as case insensitive<sup>1</sup>, for example `core.editor` is the same as `CORE.EDITOR` or `cORe.EdITor`. There is no case normalisation performed on the entries when written to disk.

GCM [_should_ be resolving](https://github.com/GitCredentialManager/git-credential-manager/blob/4c4f3957c8a0a01e4f23af767318937b88793769/src/shared/Core/Settings.cs#L374-L381) all Git config entries following [the same rules](https://github.com/GitCredentialManager/git-credential-manager/blob/4c4f3957c8a0a01e4f23af767318937b88793769/src/shared/Core/GitConfigurationKeyComparer.cs), so `credential.credentialstore` should be the same as `credential.credentialStore`.

> After setting the git config key-value pair, GCM doesn't recognize that it has been set because the same message keeps coming up.

This would indicate some sort of bug somewhere. Please can you try running the following commands from a terminal and see what results you get? They should be the same.

```shell
# Set credential.credentialStore to "plaintext"
git config --global credential.credentialStore plaintext

# Ask Git for the value back with differing cases
git config --global credential.credentialStore    # note the upper case "S"
git config --global credential.credentialstore    # note the lower case "s"
```

Also what version of Git are you using? Please run `git --version` and report back.

> When running GCM for the first time on linux, [..]

You mention that you are running on Linux, but the screenshots are of a Windows Command Prompt window? Are you using some sort of SSH/remote setup?

---

**<sup>1</sup>** Sections and key/variable names are not case sensitive, but any subsection or URL-scope _are_ case sensitive. For example `credential.https://example.com.provider` is the same as `CREDENTIAL.https://example.com.PROVIDER`, but `credential.https://example.com.provider` is _different_ from `credential.HTTPS://EXAMPLE.COM.provider`.

**Comment by hellznrg** [comment]
Hi thanks I ran those commands to see what would be returned and it looks like git just treats everything as lowercase: 
![image](https://user-images.githubusercontent.com/452590/151787645-b521965f-e476-4fc8-9777-04542438e795.png)

I noticed this problem on the linux system belonging to the company I work for. I will try to recreate this issue on linux and post some screenshots.

**Comment by hellznrg** [comment]
This is what happens on linux. I unset the environment variable GCM_CREDENTIAL_STORE and then did the following operations:
![image](https://user-images.githubusercontent.com/452590/151788965-b136eb84-2159-45fe-8f6c-6af6559feeb6.png)

The only way to get it to work is to set the GCM_CREDENTIAL_STORE environment variable.

**Comment by hellznrg** [comment]
In any case I feel that the message displayed "Set the GCM_CREDENTIAL_STORE environment variable or the credential.credentialStore Git configuration setting to one of the following options:" is a bit misleading because it implies that git config is case-sensitive when it's not.

**Comment by mjcheetham** [comment]
Thanks for your reply @hellznrg. I think I can see what's happening from your terminal screenshot.

When you run the command `git config credential.credentialStore plaintext` you are setting the configuration setting _in the current local repository_.

When you subsequently run `git clone <url>`, Git will not be reading the previously set configuration since `clone` will create a new empty repository first before pulling data.

You need to set the `credential.credentialStore` setting _**globally**_ for this to take effect in all Git repositories. In other words you need to run:

```shell
git config --global credential.credentialStore plaintext
```

I have updated the Credential Store documentation to include an example where we show the use of `--global` in https://github.com/GitCredentialManager/git-credential-manager/commit/0d536c4831c1bed06dab67d6878993435ec13573.

**Comment by hellznrg** [comment]
Hi @mjcheetham thank you for that. It seems you are correct. I've run some tests and it does work as you say.

My original intention was to keep the config variable as local as possible as I didn't want it to pollute the global namespace. So I first started with a "git init", followed by "git config credential.credentialStore plaintext" and then "git clone ...". However as you mentioned, the "git clone" doesn't take into account the previously set local config variable.

So to deal with this issue, what I did is:

1. git config --global credential.credentialStore plaintext
2. git clone ...
3. git config --global --unset  credential.credentialStore
4. cd `<cloned folder>`
5. git config credential.credentialStore plaintext
6. git pull

And all seems to be good. There's probably a better way to do it:

1. mkdir `<folder>`
2. cd `<folder>`
2. git init
3. git config credential.credentialStore plaintext
3. `<set origin>`
4. git pull

Anyway, thanks for your help.

**Comment by mjcheetham** [comment]
You can also pass a configuration setting for any specific Git command, including the clone.

For example:

```shell
git -c "credential.credentialStore=plaintext" clone <url>
```

This will only apply to that clone command, and you'd likely still want to set the local config after clone.

**Comment by hellznrg** [comment]
Ah fantastic! Thank you for that. I'm only familiar with the basic commands
and prefer to use a GUI generally.

I learnt something new today! :) The -c option will come in handy.
