### ISSUE TITLE
 [GetIdentityServiceUriAsync] HTTP: Response 403 [Forbidden] when not Organisation owner

### ISSUE THREAD

**Issue by darrenb74** [GitCredentialManager/git-credential-manager#623]
**Which version of GCM are you using?**

2.0.498+7ad55fb809

**Which Git host provider are you trying to connect to?**

* [ X] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

* [X ] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [ ] Not applicable
* [X ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [ ] Not applicable
* [X ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

When I am set up as the Organization Owner then Git operation completes as normal, When not the owner I get a 403 Forbidden error when making call to LocationService api

**Logs**

14:08:13.209836 ...DevOpsRestApi.cs:119 trace: [CreatePersonalAccessTokenAsync] Getting Azure DevOps Identity Service endpoint...
14:08:13.212828 ...DevOpsRestApi.cs:169 trace: [GetIdentityServiceUriAsync] HTTP: GET https://dev.azure.com/xxxxx/_apis/ServiceDefinitions/LocationService2/951917AC-A960-4999-8464-E3F0AA25B381?api-version=1.0
14:08:14.852101 ...DevOpsRestApi.cs:173 trace: [GetIdentityServiceUriAsync] HTTP: Response 403 [Forbidden]

14:08:17.636395 ...\Authority.cs:375    trace: [GetIdentityServiceUri] failed to find Identity Service for 'https://dev.azure.com/xxxxx/_apis/ServiceDefinitions/LocationService2/951917AC-A960-4999-8464-E3F0AA25B381?api-version=1.0' via location service [403].
14:08:17.639383 ...\Authority.cs:136    trace: [GeneratePersonalAccessToken] ! error: 'Failed to find Identity Service for `https://xxxx@dev.azure.com/xxxxx/xxxxx/_git/xxxxx`.'.

Many Thanks

**Comment by mjcheetham** [comment]
Thanks for reporting this issue. We've reached out to our friends in Azure DevOps to try and assist with this problem. We can see no reason why this error should happen, and we cannot reproduce the problem. Hopefully they can shine some light on the underlying problem.

**Comment by ldennington** [comment]
I wanted to send an update that the Azure DevOps folks have asked us to create a ticket for this. One of the required fields in the ticket is Azure DevOps URL. Is this something you're able to provide @darrenb74? I see you redacted it above, so if you're not comfortable with this, you can visit [this site](https://1esbot-prod.azurewebsites.net/?Service=AzureDevOps) to generate a ticket yourself.

**Comment by darrenb74** [comment]
Hi,

I've managed to find a workaround where I create a PAT token directly in Azure Dev Ops then manually add it to the Windows Credential Manager.
Thanks
