### ISSUE TITLE
Severe memory leak in git-credential-manager-core on macOS

### ISSUE THREAD

**Issue by ianhlavats** [GitCredentialManager/git-credential-manager#625]
**Which version of GCM are you using?**

From a terminal, run `git credential-manager-core --version` and paste the output.

2.0.632+478753bbb7

I installed git-credential-manager-core with homebrew on macOS 12.2.1.

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [X] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

From a terminal, run `git remote -v` to see your remote URL.

* [X] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [X] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [X] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully without consuming huge amounts of RAM.

**Actual behavior**

Frequent and severe memory leaks with git-credential-manager-core on macOS 12.

The issue happens while connecting to GitHub over HTTPS. Connecting to GitHub over SSH seems to avoid the problem.

After some time, I see a message from macOS saying "Your system has run out of application memory". The top consumers are always a few instances of git-credential-manager-core. I have 96GB of RAM on my Mac and these processes regularly consume between 20-30GB of RAM each.

I sampled the process and have attached the file for reference. I'm also including a screenshot from activity monitor.

**Logs**

Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command. Review and redact any private information and attach the log.

If you are running inside of Windows Subsystem for Linux (WSL), you must also set an additional environment variable to enable tracing: `WSLENV=$WSLENV:GCM_TRACE`.
For example:

```shell
WSLENV=$WSLENV:GCM_TRACE:GIT_TRACE GCM_TRACE=1 GIT_TRACE=1 git fetch
```

<img width="696" alt="git_memory_leak1" src="https://user-images.githubusercontent.com/3005952/155744313-12b7b3b5-c8db-4fce-95eb-fd86baa5d5f5.png">
<img width="696" alt="git_memory_leak2" src="https://user-images.githubusercontent.com/3005952/155744320-0785af22-885c-4d08-a334-7c7d05328e62.png">

[sample_git-credential-manager-core.txt](https://github.com/GitCredentialManager/git-credential-manager/files/8142421/sample_git-credential-manager-core.txt)

**Comment by ianhlavats** [comment]
Hi @mjcheetham , 

It does not happen every time I use Git over HTTPS with GitHub. 

I occasionally use Git from the terminal for ad-hoc updates and git admin tasks but I use it more heavily from inside an IDE. 

I have also raised a ticket with JetBrains and they have replied that while there is a small possibility the IDE is misusing the Git API, this problem in particular appears to be located in git-credential-manager-core itself.

The way that JetBrains IDEs work is by periodically fetching from the Git repo in the background which is a different usage pattern than from the terminal. I notice this problem sometimes after a period of idle time when I'm away from my computer.  When I come back, the system is low on application memory and git-credential-manager-core is always the top consumer.

This problem has been going on for months... I only recently decided to reach out for support on it.

Regards,
Ian

**Comment by ldennington** [comment]
Hello!

Could you open a Terminal and run `GCM_TRACE=1 GIT_TRACE=1 git fetch`? And then share:

1. Whether it hangs
2. Whether a GUI is shown
3. Whether a `GitHub.UI.exe` is running
4. The trace logs (with secrets scrubbed)

Also, if you can provide the link to the JetBrains ticket, that would be great, as further interaction with them may be required.

**Note:** We have been unable to reproduce this on our Macs - at most GCM uses ~60 MB per instance.

**Comment by ianhlavats** [comment]
Hi @ldennington ,

Thanks for the follow up. Here is the output of the `git fetch` command:

```
GCM_TRACE=1 GIT_TRACE=1 git fetch
10:27:39.472199 git.c:440               trace: built-in: git fetch
10:27:39.479315 run-command.c:663       trace: run_command: GIT_DIR=.git git-remote-https origin https://github.com/******/******.git
10:27:39.737521 run-command.c:663       trace: run_command: '/usr/local/share/gcm-core/git-credential-manager-core get'
10:27:39.967346 ...re/Application.cs:95 trace: [RunInternalAsync] Version: 2.0.632.34631
10:27:39.980068 ...re/Application.cs:96 trace: [RunInternalAsync] Runtime: .NET 5.0.6
10:27:39.980124 ...re/Application.cs:97 trace: [RunInternalAsync] Platform: macOS (x86-64)
10:27:39.980145 ...re/Application.cs:98 trace: [RunInternalAsync] OSVersion: 12.3
10:27:39.980248 ...re/Application.cs:99 trace: [RunInternalAsync] AppPath: /usr/local/share/gcm-core/git-credential-manager-core
10:27:39.980310 ...e/Application.cs:100 trace: [RunInternalAsync] Arguments: get
10:27:40.030461 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'get' command...
10:27:40.039532 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
10:27:40.040558 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	protocol=https
10:27:40.040605 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	host=github.com
10:27:40.102136 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
10:27:40.117037 ...viderRegistry.cs:158 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
10:27:40.119269 ...viderRegistry.cs:166 trace: [GetProviderAsync] Checking against 3 host providers registered with priority 'Normal'.
10:27:40.120342 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
10:27:40.122725 .../HostProvider.cs:126 trace: [GetCredentialAsync] Looking for existing credential in store with service=https://github.com account=...
10:27:40.173356 .../HostProvider.cs:140 trace: [GetCredentialAsync] Existing credential found.
10:27:40.174058 ...GitCommandBase.cs:54 trace: [ExecuteAsync] End 'get' command...
10:27:40.386061 run-command.c:663       trace: run_command: '/usr/local/share/gcm-core/git-credential-manager-core store'
10:27:40.614112 ...re/Application.cs:95 trace: [RunInternalAsync] Version: 2.0.632.34631
10:27:40.626644 ...re/Application.cs:96 trace: [RunInternalAsync] Runtime: .NET 5.0.6
10:27:40.626695 ...re/Application.cs:97 trace: [RunInternalAsync] Platform: macOS (x86-64)
10:27:40.626715 ...re/Application.cs:98 trace: [RunInternalAsync] OSVersion: 12.3
10:27:40.626798 ...re/Application.cs:99 trace: [RunInternalAsync] AppPath: /usr/local/share/gcm-core/git-credential-manager-core
10:27:40.626857 ...e/Application.cs:100 trace: [RunInternalAsync] Arguments: store
10:27:40.691023 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'store' command...
10:27:40.700323 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
10:27:40.701332 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	protocol=https
10:27:40.701386 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	host=github.com
10:27:40.701405 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	username=********
10:27:40.701422 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	password=********
10:27:40.765603 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
10:27:40.780998 ...viderRegistry.cs:158 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
10:27:40.783268 ...viderRegistry.cs:166 trace: [GetProviderAsync] Checking against 3 host providers registered with priority 'Normal'.
10:27:40.784395 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
10:27:40.785779 .../HostProvider.cs:160 trace: [StoreCredentialAsync] Storing credential with service=https://github.com account=********...
10:27:40.851542 .../HostProvider.cs:162 trace: [StoreCredentialAsync] Credential was successfully stored.
10:27:40.851644 ...GitCommandBase.cs:54 trace: [ExecuteAsync] End 'store' command...
10:27:40.895270 run-command.c:663       trace: run_command: git fetch-pack --stateless-rpc --stdin --lock-pack --include-tag --thin https://github.com/******/******.git/
10:27:40.900767 git.c:440               trace: built-in: git fetch-pack --stateless-rpc --stdin --lock-pack --include-tag --thin https://github.com/******/******.git/
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 14 (delta 11), reused 14 (delta 11), pack-reused 0
10:27:41.198438 run-command.c:663       trace: run_command: git unpack-objects --pack_header=2,14
10:27:41.204168 git.c:440               trace: built-in: git unpack-objects --pack_header=2,14
Unpacking objects: 100% (14/14), done.
10:27:41.377257 run-command.c:663       trace: run_command: git rev-list --objects --stdin --not --all --quiet --alternate-refs
10:27:41.383009 git.c:440               trace: built-in: git rev-list --objects --stdin --not --all --quiet --alternate-refs
From https://github.com/******/******
   8a3a78c..08da027  0.5.0      -> origin/0.5.0
 * [new tag]         0.5.25     -> 0.5.25
10:27:41.444055 run-command.c:1616      run_processes_parallel: preparing to run up to 1 tasks
10:27:41.444094 run-command.c:1648      run_processes_parallel: done
10:27:41.444123 run-command.c:663       trace: run_command: git gc --auto
10:27:41.449506 git.c:440               trace: built-in: git gc --auto
```

Just a reminder that the issue only seems to happen from the IDE during background fetch.

The JetBrains ticket is here:

https://youtrack.jetbrains.com/issue/IDEA-289782

If it helps you reproduce the issue, it usually happens I'm usually working on 3 or 4 Swift projects at a time in JetBrains AppCode, each with a large number (around 30-40) dependencies managed by CocoaPods and integrated as development pods with paths to the local repos on my machine. 

I'm allocating 8GB of RAM to the IDE. I'm aware that child processes can have the same amount of RAM as their parent process, and if AppCode is forking a child git process for each repo with 8GB RAM, this could explain the application memory exhaustion.

If this is the case, then I'll have to explore other architectures for my project, for example, combining the dependent libraries into a single library or switching from development pods to non-development pods that are not linked to git repos but simply pulled from the CocoaPods repository.

Will update the JetBrains ticket with the same details.

Thanks again for your help.

Regards,
Ian

**Comment by ianhlavats** [comment]
Hi @ldennington ,

To answer your questions: 

1. The command does not hang. 
2. A GUI is shown the first time I connect to the repo, and then credentials are cached.
3. I am on Mac... why would a .exe file be running? Is `GitHub.UI.exe` a component of git-credential-manager-core built for Mac but named using Windows executable naming conventions? If so that seems like a strange design decision to me and suggest a possible lack of understanding of Mac software engineering guidelines... is `git-credential-manager-core` really designed and optimized for Mac? Was the Mac-compatible version of the software ported from a Windows codebase or was it designed from the ground up for Mac? If it was ported, perhaps there are some gaps in memory management that were not address during the code migration process?
4. Please see above.

Thanks.

Regards,
Ian

**Comment by ldennington** [comment]
> Hi @ldennington ,
> 
> To answer your questions:
> 
> 1. The command does not hang.
> 2. A GUI is shown the first time I connect to the repo, and then credentials are cached.
> 3. I am on Mac... why would a .exe file be running? I did not see any such process. Is `GitHub.UI.exe` a component of git-credential-manager-core built for Mac but named using Windows executable naming conventions? If so that seems like a strange design decision to me and suggest a possible lack of understanding of Mac software development... is `git-credential-manager-core` really designed and optimized for Mac? Was the Mac-compatible version of the software ported from a Windows codebase or was it designed from the ground up for Mac? If it was ported, perhaps there are some gaps in memory management that were not addressed during the code migration process?

My apologies, I misspoke. GCM was designed from its inception as a cross-platform credential helper. It was not ported from any of the previous credential helper solutions that existed for Windows, MacOS, and Linux.

GCM uses "helper applications" for UI components, of which `GitHub.UI` is one. I tacked `.exe` onto the name mistakenly - I suppose I'm used to diagnosing/fixing issues for Windows users. However, on MacOS we ship it correctly as `GitHub.UI`. You can verify this by running the following locally:

`dotnet build --configuration=MacRelease`
`cd <REPO_ROOT_PATH>/out/osx/Installer.Mac/pkg/Release/payload`

All the files published for MacOS, including `GitHub.UI` are in that directory.

> 4. Please see above.
> 
> Thanks.
> 
> Regards, Ian

**Comment by ldennington** [comment]
I have downloaded multiple Swift projects and left them open on my machine (running macOS 12.2.1) in AppCode while I was away in an attempt to repro this issue and have not been able to do so. My guess is that it's because I'm missing this component of your setup:

_a large number (around 30-40) dependencies managed by CocoaPods and integrated as development pods with paths to the local repos on my machine._

I am unfamiliar with CocoaPods and will need to do a bit of ramping to duplicate your scenario more effectively.

I have also reviewed your JetBrains ticket and believe memory exhaustion due to JetBrains using fork() to create git child processes during background fetch is a good hypothesis for the root cause here. I'm hoping they follow up with some answers to your questions to shed some light on whether this truly is a `git-credential-manager-core` or an AppCode issue. In the meantime, I will continue to try for a repro of your problem on my machine.

**Comment by vtbassmatt** [comment]
[I left a comment](https://youtrack.jetbrains.com/issue/IDEA-289782#focus=Comments-27-5948110.0-0) on the JetBrains bug tracker, which I'll replicate here:

> Hey folks. I'm the product manager at GitHub responsible for (our contributions to) the Git Credential Manager. This bug is most perplexing to me. It's entirely possible that GCM leaks memory somewhere. It's managed code, so we're not in the business of malloc/free-style memory management, but we could still be holding onto some resource somewhere...
>
> ...but none of that should matter. The contract between Git and a credential manager is that Git shells out to the credential manager, sends a few words to its stdin, listens for a few words on stdout, and then the credential manager terminates. There's nothing fancy or long-running. Really, that's the model for Git itself – short-lived commands which always terminate after a single logical operation.
>
> We'll continue hunting for what might be causing a leak in GCM itself. Could JetBrains dig into the architecture for how you're calling Git? Our mutual customer should be coming back from a weekend to find _any_ long-lived Git/GCM processes (let alone ones which have ballooned to dozens of GB of memory). Thanks, and if you want to discuss further, please feel free to reach me at `vtbassmatt` at my employer's domain name :)

**Comment by derrickstolee** [comment]
> Our mutual customer should _not_ be coming back from a weekend...

(add the _not_?)

**Comment by ianhlavats** [comment]
Hi @vtbassmatt and team, thanks a lot for looking into this issue and reaching out to JetBrains. 

I have another theory on what caused it. I adjusted my anti-virus software to exclude some paths and I haven't seen the problem happen in the last week or so.

I think we can close this bug ticket.
