### ISSUE TITLE
Bad GCM/Git configuration

### ISSUE THREAD

**Issue by MarianaLagrava** [GitCredentialManager/git-credential-manager#628]
**Which version of GCM are you using?**

From a terminal, run `git credential-manager-core --version` and paste the output.

Git Credential Manager version 2.0.394-beta+3fc6791abf

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [x] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

From a terminal, run `git remote -v` to see your remote URL.

origin  https://github.com/MarianaLagrava/complete-guide-to-ASP-NETCore.git

* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

as i paste the token when the password is asked in the authentication process, it throws a error as if i try to authenticate with my password.
![image](https://user-images.githubusercontent.com/62715312/156035464-1116411e-d4df-4141-8217-0675f8dbf83a.png)

**Comment by hickford** [comment]
Try `git config —list’. Does anything look amiss?

**Comment by mjcheetham** [comment]
It looks like you're using Git for Windows, which includes GCM by default. You should not need to run the GCM `configure` command to get started.

From the errors you are getting, your Git config has probably got itself in a bad state.

As @hickford said, please try running `git config --list --show-origin` and check the results, specifically and values under the `[credential]` section(s).

**Comment by mjcheetham** [comment]
@MarianaLagrava I notice it looks like you're using an older version of Git for Windows (and GCM). Please can you first try updating to the latest Git for Windows: <https://git-scm.com/download/win>?

Once you've done this can you please run the following command to clean up some bad configuration that was set:

```batch
git config --global --unset-all credential.helper
```

**Comment by MrDavidIam** [comment]
How to terminate a configuration to stop screen mirroring and key strokes

**Comment by MarianaLagrava** [comment]
Done! thnak you for your help!
