### ISSUE TITLE
Unable to Persist Credentials and Not Getting Prompted for Auth

### ISSUE THREAD

**Issue by gbrac** [GitCredentialManager/git-credential-manager#633]
When pushing or pulling to Azure DevOps git repo, I do not get prompted for credentials and it fails.  Running git-credential-manager-core diagnose, I get: System.Exception: Unable to persist credentials with the 'wincredman' credential store.

 OK ] Environment
 [ OK ] File system
 [ OK ] Networking
 [ OK ] Git
 [FAIL] Credential storage

    [!] Encountered an exception [!]
    System.Exception: Unable to persist credentials with the 'wincredman' credential store.

    See https://aka.ms/gcm/credstores for more information.

       at GitCredentialManager.CredentialStore.ValidateWindowsCredentialManager()

       at GitCredentialManager.CredentialStore.EnsureBackingStore()

       at GitCredentialManager.CredentialStore.Remove(String service, String account)

       at GitCredentialManager.Diagnostics.CredentialStoreDiagnostic.RunInternalAsync(StringBuilder log, IList`1 additionalFiles)

       at GitCredentialManager.Diagnostics.Diagnostic.<RunAsync>d__5.MoveNext()

    [*] Diagnostic test log [*]
    ICredentialStore instance is of type: CredentialStore

    Writing test credential...Deleting test credential...

 [ OK ] Microsoft authentication (AAD/MSA)
 [ OK ] GitHub API

Diagnostic summary: 6 passed, 0 skipped, 1 failed.

**Comment by Elsewhere42** [comment]
I'm experiencing something similar with 2.35.1.Windows.2

I downgraded to 2.35.0.Windows.1 and that fixed the issue.
https://github.com/git-for-windows/git/releases/tag/v2.35.0.windows.1

I suspect there is a critical bug in 2.35.1.Windows.2.

```
Opening repositories:
C:\Users\[username]\Source\Repos\[myRepoName]
Pushing develop
git: 'credential-manager' is not a git command. See 'git --help'.

The most similar command is
	credential-manager-core
Error encountered while pushing to the remote repository: Git failed with a fatal error.
Git failed with a fatal error.
Unable to persist credentials with the 'wincredman' credential store.
See https://aka.ms/gcm/credstores for more information.
cannot spawn askpass: No such file or directory
could not read Password for 'https://my.git.repository.url': terminal prompts disabled

Failed to push to the remote repository. See the Output window for more details. 
```

**Comment by gbrac** [comment]
Thanks. I tried downgrading to this version, but the issue remains for me.

**Comment by Elsewhere42** [comment]
Well... mine is not working again.  Now with a new error:

```
Cloning into 'C:\Users\[username]\Source\Repos\MyRepoName'...
Error encountered while cloning the remote repository: Git failed with a fatal error.
Unable to persist credentials with the 'wincredman' credential store.
See https://aka.ms/gcm/credstores for more information.
Unable to persist credentials with the 'wincredman' credential store.
See https://aka.ms/gcm/credstores for more information.
Unable to persist credentials with the 'wincredman' credential store.
See https://aka.ms/gcm/credstores for more information.
cannot spawn askpass: No such file or directory
could not read Password for 'https://orgName@dev.azure.com/MyGitPath': terminal prompts disabled
```

This is killing me.  I'm dead in the water.  Git is 100% unusable.

**Comment by ldennington** [comment]
@gbrac @Elsewhere42 - Are you SSH'ing into your Windows machines by chance?

**Comment by gbrac** [comment]
No, I am not.

**Comment by Elsewhere42** [comment]
@ldennington  Thanks for the tip about the log file.   Over several days I spent many hours searching for a logging command but never found one.  That was exactly what I needed.

`git-credential-manager-core diagnose`

It looks like a Proxy Authentication error.  Is there any information available about how to setup Proxy Authentication on Git?

```
------------
Diagnostic: GitHub API
Skipped: False
Success: False
Exception:
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.GitHubRestApi.<GetMetaInfoAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.Diagnostics.GitHubApiDiagnostic.<RunInternalAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitCredentialManager.Diagnostics.Diagnostic.<RunAsync>d__5.MoveNext()
```

**Comment by ldennington** [comment]
Would you mind trying the steps outlined [here](https://github.com/GitCredentialManager/git-credential-manager/blob/ff080376301a46fba310d66965b321bf77ede70e/docs/netconfig.md#authenticated-proxies)?

**Comment by gbrac** [comment]
This is the only error or exception I have in that log. Everything else reports OK:

------------
Diagnostic: Credential storage
Skipped: False
Success: False
Exception:
System.Exception: Unable to persist credentials with the 'wincredman' credential store.
See https://aka.ms/gcm/credstores for more information.
   at GitCredentialManager.CredentialStore.ValidateWindowsCredentialManager()
   at GitCredentialManager.CredentialStore.EnsureBackingStore()
   at GitCredentialManager.CredentialStore.Remove(String service, String account)
   at GitCredentialManager.Diagnostics.CredentialStoreDiagnostic.RunInternalAsync(StringBuilder log, IList`1 additionalFiles)
   at GitCredentialManager.Diagnostics.Diagnostic.<RunAsync>d__5.MoveNext()
Log:
ICredentialStore instance is of type: CredentialStore
Writing test credential...Deleting test credential...
------------

**Comment by ldennington** [comment]
@gbrac - apologies! I edited my above comment. Would you mind following the new instructions and sending along those logs?

**Comment by ldennington** [comment]
> @ldennington Thanks for the tip about the log file. Over several days I spent many hours searching for a logging command but never found one. That was exactly what I needed.
> 
> `git-credential-manager-core diagnose`
> 
> It looks like a Proxy Authentication error. Is there any information available about how to setup Proxy Authentication on Git?
> 
> ```
> ------------
> Diagnostic: GitHub API
> Skipped: False
> Success: False
> Exception:
> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
>    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>    at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
>    --- End of inner exception stack trace ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at GitHub.GitHubRestApi.<GetMetaInfoAsync>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at GitHub.Diagnostics.GitHubApiDiagnostic.<RunInternalAsync>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at GitCredentialManager.Diagnostics.Diagnostic.<RunAsync>d__5.MoveNext()
> ```

For future reference, you can find details on troubleshooting (including logging) [here](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/faq.md#authentication-problems).

**Comment by gbrac** [comment]
I attempted to do the git push from the command line (instead of from within Visual Studio Pro 2022), and it appears to work. So, the issue appears to involve Visual Studio and GCM.

**Comment by mjcheetham** [comment]
> [..] and that worked, other than it would ask for credentials every time (instead of caching them). It appears now that only GCM Core is available, however.

This will be the same underlying problem. GCM for Windows will have been prompting you each time because it was failing to persist credentials in the store. GCM (Core) is instead failing up-front because it has detected persistence is broken for some reason.

Please can you try changing the backing store that is being used to one that is more reliable?

```batch
git config --global credential.credentialStore dpapi
```

This will tell GCM to write credentials to encrypted files under `%USERPROFILE%\.gcm\dpapi_store` rather than use the Windows Credential Manager store (which is seemingly not working for you).

**Comment by realSAH** [comment]
> @gbrac @Elsewhere42 - Are you SSH'ing into your Windows machines by chance?

Yes, I am SSHing to a windows machine. Everything works seamlessly when I RDP to the remote. But when I SSH, it says unable to presiste credentials.

Could you please let us know how to solve it in SSH case?

**Comment by realSAH** [comment]
After a little bit of **reading**, it turns out that docs explicitly warn that wincredsman codesn't work for SSH and advise for a different one instead.

https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/credstores.md

**Comment by Gmanunta81GFPS** [comment]
> > [..] and that worked, other than it would ask for credentials every time (instead of caching them). It appears now that only GCM Core is available, however.
> 
> This will be the same underlying problem. GCM for Windows will have been prompting you each time because it was failing to persist credentials in the store. GCM (Core) is instead failing up-front because it has detected persistence is broken for some reason.
> 
> Please can you try changing the backing store that is being used to one that is more reliable?
> 
> ```batchfile
> git config --global credential.credentialStore dpapi
> ```
> 
> This will tell GCM to write credentials to encrypted files under `%USERPROFILE%\.gcm\dpapi_store` rather than use the Windows Credential Manager store (which is seemingly not working for you).

it fixed my issue that it "Unable to persist credentials with the 'wincredman' credential store."

**Comment by DanWaheed** [comment]
> > > [..] and that worked, other than it would ask for credentials every time (instead of caching them). It appears now that only GCM Core is available, however.
> > 
> > 
> > This will be the same underlying problem. GCM for Windows will have been prompting you each time because it was failing to persist credentials in the store. GCM (Core) is instead failing up-front because it has detected persistence is broken for some reason.
> > Please can you try changing the backing store that is being used to one that is more reliable?
> > ```batchfile
> > git config --global credential.credentialStore dpapi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will tell GCM to write credentials to encrypted files under `%USERPROFILE%\.gcm\dpapi_store` rather than use the Windows Credential Manager store (which is seemingly not working for you).
> 
> it fixed my issue that it "Unable to persist credentials with the 'wincredman' credential store."

I had this same issue and this resolved my issue as well

**Comment by Gahona47** [comment]
> credential.credentialStore
