### ISSUE TITLE
No usable version of libssl was found when trying to configure

### ISSUE THREAD

**Issue by Palsternakka** [GitCredentialManager/git-credential-manager#662]
Tried to install GCM as per the instructions [here](https://github.com/GitCredentialManager/git-credential-manager#ubuntudebian-distributions)

```bash
sudo dpkg -i Downloads/gcmcore-linux_amd64.2.0.632.34631.deb
git-credential-manager-core configure
```
Upon running the second command, I get 

```bash
No usable version of libssl was found
Aborted (core dumped)
```

I am running Xubuntu 22.04, here's the output of `openssl version -a`

```bash
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
built on: Wed Mar 16 08:35:51 2022 UTC
platform: debian-amd64
options:  bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -ffile-prefix-map=/build/openssl-oDFw7Q/openssl-3.0.2=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_TLS_SECURITY_LEVEL=2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-3"
MODULESDIR: "/usr/lib/x86_64-linux-gnu/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_ia32cap=0x7ed8320b078bffff:0x40069c219c97a9

```

**Comment by ldennington** [comment]
This is a bit tricky, as XUbuntu isn't technically a distro GCM supports. My suggestion would be to try something like [these instructions](https://fedingo.com/how-to-install-openssl-in-ubuntu/) to install OpenSSL (which `libssl` is a part of) manually.

**Comment by ldennington** [comment]
Pardon me - I completely overlooked the fact that you have OpenSSL installed already. That's my bad. It might be worthwhile to take a look at the dotnet dependencies for different Ubuntu versions. Based on [this](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#dependencies), it looks like you may have to install OpenSSL/`libssl` 1.1.

**Comment by Palsternakka** [comment]
From what I can see, it's not (easily) possible to install two versions of OpenSSL and I'm not yet familiar enough with Linux to attempt to do so - are there any plans for OpenSSL 3 support?

**Comment by ldennington** [comment]
You'll probably want to open an issue in the [dotnet repo](https://github.com/microsoft/dotnet), since this OpenSSL dependency is theirs, not GCM's.
