### ISSUE TITLE
[GitLab] Token provided by GCM for gitlab.com does not work for Source Link request.

### ISSUE THREAD

**Issue by chuckries** [GitCredentialManager/git-credential-manager#669]
GCM for GitLab uses the `repository_write` scope for its tokens. This provides read/write access for Git over HTTP operations but does not provide repository read operations via the GitLab API. This means that GCM does not provide tokens that can be used to authenticate Source Link requests.

This isn't a bug, per se, as GCM is using the correct scope for pure git.exe operations. This is its intended purpose. It is, however, a missed opportunity. Visual Studio leverages GCM to authenticate Source Link requests, and expanding the scope used could allow Visual Studio to use Source Link for private gitlab.com repos, which has been a gap for several releases. 

A more in depth write up can be found here: https://github.com/dotnet/sourcelink/issues/281#issuecomment-1100426378

I am hoping somebody from GCM or GitLab can speak to this. My testing of GCM token's against GitLab API requests makes me **believe** that the scope is the issue, but I'm not 100% sure.

Thanks!

**Comment by chuckries** [comment]
I was able to confirm that adding `repository_read` scope to the tokens provided by GCM allows the token to be used to authenticate the repository files api, which would make the tokens usable by Source Link.

**Comment by ldennington** [comment]
Assigning to @hickford for comment.

**Comment by hickford** [comment]
I'm not familiar with Source Link, but as a user I wouldn't.

As a user, I wouldn't .

I defer to others.

https://docs.gitlab.com/ee/integration/oauth_provider.html#authorized-applications

> Scope | Description
> -- | --
> read_repository | Grants read-only access to repositories on private projects using Git-over-HTTP or the Repository Files API.
> write_repository | Grants read-write access to repositories on private projects using Git-over-HTTP (not using the API).

**Comment by Bene81** [comment]
According to my researches regarding using sourcelink to gitlab from VS debugger following issues persist:

- VS Debugger requires plain text/source files, thus the raw file URL
- repository files API returns JSON, in my case with base64 encoded content, see [Repository Files API](https://docs.gitlab.com/ee/api/repository_files.html)
- repository files API refers to commits using the `ref` query parameter
- PDB sourcelink is refering to repository root, as seen [here](https://github.com/dotnet/sourcelink/blob/00accce73f32b91a59d3be28c1f6993c3cd4df3e/src/SourceLink.GitLab/GetSourceLinkUrl.cs#L28) or any resulting PDB, the relative file paths are then appended.
  - I don't see adding query parameters will do the trick
  - as far as I read *somewhere* VS debugger has some issues with query parameters (correct me please, if I am wrong)
- repository files API requires a PRIVATE_TOKEN or ACCESS_TOKEN. A BEARER Token as provided by the OAuth API is not sufficient.
  - at least not according to my API tests -> results in `401 Unauthorized`

At this point of my research I think what needs to be done to allow sourcelink working with gitlab would be to allow OAuth application an access right to `read_raw_files`.
This access right would still need to be invented and implemented over at gitlab.org.

Best way to get sourcelink debugging nowadays seems to be the workarounds with

- GitLabProxy
- Authentication from within VS integrated web browser

**Comment by ldennington** [comment]
We're going to plan to add the `read_repository` scope to tokens, as it's a subset of permissions granted by `write_repository` anyway. Hopefully this will unblock the described Source Link scenarios.

**Comment by chuckries** [comment]
@ldennington thanks for the info. from what I recall from looking at this, the issue for source link is that the `write_reposository` scope for OAuth tokens provides read-write access only for Git-over-HTTP (essentially git.exe operations) while `read_respository` scope provides read access for both Git-over-HTTP **as well as** the Repository Files API.

The read access to the Repository Files API is what would be needed for Source Link. If you are saying that [this line](https://github.com/GitCredentialManager/git-credential-manager/blob/f5bd57908b17e7772dde33d84c3a2634fb9d4768/src/shared/GitLab/GitLabHostProvider.cs#L15) will be amended to include both scopes in tokens obtained through GCM, then I believe this should work for source link.

**Comment by chuckries** [comment]
@Bene81 you are correct that adjusting the scope is not the only fix required for Source Link to work with private gitlab.com repos, but it is a necessary piece. It is also the piece that I can't change; I can make the necessary changes in VS Source Link.

1. A while back I cloned the GCM repo and changed the necessary application id's locally which allowed me to register it as my own application with my own GitLab account. This in turn allowed me to adjust the scope of the tokens, which allowed me to test the addition of `read_repository` 
2. With this token, I tested the Repository Files API for [getting a raw file](https://docs.gitlab.com/ee/api/repository_files.html#get-raw-file-from-repository). This I believe returns a flat text file that Source Link expects, not a json blob. 

Once the correct authentication is available, I intend to:
1. Get the [dotnet/sourcelink GitLab package](https://github.com/dotnet/sourcelink/tree/main/src/SourceLink.GitLab) to change to api based URL's as opposed to the current web based URL's.
2. Add a mechanism in VS to map the old URL's into the API url's, as you suggest. According to the docs, the "id" field of the url can be a string or an id, which should allow us to use the pieces from the existing URL.

**Comment by Bene81** [comment]
@chuckries
Sounds good. Altogether it really might work.
I recall though that I had issues with just the project names in the API calls. But maybe I tricked myself there. I will need to retry this at some point. I'll keep you posted then.
I am really looking forward to sourcelink being able to deal with gitlab.

**Comment by ldennington** [comment]
@chuckries I'm unable to mention you in the PR for some reason, but wanted to give you a heads up that [it is open](https://github.com/GitCredentialManager/git-credential-manager/pull/719)!
