### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by denis-rossati** [GitCredentialManager/git-credential-manager#675]
It's not a feature but I didn't find any other tag that matches this textual fix.

After I install GCM, [the docs](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/usage.md) declares that I can run a command like `git credential-manager-core [any-command]`, but it doesn't work for me. Instead, `git-credential-manager-core [any-command]` works (with hyphen between "git" and "credential").

I would like to make sure that this isn't a typo in the documentation or I just missed some step in the installation.

Thanks for the atention in advance :)

**Comment by ldennington** [comment]
Hi @denis-rossati! Would you mind sharing the OS you're working on and the output from `git-credential-manager-core --version`? I've run several commands (`diagnose`, `unconfigure`, and `configure`) using `git credential-manager-core` and they've worked as expected on macOS with version `2.0.696+4365b917da`.

**Comment by denis-rossati** [comment]
Sure!
Ubuntu: 20.04.4
Git: 2.25.1

running `git-credential-manager-core --version` displays "2.0.696+4365b917da"

**Comment by denis-rossati** [comment]
Actually the typo was in the command I've runned. Instead of `git credential-manager-core [any-command]` I typed `git credential-manager [any-command]`

Please, apologize me for the inconvenience 🙇

**Comment by ldennington** [comment]
Thanks for letting us know!
