### ISSUE TITLE
Support popular GitLab instances out the box

### ISSUE THREAD

**Issue by hickford** [GitCredentialManager/git-credential-manager#677]
GCM supports gitlab.com out the box. Other GitLab instances require [special setup](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/gitlab.md), including creating an OAuth application (typically something done by OAuth application developers rather than users). More user friendly would be to ship with support for popular GitLab instances.

[Previous discussion](https://github.com/GitCredentialManager/git-credential-manager/pull/591#pullrequestreview-846527667) raised reasoned concerns about fairness and maintenance burden:

> we should not hardcode public instances outside of the host-maintained offering (gitlab.com, github.com, etc). Doing so opens the project and maintainers up to a lot of risk and burden. Instances come and go over time. Some may construe support of some instances as being an endorsement of that entity. The **potentially unbounded number of requests** to add a new instance is not scalable. It's not fair to decide to take some instances over others.

Good points. Indeed, a quick [web search](https://www.google.com/search?q=%22Discover+projects%2C+groups+and+snippets.+Share+your+projects+with+others%22) reveals dozens of small academic GitLab instances.

In the ["ethos of GCM as an open, universal and agnostic project"](https://github.blog/2022-04-07-git-credential-manager-authentication-for-everyone/), I tried to come up with narrow but fair criteria for including other instances that would help the most users but minimise maintenance burden:

1. (maturity) associated with an established open-source project of five or more years
2. (scale) has a repo with at least 100 stars
3. (community) has an compatible inclusive code of conduct
4. (open) anyone can create an account (necessary for GCM team to create OAuth application)

These would be satisfied by only a handful of popular GitLab instances, all associated with 'household name' open-source projects of good reputation:

* https://salsa.debian.org/public Debian Linux distribution
* https://gitlab.gnome.org/explore GNOME desktop environment
* https://gitlab.haskell.org/explore Haskell functional programming language
* https://code.videolan.org/ VLC media player
* https://gitlab.freedesktop.org/explore Freedesktop project including X11 and Wayland

How does that sound? That would help thousands of open source developers with minimal maintenance burden (approx 5 minutes per instance to create OAuth application).

* * *

Workaround: If it helps anyone else in the meantime, here is unofficial config for the above instances.

```
git config --global credential.https://gitlab.freedesktop.org.gitlabdevclientid 6503d8c5a27187628440d44e0352833a2b49bce540c546c22a3378c8f5b74d45
git config --global credential.https://gitlab.freedesktop.org.gitlabdevclientsecret 2ae9343a034ff1baadaef1e7ce3197776b00746a02ddf0323bb34aca8bff6dc1
git config --global credential.https://gitlab.gnome.org.gitlabdevclientid adf21361d32eddc87bf6baf8366f242dfe07a7d4335b46e8e101303364ccc470
git config --global credential.https://gitlab.gnome.org.gitlabdevclientsecret cdca4678f64e5b0be9febc0d5e7aab0d81d27696d7adb1cf8022ccefd0a58fc0
git config --global credential.https://salsa.debian.org.gitlabdevclientid 213f5fd32c6a14a0328048c0a77cc12c19138cc165ab957fb83d0add74656f89
git config --global credential.https://salsa.debian.org.gitlabdevclientsecret 3616b974b59451ecf553f951cb7b8e6e3c91c6d84dd3247dcb0183dac93c2a26
git config --global credential.https://gitlab.haskell.org.gitlabdevclientid 57de5eaab72b3dc447fca8c19cea39527a08e82da5377c2d10a8ebb30b08fa5f
git config --global credential.https://gitlab.haskell.org.gitlabdevclientsecret 5170a480da8fb7341e0daac94223d4fff549c702efb2f8873d950bb2b88e434f
git config --global credential.https://code.videolan.org.gitlabdevclientid f35c379241cc20bf9dffecb47990491b62757db4fb96080cddf2461eacb40375
git config --global credential.https://code.videolan.org.gitlabdevclientsecret 631558ec973c5ef65b78db9f41103f8247dc68d979c86f051c0fe4389e1995e8
```

**Comment by abisai1** [comment]
#667.

**Comment by ldennington** [comment]
The docs at [this link](https://aka.ms/gcm/gitlab) contain a popular set of instances. We may consider adding other instances to this documentation in the future, but do not plan to put them into the GCM codebase.
