### ISSUE TITLE
GCM not working with `git send-email` or `git imap-send`. 

### ISSUE THREAD

**Issue by PhilipOakley** [GitCredentialManager/git-credential-manager#683]
GCM should include being a documented, valid, credential helper for the `git send-email` and `git imap-send` git commands to allow the safe sending of patches and emails to the git and Linux lists (etc.) for patch submission.

The git list has [indicated](https://lore.kernel.org/git/2f8567f7-6d9c-e79b-9a05-7dd55cb40224@iee.email/) that GCM isn't integrated as a helper to those commands for providing the essential plain text emails needed by the list.

It maybe that 'I'm holding it wrong' and all that is needed is some GCM documentation to show how to set up the user `.gitconfig`, and how to add the needed email host 'username/password' to GCM to make it work. 

Hosting providers don't see GCM/send-email as their problem and provided zero support (though do have port/auth details for Outlook, Thunderbird, etc). Having distinct credentials per port (#608) could be a benefit. 

Adding commentary about port 465 confusions could also help (e.g. [1](https://www.pepipost.com/blog/smtp-port-465/), [2](https://sendgrid.com/blog/whats-the-difference-between-ports-465-and-587/),)

Hoping someone can shed some light and information on how to make GCM useful in this scenario.

**Feature description**
Integrate with `git send-email` or `git imap-send`. 
Document the `git send-email` or `git imap-send` setups.

**Comment by ldennington** [comment]
This is not something we plan to support in GCM. However, we should exhibit better behavior for protocols we don't support.

**Comment by PhilipOakley** [comment]
Maybe an initial easy step is to add a documentation comment on the GCM page that notes that despite it being a **Git** credential manager it isn't currently supporting the `send-email` or `imap-send` commands' use of credentials, and that it's currently a low priority (but PRs welcome) etc.

Separately, where would I look in the code to maybe see how the two (`git send-email`'s credential request and GCM's protocol/address response determination) meet in the middle? I'm unfamiliar with the code layout.

**Comment by mjcheetham** [comment]
In investigating how to better handle these non-HTTP(S) credential requests, I realised it was actually just an artificial limitation being imposed and it would be trivial to support any protocol in the simple cases.
The fix merged in #712 should enable GCM to work with `send-email` and `imap-send`, and will be included in the next release of GCM.

**Comment by PhilipOakley** [comment]
> should enable GCM to work with `send-email` and `imap-send`,

Sounds good. 
Will there be a documentation update somewhere to help folks with their setups?
