### ISSUE TITLE
Neutral (Atlassian-term free) dialog when connecting to Bitbucket on prem

### ISSUE THREAD

**Issue by jh-cd** [GitCredentialManager/git-credential-manager#684]
**Feature description**

In PR #116 a dialog has been introduced showing sections a) a title "Atlassian", b) User/Password inputs, c) "Can't log in", d) "Sign up for an account".
This dialog is shown logging in to local/internal Bitbucket on prem. The title "Atlassian" as well as the link "Can't log in" (links to bitbucket.org) and the link "Sign up for an account" (links to atlassian.com) are misleading. Develops fear their internal credentials would be sent to Atlassian.

We're using Bitbucket on prem and it would be helpful to have a neutral login-screen without any Atlassian-related term or link as it was using wincred (if memory serves me right), because our developers have nothing to do with the company Atlassian nor with Bitbucket Cloud.

Is there any switch to achieve this?

I know there is the .gitconfig property `interactive = false` in the `[credential]` section suppressing the "Atlassian" dialog. But this results again in a misleading behavour: Despite the login-dialogs for Username and Password pops up, there is the command line message `fatal: Cannot prompt because user interactivity has been disabled.`. I think the result is on purpose, it is not fatal nor an error at all.

I also tried to set the provider to `generic`, but the "Atlassisn"-dialog still popped up, and the setting in .gitconfig has been rewritten to `bitbucket`.

Setting `guiPrompt = false` also lets pop up the "Atlassian"-dialog.

**Comment by mjcheetham** [comment]
In #713 we've updated the links in the GUI prompts to point to an instance-specific location for sign-in and password reset, and will now show the instance URL to make it clear what you are authenticating against.

![image](https://user-images.githubusercontent.com/5658207/171137465-2784a124-33a3-4199-b69b-e0c94af107ee.png)
