### ISSUE TITLE
Better support for GitHub Enterprise Managed Users

### ISSUE THREAD

**Issue by markphip** [GitCredentialManager/git-credential-manager#688]
**Which version of GCM are you using?**

2.0.605+97323d1677

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [X] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

* [ ] Yes
* [X] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [X] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [X] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

When cloning a repository from a GHEC repository, I am prompted to login to GitHub using my EMU account

**Actual behavior**

GCM used my cached github.com credentials to successfully authenticate with GitHub, but this user is not an Enterprise Managed User so it cannot access the repository

I do not know how you can detect this situation but it seems like it would be super common and without a solution the only option would appear to be to only use https for one account and SSH for the other.

**Comment by ldennington** [comment]
Thanks for raising the issue! This is being tracked on our backlog [#718](https://github.com/github/git-fundamentals/issues/718). We'll have more to share in this area soon!

**Comment by ryanspletzer** [comment]
Hi @ldennington was there more progress made on this front? GCM has been wonderful for github.com and GitHub Enterprise Server, wondering if it could accommodate the new EMU setup. I tried to follow your linked issue but it seems to lead to an internal / private GitHub org / repo: https://github.com/github/git-fundamentals/issues/718

**Comment by ldennington** [comment]
Hi @ryanspletzer - sorry about the link to the internal issue. That was a mistake, and I have removed it. The TLDR is that, while @mjcheetham was able to complete the [changes in core Git](https://lore.kernel.org/git/pull.1352.v11.git.1677518420.gitgitgadget@gmail.com/) that enable this work, we are facing some blockers outside the scope of our control that are preventing us from completing the work on the GCM side. We will provide an update as soon as we have more information available.
