### ISSUE TITLE
GCM fails to install and run: .NET Framework 4.7.2 required

### ISSUE THREAD

**Issue by CSharperMantle** [GitCredentialManager/git-credential-manager#690]
Promoting [#540#issuecomment-1119112791](https://github.com/GitCredentialManager/git-credential-manager/issues/540#issuecomment-1119112791) to a new issue.

> Installation failed due to a lack of .NET Framework 4.7.2.
> 
> I have a working .NET 5 SDK & Runtime installed since I routinely do some devs on .NET 5, so I guess that's not the issue. The problem is, *why does GCM say it is built on .NET but it still depends on .NET Framework?*
> 
> Upgrading Windows is not an option for me because of the hardware constraints.

**Which version of GCM are you using?**

N/A (GCM fails to install. Installer name: `gcmcore-win-x86-2.0.696`)

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [x] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Expected behavior**

GCM runs.

**Actual behavior**

GCM fails to run. 

![broken installation](https://user-images.githubusercontent.com/32665105/167039507-2c9268a1-fa32-41fe-9ea9-753625db94dd.png)

**System information**

* Windows 10 1511, OS Version 10586.1176
* Installed .NET runtimes:
  * .NET Framework 4.6.2 (Full SDK)
  * .NET SDK 5.0.301
  * .NET Core SDK 2.1.523
  * .NET Desktop Runtime - 6.0.4

**Comment by ldennington** [comment]
This is a bogus version of #540.
