### ISSUE TITLE
Git for Windows 2.36.1 breaks WSL setup steps

### ISSUE THREAD

**Issue by asasine** [GitCredentialManager/git-credential-manager#692]
[Git for Windows 2.36.1](https://github.com/git-for-windows/git/releases/tag/v2.36.1.windows.1) moves the git-credential-manager-core executable to a new path, breaking the [WSL configuration steps](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/wsl.md) in this repo. The new command should be:

```bash
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe"
```

This applies for Git for Windows 2.36.1 or newer.

Relevant PR: https://github.com/git-for-windows/build-extra/pull/406

**Comment by ldennington** [comment]
@asasine - thanks for raising this up! I've created #693 with the fix.
