### ISSUE TITLE
My commit is attributed to a person that is not me!

### ISSUE THREAD

**Issue by gaazkam** [GitCredentialManager/git-credential-manager#695]
**Which version of GCM are you using?**

Version: 2.0.696.25923
Runtime: .NET 6.0.3
Platform: Linux (x86-64)
OSVersion: Linux m-VirtualBox 5.13.0-41-generic #46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [x] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [x] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [x] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

My commits are attributed to me (https://github.com/gaazkam)

**Actual behavior**

My commits are attributed to https://github.com/ForestPCT

See the history of commits to https://github.com/gaazkam/mon and in particular https://github.com/gaazkam/mon/commit/8b420de0c9066348edb2b2b3eec20ce161f17133 and https://github.com/gaazkam/mon/commit/8f540aa69f8c8564815dd726877c36c5719499f2 and https://github.com/gaazkam/mon/commit/8820c6a48b01bb7f5fb35dfd58435d9543a8eafa

I hit this issue when I was testing to report #694

I am ***NOT*** ForestPCT, I have never met them, I have never had any contact with them, I have ZERO idea how possible my test commits started being attributed to them!!

Not sure where I should report this; I chose to submit an issue to this repo because it seems that this only happens when I try to use GCM.

When I extracted the password from the login keyring (`gho_REDACTED` - the token automatically assigned to me, not my github.com password) and tried to push a commit without using GCM, but by manually entering the login (gaazkam) and password (the aforementioned token) to git then the commit got correctly attributed to me: https://github.com/gaazkam/mon/commit/68cf4dcf1170bba49850592855df7c5545346a5f

If this is an incorrect place to report this then I'm sorry, please direct me to a better place.

I will open a ticket to github support as well.

**Logs**

As you can see from logs the user name is gaazkam NOT ForestPCT!

Logs from pushing a commit incorrectly attributed to ForestPCT:

```
m@m-VirtualBox:~/mon$ git push
11:00:27.347646 git.c:439               trace: built-in: git push
11:00:27.347926 run-command.c:663       trace: run_command: GIT_DIR=.git git-remote-https origin https://github.com/gaazkam/mon.git
11:00:27.951621 run-command.c:663       trace: run_command: '/usr/local/share/gcm-core/git-credential-manager-core get'
11:00:28.236413 ...re/Application.cs:95 trace: [RunInternalAsync] Version: 2.0.696.25923
11:00:28.239809 ...re/Application.cs:96 trace: [RunInternalAsync] Runtime: .NET 6.0.3
11:00:28.239950 ...re/Application.cs:97 trace: [RunInternalAsync] Platform: Linux (x86-64)
11:00:28.239970 ...re/Application.cs:98 trace: [RunInternalAsync] OSVersion: Linux m-VirtualBox 5.13.0-41-generic #46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
11:00:28.240148 ...re/Application.cs:99 trace: [RunInternalAsync] AppPath: /usr/local/share/gcm-core/git-credential-manager-core
11:00:28.240225 ...e/Application.cs:100 trace: [RunInternalAsync] Arguments: get
11:00:28.380267 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'get' command...
11:00:28.412826 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
11:00:28.417649 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	protocol=https
11:00:28.417802 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	host=github.com
11:00:28.521706 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
11:00:28.531801 ...viderRegistry.cs:158 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
11:00:28.535791 ...viderRegistry.cs:166 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.
11:00:28.538883 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
11:00:28.544710 .../HostProvider.cs:126 trace: [GetCredentialAsync] Looking for existing credential in store with service=https://github.com account=...
11:00:28.654594 .../HostProvider.cs:140 trace: [GetCredentialAsync] Existing credential found.
11:00:28.656403 ...GitCommandBase.cs:54 trace: [ExecuteAsync] End 'get' command...
11:00:28.974176 run-command.c:663       trace: run_command: '/usr/local/share/gcm-core/git-credential-manager-core store'
11:00:29.219513 ...re/Application.cs:95 trace: [RunInternalAsync] Version: 2.0.696.25923
11:00:29.222622 ...re/Application.cs:96 trace: [RunInternalAsync] Runtime: .NET 6.0.3
11:00:29.222724 ...re/Application.cs:97 trace: [RunInternalAsync] Platform: Linux (x86-64)
11:00:29.222741 ...re/Application.cs:98 trace: [RunInternalAsync] OSVersion: Linux m-VirtualBox 5.13.0-41-generic #46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
11:00:29.222894 ...re/Application.cs:99 trace: [RunInternalAsync] AppPath: /usr/local/share/gcm-core/git-credential-manager-core
11:00:29.222968 ...e/Application.cs:100 trace: [RunInternalAsync] Arguments: store
11:00:29.375312 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'store' command...
11:00:29.404186 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
11:00:29.407350 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	protocol=https
11:00:29.407472 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	host=github.com
11:00:29.407522 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	username=gaazkam
11:00:29.407541 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	password=********
11:00:29.489581 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
11:00:29.497245 ...viderRegistry.cs:158 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
11:00:29.503690 ...viderRegistry.cs:166 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.
11:00:29.506578 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
11:00:29.508708 .../HostProvider.cs:160 trace: [StoreCredentialAsync] Storing credential with service=https://github.com account=gaazkam...
11:00:29.626891 .../HostProvider.cs:162 trace: [StoreCredentialAsync] Credential was successfully stored.
11:00:29.627028 ...GitCommandBase.cs:54 trace: [ExecuteAsync] End 'store' command...
11:00:29.646971 run-command.c:663       trace: run_command: git send-pack --stateless-rpc --helper-status --thin --progress https://github.com/gaazkam/mon.git/ --stdin
11:00:29.651237 git.c:439               trace: built-in: git send-pack --stateless-rpc --helper-status --thin --progress https://github.com/gaazkam/mon.git/ --stdin
11:00:29.652267 run-command.c:663       trace: run_command: git pack-objects --all-progress-implied --revs --stdout --thin --delta-base-offset --progress
11:00:29.655399 git.c:439               trace: built-in: git pack-objects --all-progress-implied --revs --stdout --thin --delta-base-offset --progress
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Writing objects: 100% (3/3), 286 bytes | 286.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To https://github.com/gaazkam/mon.git
   8f540aa..8820c6a  main -> main
```

**Comment by mjcheetham** [comment]
I'm glad you managed to work out what was going on there!

> I am still surprised, because the incorrect email still contains `gaazkam` and not `ForestPCT`, but whatever,.

This will probably be an example of subaddressing (sometimes known as "plus addressing") as per [RFC 5233](https://datatracker.ietf.org/doc/html/rfc5233). The TL;DR is that everything between the `+` and the `@` is just a tag and isn't used to make a unique mailbox address (your mail server may or may not support this - Gmail _does_ for example).

**Comment by gaazkam** [comment]
Wow, thanks for your education!
