### ISSUE TITLE
Instructions on removing Experimental install from source helper script

### ISSUE THREAD

**Issue by ReznicencuBogdan** [GitCredentialManager/git-credential-manager#696]
Readme file has a section called `Experimental: install from source helper script`. The install script generates/spreads files and directories such as `~/.dotnet/` , `/usr/local/share/gcm-core/`, `/usr/local/bin/git-credential-manager-core`.  

However there is no instruction regarding their removal. It is specified how to unconfigure using `git-credential-manager-core unconfigure` but no assurance that the manual removal of those files/directories won't break something. So, is it ok to manually remove them? Is there anything left behind?

**Comment by ldennington** [comment]
We currently do not have instructions for how to remove after installing from source. I will look into adding them this week.
