### ISSUE TITLE
fatal: unable to access 'https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/dev_courts_ie/': The requested URL returned error: 403

### ISSUE THREAD

**Issue by rekhajethani** [GitCredentialManager/git-credential-manager#697]
**Which version of GCM are you using?**
2.36.1
From a terminal, run `git credential-manager-core --version` and paste the output.
2.0.696+4365b917da

**Which Git host provider are you trying to connect to?**

AWS

**Can you access the remote repository directly in the browser using the remote URL?**
yes

From a terminal, run `git remote -v` to see your remote URL.
https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/dev_courts_ie

* [ ] No, I get a permission error

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

Cloning into 'dev_courts_ie'...
git: 'credential-manager' is not a git command. See 'git --help'.

The most similar command is
        credential-manager-core
aws codecommit credential-helper $@ get: aws: command not found
fatal: unable to access 'https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/dev_courts_ie/': The requested URL returned error: 403

**Logs**

Diagnose log at 2022-05-13T13:48:45Z

Executable: C:\Program Files\Git\mingw64\bin\git-credential-manager-core.exe
Version: 2.0.696+4365b917da

------------
Diagnostic: Environment
Skipped: False
Success: True
Exception: None
Log:
OSType: Windows
OSVersion: 10.0 (build 19042)
Reading environment variables... OK
 Variables:
HOMEPATH=\Users\rekha.jethani
DriverData=C:\Windows\System32\Drivers\DriverData
COMPUTERNAME=M5-L-1VC1KW2
UATDATA=C:\windows\CCM\UATData\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77
MSYSTEM=MINGW64
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
OneDrive=C:\Users\rekha.jethani\OneDrive - Accenture
ChocolateyLastPathUpdate=132359200275069578
__PSLockDownPolicy=0
ProgramFiles(x86)=C:\Program Files (x86)
CONFIG_SITE=C:/Program Files/Git/etc/config.site
LC_CTYPE=en_US.UTF-8
USERDOMAIN=DIR
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
ORIGINAL_TEMP=C:/Users/REKHA~1.JET/AppData/Local/Temp
USERNAME=rekha.jethani
MINGW_PREFIX=C:/Program Files/Git/mingw64
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
ACLOCAL_PATH=C:\Program Files\Git\mingw64\share\aclocal;C:\Program Files\Git\usr\share\aclocal
TEMP=C:\Users\REKHA~1.JET\AppData\Local\Temp
LOCALAPPDATA=C:\Users\rekha.jethani\AppData\Local
MANPATH=C:\Program Files\Git\mingw64\local\man;C:\Program Files\Git\mingw64\share\man;C:\Program Files\Git\usr\local\man;C:\Program Files\Git\usr\share\man;C:\Program Files\Git\usr\man;C:\Program Files\Git\share\man
TERM=xterm
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
MSYSTEM_CARCH=x86_64
PROGRAMFILES=C:\Program Files (x86)
ProgramData=C:\ProgramData
USERDNSDOMAIN=DIR.SVC.ACCENTURE.COM
TERM_PROGRAM_VERSION=3.6.1
ORIGINAL_TMP=C:/Users/REKHA~1.JET/AppData/Local/Temp
PROCESSOR_REVISION=8e0c
SYSTEMROOT=C:\WINDOWS
TERM_PROGRAM=mintty
PROCESSOR_LEVEL=6
NUMBER_OF_PROCESSORS=8
SSH_ASKPASS=C:/Program Files/Git/mingw64/bin/git-askpass.exe
SHLVL=1
APPDATA=C:\Users\rekha.jethani\AppData\Roaming
SYSTEMDRIVE=C:
PSModulePath=%ProgramFiles%\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft Azure Information Protection\Powershell
PUBLIC=C:\Users\Public
HOSTNAME=M5-L-1VC1KW2
PKG_CONFIG_PATH=C:\Program Files\Git\mingw64\lib\pkgconfig;C:\Program Files\Git\mingw64\share\pkgconfig
SYSDRIVE=%SYSTEMFOLDER%
MSYSTEM_CHOST=x86_64-w64-mingw32
WINDIR=C:\WINDOWS
PLINK_PROTOCOL=ssh
INFOPATH=C:\Program Files\Git\usr\local\info;C:\Program Files\Git\usr\share\info;C:\Program Files\Git\usr\info;C:\Program Files\Git\share\info
ProgramW6432=C:\Program Files
PATH=C:/Program Files/Git/mingw64/libexec/git-core;C:\Users\rekha.jethani\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\rekha.jethani\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python38\Scripts;C:\Python38;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\nodejs;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\DevDesktop\tools;C:\Program Files (x86)\DevDesktop\drush_10;C:\Program Files (x86)\Symantec\VIP Access Client;C:\Program Files (x86)\Pulse Secure\VC142.CRT\X64;C:\Program Files (x86)\Pulse Secure\VC142.CRT\X86;C:\Program Files (x86)\Common Files\Pulse Secure\VC142.CRT\X64;C:\Program Files (x86)\Common Files\Pulse Secure\VC142.CRT\X86;C:\Program Files\Git\cmd;C:\instantclient_12_1;C:\Users\rekha.jethani\AppData\Local\Microsoft\WindowsApps;C:\Users\rekha.jethani\AppData\Local\Programs\Microsoft VS Code\bin;C:\wamp64\bin\php\php5.6.40;C:\Users\rekha.jethani\AppData\Local\ComposerSetup\bin;C:\Users\rekha.jethani\AppData\Roaming\Composer\vendor\bin;C:\Users\rekha.jethani\AppData\Roaming\npm;C:\Program Files\Java\jdk1.8.0_202\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
ChocolateyInstall=C:\ProgramData\chocolatey
TMPDIR=C:\Users\REKHA~1.JET\AppData\Local\Temp
TMP=C:\Users\REKHA~1.JET\AppData\Local\Temp
drupal console=C:\wamp64\bin\php
SHELL=C:\Program Files\Git\usr\bin\bash.exe
HOME=C:\Users\rekha.jethani
COMSPEC=C:\WINDOWS\system32\cmd.exe
ZES_ENABLE_SYSMAN=1
LOGONSERVER=\\SGPDC3211
USERPROFILE=C:\Users\rekha.jethani
DISPLAY=needs-to-be-defined
COMMONPROGRAMFILES=C:\Program Files (x86)\Common Files
USERDOMAIN_ROAMINGPROFILE=DIR
CommonProgramW6432=C:\Program Files\Common Files
HOMEDRIVE=C:
MSYSTEM_PREFIX=C:/Program Files/Git/mingw64
OLDPWD=C:/
OneDriveCommercial=C:\Users\rekha.jethani\OneDrive - Accenture
MINGW_PACKAGE_PREFIX=mingw-w64-x86_64
PWD=C:/Courts-Clone_AWS
EXEPATH=C:\Program Files\Git
NEXTHINK=C:\Program Files\Nexthink\Collector
PROCESSOR_ARCHITEW6432=AMD64
ORIGINAL_PATH=C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\rekha.jethani\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python38\Scripts;C:\Python38;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\nodejs;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\DevDesktop\tools;C:\Program Files (x86)\DevDesktop\drush_10;C:\Program Files (x86)\Symantec\VIP Access Client;C:\Program Files (x86)\Pulse Secure\VC142.CRT\X64;C:\Program Files (x86)\Pulse Secure\VC142.CRT\X86;C:\Program Files (x86)\Common Files\Pulse Secure\VC142.CRT\X64;C:\Program Files (x86)\Common Files\Pulse Secure\VC142.CRT\X86;C:\Program Files\Git\cmd;C:\instantclient_12_1;C:\Users\rekha.jethani\AppData\Local\Microsoft\WindowsApps;C:\Users\rekha.jethani\AppData\Local\Programs\Microsoft VS Code\bin;C:\wamp64\bin\php\php5.6.40;C:\Users\rekha.jethani\AppData\Local\ComposerSetup\bin;C:\Users\rekha.jethani\AppData\Roaming\Composer\vendor\bin;C:\Users\rekha.jethani\AppData\Roaming\npm;C:\Program Files\Java\jdk1.8.0_202\bin
PROCESSOR_ARCHITECTURE=x86
PS1=\[\033]0;$TITLEPREFIX:$PWD\007\]\n\[\033[32m\]\u@\h \[\033[35m\]$MSYSTEM \[\033[33m\]\w\[\033[36m\]`__git_ps1`\[\033[0m\]\n$ 
OS=Windows_NT
MINGW_CHOST=x86_64-w64-mingw32
_=C:/Program Files/Git/mingw64/bin/git
ALLUSERSPROFILE=C:\ProgramData

------------
Diagnostic: File system
Skipped: False
Success: True
Exception: None
Log:
Temporary directory is 'C:\Users\rekha.jethani\AppData\Local\Temp\'...
Checking basic file I/O...
Writing to temporary file 'C:\Users\rekha.jethani\AppData\Local\Temp\a04c422f9f0eb30ee011fe38'... OK
Reading from temporary file 'C:\Users\rekha.jethani\AppData\Local\Temp\a04c422f9f0eb30ee011fe38'... OK
Deleting temporary file 'C:\Users\rekha.jethani\AppData\Local\Temp\a04c422f9f0eb30ee011fe38'... OK
Testing IFileSystem instance...
UserHomePath: C:\Users\rekha.jethani
UserDataDirectoryPath: C:\Users\rekha.jethani\.gcm
GetCurrentDirectory(): C:\Courts-Clone_AWS

------------
Diagnostic: Networking
Skipped: False
Success: True
Exception: None
Log:
Checking basic networking and HTTP stack...
Creating HTTP client... OK
IsNetworkAvailable: True
Sending HEAD request to http://example.com... OK
Sending HEAD request to https://example.com... OK
Acquiring free TCP port... OK
Testing local HTTP loopback connections...
Creating new HTTP listener for http://localhost:59963/... OK
Waiting for loopback connection... OK
Writing response... OK
Waiting for response data... OK
Loopback connection data OK
Testing with IHttpClientFactory created HTTP client...
Creating HTTP client... OK
IsNetworkAvailable: True
Sending HEAD request to http://example.com... OK
Sending HEAD request to https://example.com... OK
Acquiring free TCP port... OK
Testing local HTTP loopback connections...
Creating new HTTP listener for http://localhost:59967/... OK
Waiting for loopback connection... OK
Writing response... OK
Waiting for response data... OK
Loopback connection data OK

------------
Diagnostic: Git
Skipped: False
Success: True
Exception: None
Log:
Getting Git version... OK
Git version is '2.36.1.windows.1'
Locating current repository... OK
Not inside a Git repository.
Listing all Git configuration... OK
Git configuration:
file:C:/Program Files/Git/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig	http.sslbackend=openssl
file:C:/Program Files/Git/etc/gitconfig	http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/etc/gitconfig	core.autocrlf=true
file:C:/Program Files/Git/etc/gitconfig	core.fscache=true
file:C:/Program Files/Git/etc/gitconfig	core.symlinks=true
file:C:/Program Files/Git/etc/gitconfig	pull.rebase=false
file:C:/Program Files/Git/etc/gitconfig	init.defaultbranch=master
file:C:/Users/rekha.jethani/.gitconfig	init.templatedir=C:/Users/rekha.jethani/.acn-security-tools/git-template
file:C:/Users/rekha.jethani/.gitconfig	winupdater.recentlyseenversion=2.26.0.windows.1
file:C:/Users/rekha.jethani/.gitconfig	credential.https://git-codecommit.eu-west-1.amazonaws.com.provider=generic
file:C:/Users/rekha.jethani/.gitconfig	credential.credentialstore=wincredman
file:C:/Users/rekha.jethani/.gitconfig	credential.helper=manager
file:C:/Users/rekha.jethani/.gitconfig	credential.usehttppath=true
file:C:/Users/rekha.jethani/.gitconfig	credential.usehttpspath=true
file:C:/Users/rekha.jethani/.gitconfig	credential.https://git-codecommit.*.amazonaws.com.helper=!aws codecommit credential-helper $@
file:C:/Users/rekha.jethani/.gitconfig	credential.https://git-codecommit.*.amazonaws.com.usehttppath=true
file:C:/Users/rekha.jethani/.gitconfig	user.name=rekha.jethani-at-570307279104
file:C:/Users/rekha.jethani/.gitconfig	user.password=CprSJGg5h68ex0r2SzgZlXCar7Bee8cEf4UEsVMWmAU=

------------
Diagnostic: Credential storage
Skipped: False
Success: False
Exception:
System.Exception: Unable to persist credentials with the 'wincredman' credential store.
See https://aka.ms/gcm/credstores for more information.
   at GitCredentialManager.CredentialStore.ValidateWindowsCredentialManager()
   at GitCredentialManager.CredentialStore.EnsureBackingStore()
   at GitCredentialManager.CredentialStore.Remove(String service, String account)
   at GitCredentialManager.Diagnostics.CredentialStoreDiagnostic.RunInternalAsync(StringBuilder log, IList`1 additionalFiles)
   at GitCredentialManager.Diagnostics.Diagnostic.<RunAsync>d__5.MoveNext()
Log:
ICredentialStore instance is of type: CredentialStore
Writing test credential...Deleting test credential...
------------
Diagnostic: Microsoft authentication (AAD/MSA)
Skipped: False
Success: True
Exception: None
Log:
Broker not supported.
Flow type is: Auto
Gathering MSAL token cache data... OK
CacheDirectory: C:\Users\rekha.jethani\AppData\Local\.IdentityService
CacheFileName: msal.cache
CacheFilePath: C:\Users\rekha.jethani\AppData\Local\.IdentityService\msal.cache
Creating cache helper... OK
Verifying MSAL token cache persistence... OK

------------
Diagnostic: GitHub API
Skipped: False
Success: True
Exception: None
Log:
Using 'https://github.com/' as API target.
Querying '/meta' endpoint... OK

**Comment by ldennington** [comment]
I am admittedly not super familiar with AWS Code Commit, but it seems Amazon provides [a credential helper specifically for it](https://docs.aws.amazon.com/cli/latest/reference/codecommit/credential-helper/index.html). It looks like [Git Remote Code Commit](https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-git-remote-codecommit.html) is another highly-recommended alternative and [SSH](https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up.html?shortFooter=true#setting-up-other) is an option as well.
