### ISSUE TITLE
Authentication on Bitbucket DC fails - Redirects to bitbucket.org

### ISSUE THREAD

**Issue by augustocarvalho** [GitCredentialManager/git-credential-manager#722]
**Which version of GCM are you using?**
2.0.696+4365b917da

**Which Git host provider are you trying to connect to?**
Bitbucket DC (On prem)

**Expected behavior**

I am trying to clone a repo from a Bitbucket DC on prem.
GMC detects that it is a bitbucket server (I see the right host with the trace and on my gitconfig it shows the provider = bitbucket)

But redirects the authentication to bitbucket.org:

**Logs**
10:46:46.972059 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   protocol=https
10:46:46.972059 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   host=mybitbucket_url
10:46:46.972059 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   username=myusername
10:46:47.103677 ...oviderRegistry.cs:99 trace: [GetProviderAsync] Host provider override was set id='bitbucket'
10:46:47.103677 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'Bitbucket' was selected.
10:46:47.312195 ...tHostProvider.cs:103 trace: [GetStoredCredentials] Look for existing credentials under mybitbucket_url ...
10:46:47.713122 ...tHostProvider.cs:109 trace: [GetStoredCredentials] No stored credentials found
10:46:47.713122 ...tHostProvider.cs:126 trace: [GetRefreshedCredentials] Refresh credentials...
10:46:47.713122 ...tHostProvider.cs:131 trace: [GetRefreshedCredentials] Checking for refresh token...
10:46:47.713122 ...tHostProvider.cs:138 trace: [GetRefreshedCredentials] No stored refresh token found
10:46:47.713122 ...tHostProvider.cs:146 trace: [GetRefreshedCredentials] Prompt for credentials...
10:46:48.342977 ...enticationBase.cs:40 trace: [InvokeHelperAsync] Starting helper process: C:\Program Files\Git\mingw64\bin\Atlassian.Bitbucket.UI.exe userpass --username myusername
10:46:55.577219 ...tHostProvider.cs:167 trace: [GetRefreshedCredentials] Checking if two-factor requirements for credentials...
10:46:55.577219 ...tHostProvider.cs:376 trace: [RequiresTwoFactorAuthenticationAsync] Check if 2FA is required for credentials (myusername/********)...
10:46:55.593222 ...tbucketRestApi.cs:74 trace: [GetUserInformationAsync] HTTP: GET https://api.bitbucket.org/2.0/user
10:46:55.593222 ...pClientFactory.cs:58 trace: [CreateClient] Creating new HTTP client instance...
10:46:57.061702 ...pClientFactory.cs:97 trace: [CreateClient] Custom certificate verification has been enabled with certificate bundle at C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
10:46:57.517012 ...tbucketRestApi.cs:77 trace: [GetUserInformationAsync] HTTP: Response 401 [Unauthorized]

**Comment by ldennington** [comment]
@mminns - would you mind taking a look at this? Perhaps it'll be fixed with #607?

**Comment by mminns** [comment]
Morning @augustocarvalho 

Could you post up your `git config` settings, please?

It looks like you have set `credential.provider` ?

If its at all possible would you be able to post your Bitbucket DC URL or at least a close copy showing the structure of the URL?

Thanks

**Comment by mminns** [comment]
Finally have a little time to look into this

**Comment by augustocarvalho** [comment]
Hi, thanks for the fix. 
I can confirm that the new version works, the authentication is redirected to our Bitbucket instance.

$ git credential-manager-core --version
2.0.779+57cd9d4e50

$ git --version
git version 2.37.0.windows.1
