### ISSUE TITLE
Facebook 

### ISSUE THREAD

**Issue by Ha607** [GitCredentialManager/git-credential-manager#733]
Forgot password

**Comment by Rhondad3** [comment]
👍

**Comment by Rhondad3** [comment]
This is Rhonda Douglas, I have not authorized. Any transactions or password
resets, my accounts Facebook , email etc have been taken over by an
identity theft. There should be no transactions between myself and git hub.
All of my credentials have been compromised , you may contact me directly
via email or by phone 425-399-6659 , thank you
