### ISSUE TITLE
Incorrect doc on how to uninstall on Ubuntu

### ISSUE THREAD

**Issue by Shawn91** [GitCredentialManager/git-credential-manager#741]
The command in documentation on how to uninstall gcm on Linux is `sudo dpkg -r gcm` . 

However, after running the command on my Ubuntu server, a warning was issued `dpkg: warning: ignoring request to remove gcm which isn't installed`.

After searching through the packages installed on my server, it seems the correct command should be `sudo dpkg -r gcmcore`

**Comment by dscho** [comment]
Good point. Could you kindly open a Pull Request?

**Comment by dscho** [comment]
> Could you kindly open a Pull Request?

@Shawn91 just in case you read this as a "go away", I want to stress that this was an honest invitation to contribute, to help the project along. No harm intended on my side!
