### ISSUE TITLE
Should build.sh use $RUNTIME to name the build package

### ISSUE THREAD

**Issue by mminns** [GitCredentialManager/git-credential-manager#774]
Unless explicitly specified build.sh will automatically determine the underlying architecture but regardless always call the final package `osx-x64`, i.e. https://github.com/GitCredentialManager/git-credential-manager/blob/dd4fe479cb7cd60bcb90a1fd3bd1606a3a4b845a/src/osx/Installer.Mac/build.sh#L64

Should it not use the $RUNTIME variable instead?

DISTOUT="$OUTDIR/gcm-$RUNTIME-$VERSION.pkg"

**Comment by ldennington** [comment]
Thanks for calling this out @mminns! I've opened #788 to fix.
