### ISSUE TITLE
GitLab Support documentation: 'Expire access tokens' no longer valid?

### ISSUE THREAD

**Issue by cornejom** [GitCredentialManager/git-credential-manager#780]
GCM's [GitLab Support](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/gitlab.md) page says that when creating an OAuth application to unselect the 'Confidential' option, and ensure the 'Expire access tokens' option is selected.    
I am using GitLab Enterprise Edition 13.11.3-ee and the 'Expire access tokens' is not available.  See partial screengrab below.     
Is the support documentation out of date?

![OAuth Gitlab](https://user-images.githubusercontent.com/6126003/177597570-09b1e481-4640-47a3-8394-42068a0b1a9f.png)
.

**Comment by ldennington** [comment]
Thanks for calling this out! You are correct that this document is out of date. Would you mind submitting a PR to remove the instruction to uncheck 'Expire access tokens'?

**Comment by cornejom** [comment]
Sure ... but I'm not familiar with the PR process.  Should I edit the relevant file in the main branch?  Then commit?  Then create PR?  Or do I need to create another branch before editing?
I don't seem to have ability to create new branches.

**Comment by ldennington** [comment]
No problem. These steps should work for you:

1. [Fork the repository](https://docs.github.com/en/get-started/quickstart/fork-a-repo).
2. Clone your new fork.
3. Check out a new branch locally by running `git checkout -b fix-gitlab-support-docs` in the directory where you cloned the repo.
4. Make your changes and commit them (take a look at [this article](https://github.blog/2022-06-30-write-better-commits-build-better-projects/) for guidelines on structuring commits).
5. Push your changes by running `git push --set-upstream origin fix-gitlab-support-docs` in the directory where you cloned the repo.
6. Go to the [**Pull Requests**](https://github.com/GitCredentialManager/git-credential-manager/pulls) tab of `GitCredentialManager/git-credential-manager`.
7. There should be an option for you to create a pull request with the branch you just pushed.
