### ISSUE TITLE
This application could not be started 

### ISSUE THREAD

**Issue by bckelley** [GitCredentialManager/git-credential-manager#792]
error appears in both vscode and powershell.

**Comment by KisaragiEffective** [comment]
You should report more details with the recommended way.

**Comment by bckelley** [comment]
i don't understand report what exactly to who

**Comment by ashemedai** [comment]
Your current issue lacks a lot of details for the project members to even begin offering any help. Start by providing details such as which version of GCM did you install, what is the operating system, what is the operating system's version, what is the version of VS Code used. What are the exact erorr messages you are getting, screenshot as necessary.

**Comment by ldennington** [comment]
All of @ashemedai's suggestions are good. Additionally, you may want to follow [these instructions](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/environment.md#gcm_trace) for trace logging and paste the logs into the issue as well (making sure to redact any sensitive information).

**Comment by Mrkojtis** [comment]
1. > Start a community website for understanding and good companionship! 💚

> #768  #694  #791 #794 


![Screenshot_20220718-213945](https://user-images.githubusercontent.com/92351915/179605571-e4096949-ebd4-4e2a-9a41-04094cb0955a.png) 

                                      My phone !

**Comment by ldennington** [comment]
Closing due to lack of response. If you're still experiencing the issue, please open a separate issue and be sure to fill out the template and provide trace logs.
