### ISSUE TITLE
Package for Fedora Linux

### ISSUE THREAD

**Issue by hickford** [GitCredentialManager/git-credential-manager#816]
If it helps anyone, I packaged git-credential-manager for Fedora Linux in an *experimental* personal repo. https://copr.fedorainfracloud.org/coprs/matthickford/git-credential-manager/ . Feedback welcome and help testing appreciated.  

The bulk of the work was writing the rpm spec https://github.com/hickford/git-credential-manager/pull/2/files

What's pretty cool is that the rpm package is **only 1.5 MB** because it depends on package [dotnet-runtime-6.0](https://packages.fedoraproject.org/pkgs/dotnet6.0/dotnet-runtime-6.0/) in Fedora. For comparison, the [official GCM binaries](https://github.com/GitCredentialManager/git-credential-manager/releases) and deb package are over 100 MB because they self-contain the .NET runtime.

Ultimately I hope to get git-credential-manager included as an official Fedora package https://fedoraproject.org/wiki/Package_maintainers_wishlist https://docs.fedoraproject.org/en-US/package-maintainers/New_Package_Process_for_New_Contributors/

**Comment by hickford** [comment]
The same idea would work to produce small packages for Debian or Ubuntu, but because these distributions don't include .NET,  users would first have to install .NET from packages.microsoft.com following https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian . This would be fine for a personal PPA archive, but an obstacle to including git-credential-manager in Debian officially.

**Comment by ldennington** [comment]
I think it may be better long-term to focus on supporting GCM as a dotnet tool. While it would be super cool to have packages on the official Ubuntu/Debian/Fedora/etc. feeds, the amount of maintenance required with each added feed could become problematic. What I love about the dotnet tool approach is that we publish to a single feed that can be accessed from any Linux distro.

**Comment by hickford** [comment]
I agree.

**Comment by ebibesty** [comment]
Unsubscribe me please
