### ISSUE TITLE
Error when trying to clone Azure DevOps Repo (Git). fatal: Failed to create PAT: TF401444: Please sign-in at least once as *Tenant ID\\*wrong account* in a web browser to enable access to the service.

### ISSUE THREAD

**Issue by jossgc** [GitCredentialManager/git-credential-manager#850]
Submitting this on behalf of my affected customer. Previous consent granted to share logs and information collected.

**Which version of GCM are you using?**

From a terminal, run `git credential-manager-core --version` and paste the output.

**Result:** 
git credential-manager-core --version 2.0.785+6074e4e3d3

**Which Git host provider are you trying to connect to?**

* [x] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

From a terminal, run `git remote -v` to see your remote URL.

* [ ] Yes
* [x] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [ ] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [x] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [ ] Not applicable
* [x] I only see one identity (only the wrong account)
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

Whenever affected user tries to clone any of his repositories the Credential Manager window pop-ups to login, it shows only the user account that he uses to login to his local computer (which is not the correct one), so he manually type in the correct account to login but still shows a permission error (see below) and lists the local account for his computer, which is not the account that is part of the Azure DevOps organization.

Same scenario experienced when trying to clone the Repo from Visual Studio, affected user is able to connect to the project, but at the moment he tries to clone the repo, he experience the same behavior.

**Troubleshooting done so far**
Log out from all visual studio sessions opened.
Close all visual Studio instances.
Go to the following locationS and clear up the content:
%localappdata%\microsoft\VisualStudio (for this, there can be multiple numbers, such as 12.0, 13.0, and so on. Please go for each one and delete the folder called: ComponentModelCache)
%localappdata%\microsoft\VSCommon
%localappdata%\.identityservice (This will clean up the entire cache including AAD, session and account data)
%localappdata%/Microsoft/VisualStudio
%localappdata%/Microsoft/VisualStudio Services
After this please restart Visual Studio and try again.
**Result: issue persists**

we ran under the git bash command git --version to confirm we are on latest version, which we are (2.37.1)
-we checked user's permissions within DevOps (organization's permission, project's permission, repo's permission and Project Administrator's permissions), all in place and good.
-cleaned .IdentityService folder again: C:\Users\<username>\AppData\Local\.IdentityService
-Went back to git bash and try again to clone the repo: issue persists.
-we confirmed VS version: VS 2019 16.11.17
-we look up for the following path: [file:///C:/Program%20Files/Git/mingw64/share/doc/git-doc/git-credential.html](https://onesupport.crm.dynamics.com/_imgs/loading.gif#) with this will be skip clone process and we will go straight to credential part. 
-On git bash we ran the following, issue persists:
git credential fill <enter>
protocol=https <enter>
host=dev.azure.com <enter>
path=<URL-path-to-repository> 
 
-tried again but adding extra property username and trying with capital letters as per UPN (to disregard if it is an issue with case sensitive), issue persists:
git credential fill <enter>
protocol=https <enter>
host=dev.azure.com <enter>
path=<URL-path-to-repository> 
Username=<admin-username>
 
-affected user confirmed he is using a VPN but another user has the same error and there is another user that don't. Access to Azure DevOps Portal works perfectly, and from VS he is able to connect to Projects, issue begins when he tried to clone the repo.
-we tried to add the required account directly to the credential manager and try to clone again from git bash: issue persists.
-restarted git bash: issue persists.
-deleted manual entry of the account on Credential Manager.

Another thing we noticed is that if we go to Control Panel > Credential Manager > Windows Credential > There isn't any credential stored there, nor for Git or Visual Studio.

**Logs**

Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command. Review and redact any private information and attach the log.

-see attached file: gitLog-updated.txt

$ git clone https://Qurate@dev.azure.com/Qurate/QRG-EDW/_git/EDW_Admins_DeltaLake
Cloning into 'EDW_Admins_DeltaLake'...
warning: ----------------- SECURITY WARNING ----------------
warning: | TLS certificate verification has been disabled! |
warning: ---------------------------------------------------
warning: HTTPS connections may not be secure. See https://aka.ms/gcm/tlsverify for more information.
warning: ----------------- SECURITY WARNING ----------------
warning: | TLS certificate verification has been disabled! |
warning: ---------------------------------------------------
warning: HTTPS connections may not be secure. See https://aka.ms/gcm/tlsverify for more information.
fatal: Failed to create PAT: TF401444: Please sign-in at least once as **AAD Tenant ID**\\**wrong local account**  in a web browser to enable access to the service.
fatal: Authentication failed for 'https://dev.azure.com/Qurate/QRG-EDW/_git/EDW_Admins_DeltaLake/
[gitLog-updated.txt](https://github.com/GitCredentialManager/git-credential-manager/files/9435314/gitLog-updated.txt)
'

**Comment by jossgc** [comment]
I believe they haven't, let me confirm with them about it and came back with the result. 
Just one quick question, either way if they are typing the account that they need to use, it should catch or take into consideration the information we typed in despite not being shown in the picker?
Thanks in advance for your support.

**Comment by ldennington** [comment]
No, you're correct. Since they're manually entering their details, that should work. Would the customer be comfortable sharing the contents of their git config (i.e. what they see when they run `git config --global`)?

**Comment by jossgc** [comment]
I can ask them, however I will need to modify the PII that could contain related to username or something like that, is that okay with you? 
On our case we collected similar information but as git config --global --list, I don't know if that information also helps.

**Comment by ldennington** [comment]
`git config --global --list` shows the same information, just formatted differently. I'm curious whether there's a config set that maps the org to the incorrect username. It would look something like this:

`credential.azrepos:org/qurate.username=<wrong local account>`

**Comment by jossgc** [comment]
It actually shows the correct account in there, see (PII edited):
xxx@xxxx MINGW64 ~

$ git config --global --list

user.name=<Customer name>

[user.email=<customer correct account>

core.editor="C:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait

credential.https://dev.azure.com.usehttppath=true

credential.microsoft.visualstudio.com.authority=AAD

credential.helper=

credential.helper=manager-core

**Comment by ldennington** [comment]
As I'm looking at the logs, I see the following:

`13:47:02.451700 ...\Common.cs:744       trace: [Main] git-credential-manager (v1.20.0) 'get'`

I'm thinking that somehow an old version of GCM is being called that could be causing this issue - the logs are showing `1.20.0`, whereas the current version is `2.0.785`. I'm thinking this may be due to the `credential.helper` config being set to `manager-core` rather than the full path to GCM. Can the customer send along output of the following (running from `cmd` rather than `bash`:

`git version && where git && git-credential-manager-core --version && where git-credential-manager-core`

**Comment by jossgc** [comment]
For sure, I already asked them requesting that information; I'm pending on their response. 
I think they updated the Git version after those logs were captured, but I'm not completely sure. Once I've heard from them again, I will update this issue with the respective information. Thanks!

**Comment by jossgc** [comment]
My customer confirmed the output of the command indicated previously, see below:
Command outputs: 

C:\WINDOWS\System32>git version

git version 2.37.1.windows.1
 

C:\WINDOWS\System32>where git

C:\Program Files\Git\cmd\git.exe

 

C:\WINDOWS\System32>git-credential-manager-core --version

'git-credential-manager-core' is not recognized as an internal or external command,

operable program or batch file.

 

C:\WINDOWS\System32>git credential-manager-core --version

2.0.785+6074e4e3d3

 

C:\WINDOWS\System32>

C:\WINDOWS\System32>

C:\WINDOWS\System32>where git credential-manager-core

C:\Program Files\Git\cmd\git.exe

INFO: Could not find "credential-manager-core".


Also, about the first action plan to add the affected account to the local PC, it didn't let him complete the process, see:
![image](https://user-images.githubusercontent.com/66031675/187474271-588cff1f-9f60-41a5-89a4-a9bfc1093c79.png)

**Comment by ldennington** [comment]
Ok, so I did some more digging, and what I believe is happening is that _somehow_ there is an old installation of the deprecated [Git Credential Manager for Windows tool](https://github.com/microsoft/Git-Credential-Manager-for-Windows) that is being called _instead of GCM_ (which is the tool that replaced that tool). If you look at the **Releases** page of the old Git Credential Manager tool, you can see [the last version released was 1.20.0](https://github.com/microsoft/Git-Credential-Manager-for-Windows/releases/tag/1.20.0), which aligns with the version I saw in the logs. That also explains why I was seeing class names in the logs that don't exist in GCM.

My recommendation is the following:

1. Uninstall the old Git Credential Manager for Windows tool via Control Panel.
<img width="701" alt="image" src="https://user-images.githubusercontent.com/11321782/187520745-8c2ae8a8-2ca6-4453-9770-6dfefa0adbd2.png">
2. Remove the following config values (you can run `git config --global -e` to edit the config file and manually remove them):

```
[credential]
        helper =
        helper = manager-core
[credential "microsoft.visualstudio.com"]
        authority = AAD
```

4. Upgrade to the [latest version of Git](https://github.com/git-for-windows/git/releases/download/v2.37.2.windows.2/Git-2.37.2.2-64-bit.exe) (which comes with the new Git Credential Manager tool bundled).
5. Re-try the workflow.

**Comment by jossgc** [comment]
Perfect! I will share this steps with my customer and let you know the result. Do you think it will be useful to enable the environment variables GCM_TRACE=1 and GIT_TRACE=1 when retrying to clone the Repo in case issue persists?

**Comment by ldennington** [comment]
Yep, I think that's a great idea! Thanks.

**Comment by jossgc** [comment]
FYI: my customer is trying to follow up the action plan provided and on the first step, under the Control Panel is not listed the Git Credential Manager to uninstall it, see:
![image](https://user-images.githubusercontent.com/66031675/187552764-d5d9d821-69ac-4eae-8a7f-bfa46145703b.png)

I indicated him to continue with the next steps, to see if there is any change on behavior. I will let you know how it goes. Thanks!

**Comment by jossgc** [comment]
Hi, my customer followed the steps and tried again however issue persists. We are pending on getting complete traces, in the meantime, see:

![image](https://user-images.githubusercontent.com/66031675/187739721-fdbd245d-4379-4eee-bfd7-e65078b0d32a.png)

**Comment by jossgc** [comment]
Hi, see attached recent log after action plan provided (PII information modified). If further information or actions are required from our end, feel free to let me know :)
[git_output-updatedwithoutpii.txt](https://github.com/GitCredentialManager/git-credential-manager/files/9464955/git_output-updatedwithoutpii.txt)

**Comment by ldennington** [comment]
Thanks for sending those along! At least we are now using GCM rather than the deprecated tool 😊.

I dug in and found that the issue seems to be happening with [this call](https://github.com/GitCredentialManager/git-credential-manager/blob/2a077a874b32d987cd4849b17adca96b413ad57a/src/shared/Core/Authentication/MicrosoftAuthentication.cs#L178-L186). What I imagine the flow looks like is:

The linked call happens --> A web browser opens with the account picker --> Your customer manually enters their account details --> A token is returned _for the wrong account_

That call is actually part of the [Microsoft Authentication Library for Dotnet](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet) (MSAL for short). So it could be worth opening an issue with that team, with a link to this issue for background.

In the meantime, I am unfortunately [leaving the country tomorrow and will not be back until September 6](https://github.com/GitCredentialManager/git-credential-manager/issues/853). You could try [going through some different auth flows other than embedded](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/configuration.md#credentialmsauthflow), but unfortunately each of them will lead to an account picker. I think filing an issue with the MSAL team is probably your best bet.

**Comment by jossgc** [comment]
Thanks for your inputs and continues help over this.
And yes, that's the flow. I will open the respective issue with them then. Thanks a lot!
Enjoy your vacations! :)

**Comment by bgavrilMS** [comment]
Hi, I'm from MSAL team and I can't see what the issue here could be with MSAL. Please give us more information. Here's what I understand: 

1. User logs in and the account picker opens
2. User manually enters a new account 
3. A token is returned for this account, but that token leads to an auth error.

@ldennington - are you sure that the new account is actually authorized to perform the operation? Are you implying that the token is for the wrong account?

**Comment by jossgc** [comment]
Hi @bgavrilMS, thanks for looking into this. Yes, your statements are correct. We are assuming that the toke generated is for the wrong account, since on error message always points to the wrong account, not the one that we manually typed in.
And yes, the user's account is authorized to perform the operation.
Thanks in advance!

**Comment by mjcheetham** [comment]
@jossgc please could you have the user try again but also enable the following environment variable to include internal MSAL trace information?

```
GCM_TRACE_MSAUTH=1
```

Make sure to also have set `GCM_TRACE=1`.

Note that the information included in trace output will now be much larger and contain more PII that should be redacted appropriately.

This information will help us understand what MSAL is doing to acquire a token for the wrong account.

**Comment by ldennington** [comment]
We have a suspicion that somehow your customer's local account is AAD joined while their corporate account is joined to their company's network. We may be able to unblock them by having them try something like [device flow](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/configuration.md#credentialmsauthflow) using their phone (similar to how one might authenticate to a streaming service on their television).

**Comment by jossgc** [comment]
Hi, thank you!
Okay, let me share this with the customer and see how it goes. Just being curious, 

1. if that will be the case, their entire team wouldn't have the same behavior? They have one colleague that is able to perform git operation as normal, I think it has the same environment/configuration as my customer. 
2. if my customer adds his account to the company's network might help to resolve the issue as well? (just looking for possible workaround in case the device flow cannot be implemented due company's policies or something).

Thanks again! I will share the respective output.

**Comment by ldennington** [comment]
Perhaps it would be better to gather some more information to ensure the customer has set all the requested environment variables correctly. In Git bash, can they run the below command and then send along the redacted logs.

```console
GCM_TRACE=1 GCM_TRACE_MSAUTH=1 git clone https://Qurate@dev.azure.com/Qurate/QRG-EDW/_git/EDW_Admins_SynapseDW-UDC
```

Additionally, a [Fiddler trace](https://docs.telerik.com/fiddler/configure-fiddler/tasks/configurefiddler) would be extremely helpful for us to debug this issue. The customer can obtain this trace by downloading Fiddler, enabling decryption following [these instructions](https://docs.telerik.com/fiddler/configure-fiddler/tasks/decrypthttps). Note that this trace will be quite large and contain a fair amount of PII, since it captures everything running on the machine. If you don't feel comfortable redacting and sharing this trace publicly, feel free to send it via [email](mailto:gcmsupport@github.com).

**Comment by jossgc** [comment]
Hi! My customer worked under the device flow action and shared the respective output of it. It failed still. 
Attached you can find the respective logs. Do you still want me to collect the last traces requested (last git trace when activating the device flow didn't have enabled the env variable `"GCM_TRACE_MSAUTH=1"`) or should I wait for your comments about the trace when using device flow?
[Git_output_09_15_2022-withoutpii.txt](https://github.com/GitCredentialManager/git-credential-manager/files/9608651/Git_output_09_15_2022-withoutpii.txt)

**Comment by ldennington** [comment]
Based on my reading of the latest logs, it seems that MSAL expired while generating the device code. I think the best course of action would be to return to the default MS Auth flow by running the following:

`git config --global credential.msauthFlow default`

Then have your customer run the command from my previous comment, plus provide the Fiddler trace either publicly or privately.

**Comment by bgavrilMS** [comment]
It's not clear from the logs how long the customer waited before logging in, but I assume that more than 15 minutes? This seems like an excessive amount of time, and the flow is abandoned by the token issuer (AAD). Did the user actually not log in ? We might need more logs, such as the MSAL logs.

@ldennington is also correct in suggesting to use interactive authentication (this is where a browser pops up). Device Code Flow is useful when you are logging into a box without UI, such as headless Linux or a terminal connection to a Windows box. Is this the case?

**Comment by ldennington** [comment]
> It's not clear from the logs how long the customer waited before logging in, but it looks like they waited more than 15 minutes? This seems like an excessive amount of time, and the flow is abandoned by the token issuer (AAD). Did the user actually not log in ? We might need more logs, such as the MSAL logs.

This was my initial thought as well, but when Matthew and I compared the logs Joselyn sent over to logs from Matthew's machine, we saw the following:

```
13:54:11.760761 ...uthentication.cs:222 trace: [GetFlowType] Microsoft auth flow overriden to 'devicecode'.
13:54:11.761240 ...uthentication.cs:198 trace: [GetTokenAsync] Performing interactive auth with device code...
13:54:11.805962 ...pClientFactory.cs:58 trace: [CreateClient] Creating new HTTP client instance...
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code E2JANLQNG to authenticate.
```

When you compare this to the customer's logs, it seems to show that no code was ever provided, so they never had a chance to enter it:

```
09:20:54.277803 ...uthentication.cs:222 trace: [GetFlowType] Microsoft auth flow overriden to 'devicecode'.
09:20:54.277803 ...uthentication.cs:198 trace: [GetTokenAsync] Performing interactive auth with device code...
09:20:54.325685 ...pClientFactory.cs:58 trace: [CreateClient] Creating new HTTP client instance...
fatal: Verification code expired before contacting the server
```

**Comment by ldennington** [comment]
> @ldennington is also correct in suggesting to use interactive authentication (this is where a browser pops up). Device Code Flow is useful when you are logging into a box without UI, such as headless Linux or a terminal connection to a Windows box. Is this the case?

I suggested device flow as a potential alternative to get auth working for the customer. Since that also didn't work, I figured it would be best to get additional logs/traces and continue to attempt to get to the bottom of the original issue.

**Comment by jossgc** [comment]
Okay, understood. Let me ask him for the git trace with the environment variables requested and the Fiddler trace and get back to you. 
Thanks for your help on this, I know it is a tricky issue so I appreciate your continues help on it :)

**Comment by bgavrilMS** [comment]
@jossgc - feel free to ask the customer to join this discussion, it is a public forum after all.

**Comment by jossgc** [comment]
Just to confirm, to be able to capture Fiddler trace while performing the git clone operation I only need to enable these config right?
```
git config --global http.proxy 127.0.0.1:8888
git config --global http.sslVerify false
```
Is because I'm trying to repro the instructions to share them with my customer, however, under Fiddler only show me this (see image below), which for me seems incomplete. I do have the Git_Traces variable enabled and under Fiddler I have the Decrypt Option enabled as well. Basically it shows one 200 status code indicating connection to the repo was useful and another indicating clone action was completed. I don't think that kind information will be useful for investigation (in this scenario where is not showing complete information, not the Fiddler trace as is)

![image](https://user-images.githubusercontent.com/66031675/191550063-5a3c63ba-fe2a-4b92-b0c3-c5d687cc9bba.png)


Any input will be highly appreciated! :)

**Comment by ldennington** [comment]
@jossgc I think the Fiddler trace is most useful when you don't already have a valid Azure DevOps credential in your local Credential Store. I attempted this flow with an Azure DevOps repo I already had credentials stored for and got the same result as you. However, when I attempted it with your customer's repo (which I obviously do _not_ have credentials stored for and, in fact, am not allowed access to at all), I was prompted to authenticate and got more of the information we're looking for.

<img width="512" alt="image" src="https://user-images.githubusercontent.com/11321782/191595184-229720f8-b3c2-41e9-8bcc-e3cd3010c77d.png">

@mjcheetham - anything else you'd like to add here? Or are we still good using the steps outlined above when asking for the customer's Fiddler trace?

**Comment by jossgc** [comment]
@ldennington oh okay! I worried since I'm used to see a lot more information on Fiddler traces even on successful scenarios. Thanks!

**Comment by mjcheetham** [comment]
I would expect Fiddler traces similar to what @ldennington has shown, with calls to both `dev.azure.com` and `login.microsoftonline.com`. Clearing any stored credentials before recording a trace would work.

But please also make sure that `GCM_TRACE_MSAUTH=1` is also set alongside `GCM_TRACE=1` and `GIT_TRACE=1`.. we need to be able to correlate between the MSAL logs, Git and GCM logs, and the network traffic as recorded by Fiddler.

Again, the Fiddler trace and MSAL logs file will contain lots of secrets, so you may need to send these to us via a private channel.

**Comment by jossgc** [comment]
Understood! I will provide this information to the customer and contact you back once I have it. Thanks!

**Comment by elementary-my-friend** [comment]
I'm ver, very sorry that I have caused all a lot of "confusion", not on
GitHub"s part, but due to *my ignorance *about almost everything GitHub is
for, and what I did to cause a waste of time to everyone who took the time
to email  me.
Please know that I didn't mean to cause any inconvenience to *anybody*.

Thank you,
Anne Marie Wentworth

**Comment by jossgc** [comment]
Hi team, my customer confirmed issue is solved. 
Thanks for your efforts, assistance and guidance over this @ldennington @mjcheetham. I highly appreciated :)

**Comment by ldennington** [comment]
Glad to hear that it's been solved!
