### ISSUE TITLE
"fatal: Invalid 'host' input argument (cannot be empty)" when using https://repo.or.cz

### ISSUE THREAD

**Issue by ebblake** [GitCredentialManager/git-credential-manager#854]
**Which version of GCM are you using?**

From a terminal, run `git credential-manager-core --version` and paste the output.
2.0.810+1f8e978a46

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [X] Other - please describe
I've tried to set up ssh keys as instructed by https://repo.or.cz/httpspush.html.  Now, every time I try to connect to that repository, I get the error message "fatal: Invalid 'host' input argument (cannot be empty)" from git-credential-manager-core, even though my other credential managers are still able to provide a password and let me proceed.

**Can you access the remote repository directly in the browser using the remote URL?**

From a terminal, run `git remote -v` to see your remote URL.

* [X] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe
I'm trying to connect to https://repo.or.cz/libnbd/ericb.git as username 'ericb' and with ~/.gitconfig containing:
```
[http "https://repo.or.cz"]
	sslCert = /home/eblake/certs/rorcz_ericb_user_1.pem
	sslKey = /home/eblake/.ssh/id_rsa-2011
	sslCertPasswordProtected = true
```
---

**_[Azure DevOps only]_ What format is your remote URL?**

* [X] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [X] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I don't get slammed with spurious stderr messages while my other credential manager (libsecret) kicks in.  Better yet, gcm should handle repo.or.cz natively so I don't need another credential manager.

**Actual behavior**

Every call to gcm in relation to repo.or.cz triggers an error message.

**Logs**

Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command. Review and redact any private information and attach the log.
```
$ GIT_TRACE=1 GCM_TRACE=1 git remote show repo
14:17:33.875707 git.c:460               trace: built-in: git remote show repo
14:17:33.876629 run-command.c:654       trace: run_command: GIT_DIR=.git git remote-https repo https://repo.or.cz/libnbd/ericb
14:17:33.879561 git.c:749               trace: exec: git-remote-https repo https://repo.or.cz/libnbd/ericb
14:17:33.879636 run-command.c:654       trace: run_command: git-remote-https repo https://repo.or.cz/libnbd/ericb
14:17:33.893845 run-command.c:654       trace: run_command: 'git credential-libsecret get'
14:17:33.900905 git.c:749               trace: exec: git-credential-libsecret get
14:17:33.900984 run-command.c:654       trace: run_command: git-credential-libsecret get
14:17:34.660053 run-command.c:654       trace: run_command: 'git credential-libsecret store'
14:17:34.666810 git.c:749               trace: exec: git-credential-libsecret store
14:17:34.666896 run-command.c:654       trace: run_command: git-credential-libsecret store
14:17:34.724808 run-command.c:654       trace: run_command: '/usr/local/share/gcm-core/git-credential-manager-core store'
14:17:34.825391 ...re/Application.cs:95 trace: [RunInternalAsync] Version: 2.0.810.36383
14:17:34.826465 ...re/Application.cs:96 trace: [RunInternalAsync] Runtime: .NET 6.0.8
14:17:34.826486 ...re/Application.cs:97 trace: [RunInternalAsync] Platform: Linux (x86-64)
14:17:34.826499 ...re/Application.cs:98 trace: [RunInternalAsync] OSVersion: Linux green 5.18.19-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Aug 21 15:52:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
14:17:34.826548 ...re/Application.cs:99 trace: [RunInternalAsync] AppPath: /usr/local/share/gcm-core/git-credential-manager-core
14:17:34.826570 ...e/Application.cs:100 trace: [RunInternalAsync] Arguments: store
14:17:34.882523 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'store' command...
fatal: Invalid 'host' input argument (cannot be empty)
   at GitCredentialManager.Commands.GitCommandBase.EnsureMinimumInputArguments(InputArguments input)
   at GitCredentialManager.Commands.StoreCommand.EnsureMinimumInputArguments(InputArguments input)
   at GitCredentialManager.Commands.GitCommandBase.ExecuteAsync()
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
* remote repo
  Fetch URL: https://repo.or.cz/libnbd/ericb
  Push  URL: https://repo.or.cz/libnbd/ericb
  HEAD branch: master
  Remote branches:
    fast-zero tracked
    master    tracked
  Local ref configured for 'git push':
    master pushes to master (fast-forwardable)

```

If you are running inside of Windows Subsystem for Linux (WSL), you must also set an additional environment variable to enable tracing: `WSLENV=$WSLENV:GCM_TRACE`.
For example:

```shell
WSLENV=$WSLENV:GCM_TRACE:GIT_TRACE GCM_TRACE=1 GIT_TRACE=1 git fetch
```

**Comment by ldennington** [comment]
I apologize for the pain here. Is disabling GCM an option for you? My thinking is that would make the errors go away while libsecret continues to do its thing. I understand that support for `repo.or.cz` and similar providers is a deeper issue, but I'm thinking of potential short-term mitigations.

You should be able to remove the `helper = /usr/local/share/gcm-core/git-credential-manager-core` line from your global config if you do decide to disable GCM.

**Comment by dscho** [comment]
> You should be able to remove the `helper = /usr/local/share/gcm-core/git-credential-manager-core` line from your global config if you do decide to disable GCM.

Or override selectively via [`credential.<url>.helper`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-credentiallturlgt). Note:

- The `<url>` can be a partial match, e.g. `https://repo.or.cz`
- The `credential.helper` setting is multi-valued, to re-set it to the empty list you have to pass an empty value first, like so:
  ```ini
  [credential "https://repo.or.cz"]
    helper =
    helper = libsecret
  ```
  (I recommend editing either the repository config or the "global" config, via `git config -e` or `git config -e --global`, respectively.)

**Comment by ebblake** [comment]
I still need GCM for github and gitlab access (libsecret isn't cutting it there).  Trying:
```
[credential "https://repo.or.cz"]
	credentialStore = secretservice
        helper =
        helper = libsecret
[credential]
	credentialStore = secretservice
	helper =
	helper = /usr/local/share/gcm-core/git-credential-manager-core
```
didn't work; I still got the warning message from GCM, as well as a per-command password prompt:
```
$ git remote update
Fetching origin
Fetching repo
fatal: Invalid 'host' input argument (cannot be empty)
Password for 'cert:////home/eblake/certs/rorcz_ericb_user_1.pem': 

fatal: Invalid 'host' input argument (cannot be empty)
```

while the configuration that I'm currently living with:
```
[credential]
	credentialStore = secretservice
	helper =
	helper = /usr/local/share/gcm-core/git-credential-manager-core
	helper = libsecret
```
I can at least ignore the warning messages, but get the benefit of longer-lived caching:
```
$ git remote update
Fetching origin
Fetching repo
fatal: Invalid 'host' input argument (cannot be empty)
fatal: Invalid 'host' input argument (cannot be empty)
```

For reference, I am using a repository with two remotes:
```
$ git remote show origin | head -n3
* remote origin
  Fetch URL: https://gitlab.com/nbdkit/libnbd.git
  Push  URL: https://gitlab.com/nbdkit/libnbd.git
$ git remote show repo 2>/dev/null | head -n3
* remote repo
  Fetch URL: https://repo.or.cz/libnbd/ericb
  Push  URL: https://repo.or.cz/libnbd/ericb
```

**Comment by dscho** [comment]
> ```ini
> [credential "https://repo.or.cz"]
> 	credentialStore = secretservice
>         helper =
>         helper = libsecret
> [credential]
> 	credentialStore = secretservice
> 	helper =
> 	helper = /usr/local/share/gcm-core/git-credential-manager-core
> ```

I am fairly certain that Git will read those in order, and therefore the second-to-last line (`helper =`) will reset the list of credential helpers, then only GCM Core will be added.

I _think_ that you need to turn that around:

```ini
[credential]
	credentialStore = secretservice
	helper =
	helper = /usr/local/share/gcm-core/git-credential-manager-core
[credential "https://repo.or.cz"]
	credentialStore = secretservice
        helper =
        helper = libsecret
```

**Comment by dscho** [comment]
> Git will read those in order

Point in case: when I add this section to my Git config (via `git config -e`):

```ini
[credential "https://repo.or.cz"]
        helper =
        helper = super-bogus
```

I get this output:

```console
$ echo "url=https://repo.or.cz/bogus" | GIT_TERMINAL_PROMPT=false git credential fill
git: 'credential-super-bogus' is not a git command. See 'git --help'.
fatal: could not read Username for 'https://repo.or.cz': terminal prompts disabled
```

If I _then_ append the following section:

```ini
[credential]
        helper =
```

and run the same command, I get:

```console
$ echo "url=https://repo.or.cz/bogus" | GIT_TERMINAL_PROMPT=false git credential fill
fatal: could not read Username for 'https://repo.or.cz': terminal prompts disabled
```

i.e. it does not even bother to try to run the `git credential-super-bogus` helper. Which indeed means that the last section overrode the second-to-last section.

**Comment by ldennington** [comment]
@ebblake - were you able to re-order your credential helpers to fix your issue here?

**Comment by ebblake** [comment]
Re-ordering in .gitconfig didn't help; but since the warning message is not fatal as long as my secondary credential engine gets a shot, I'm just living with it.

**Comment by dscho** [comment]
@ebblake could you look at the output of `git config --show-scope --get-regexp "credential.*helper"` to see whether there might be anything odd in there?

**Comment by ldennington** [comment]
If anything else is needed, feel free to re-open the ticket.
