### ISSUE TITLE
Github API deprecation doc uses githubuser-content image links

### ISSUE THREAD

**Issue by wolf99** [GitCredentialManager/git-credential-manager#863]
Hi!

As you may know I've been working to tidy the markdown docs a little bit.
During #680 , I noticed that https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/github-apideprecation.md uses images linked from https://user-images.githubusercontent.com type URLs.

It may make more sense to have the images stored in the `docs/img` dir within the repo, as with images used in other doc files.
But I cannot tell from the URL where those images are currently actually stored so I am unsure if this is a good idea and where to go do correctly source the image files.

Do you know where those image files are? Another repo or GitHub help page maybe?
It looks like it may have been the latter at one point, but that the GitHub docs were then since changed...

Some examples of the image: URLs used:

- https://user-images.githubusercontent.com/5658207/95448288-ff4ee800-095a-11eb-9709-8e37bde8b716.png
- https://user-images.githubusercontent.com/5658207/95448393-31f8e080-095b-11eb-9568-cfd1c567a65c.png
- https://user-images.githubusercontent.com/5658207/95447450-a3d02a80-0959-11eb-82a8-2d2834d5aa16.png
- etc...

**Comment by Wmoow122** [comment]
![Screenshot_٢٠٢٢٠٩١٤-٠٤١٥٣٤](https://user-images.githubusercontent.com/105323629/190070203-caf6ca96-50e7-4a60-a7ad-8b5bc1f0ba94.png)

**Comment by Wmoow122** [comment]
![Uploading Screenshot_٢٠٢٢٠٩١٣-١٢٥٤١٤.png…]()

**Comment by ldennington** [comment]
I think this is a good idea! My suggestion is to download the images at the links and add them to the `img` directory and change the links in the file.
