### ISSUE TITLE
Template nightly test runs are failing with:

### ISSUE THREAD

**Issue by sujadhali** [GitCredentialManager/git-credential-manager#866]
Template nightly test runs are failing with:

> Error message:
>node common/scripts/install-run-rush.js install
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /mnt/vss/_work/_temp/b90c7bd1-a602-4005-89a2-8e5cfa10b64f.sh
The rush.json configuration requests Rush version 5.63.0
Transforming /mnt/vss/_work/1/s/common/config/rush/.npmrc
  --> "/mnt/vss/_work/1/s/common/temp/install-run/@microsoft+rush@5.63.0/.npmrc"
Installing @microsoft/rush...
npm ERR! code E500
npm ERR! 500 Internal Server Error - GET https://registry.npmjs.org/@pnpm%2flink-bins - Network connection lost.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cloudtest/.npm/_logs/2022-09-15T10_34_27_554Z-debug-0.log
Error: Unable to install package: Error: "npm install" encountered an error

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1852603&view=results

__Originally posted by @v-jiaodi in https://github.com/Azure/azure-sdk-for-js/issues/23234__

**Comment by dscho** [comment]
> Network connection lost.

@sujadhali In what way do you think this could be a bug in Git Credential Manager?

**Comment by ldennington** [comment]
Closing, as this appears to be a network issue.
