### ISSUE TITLE
Unexpected end of file with gcm-linux_amd64.2.0.785.deb

### ISSUE THREAD

**Issue by gwhizoftv** [GitCredentialManager/git-credential-manager#868]
I downloaded the "latest' .deb package:

curl -o gcm-linux_amd64.2.0.785.deb https://github.com/GitCredentialManager/git-credential-manager/releases/download/v2.0.785/gcm-linux_amd64.2.0.785.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

I tried to follow the directions below for Debian:

 sudo bash
root@ip-172-31-24-191:/home/admin/adminstuff# dpkg -i gcm-linux_amd64.2.0.785.deb 
dpkg-deb: error: unexpected end of file in archive magic version number in gcm-linux_amd64.2.0.785.deb
dpkg: error processing archive gcm-linux_amd64.2.0.785.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 gcm-linux_amd64.2.0.785.deb
root@ip-172-31-24-191:/home/admin/adminstuff#

**Comment by dscho** [comment]
> ```
> curl -o gcm-linux_amd64.2.0.785.deb https://github.com/GitCredentialManager/git-credential-manager/releases/download/v2.0.785/gcm-linux_amd64.2.0.785.deb
> % Total % Received % Xferd Average Speed Time Time Time Current
> Dload Upload Total Spent Left Speed
> 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
> ```

That does not look as if it worked. Maybe you need to pass the `-L` flag so that `curl` follows redirects?
