### ISSUE TITLE
Specify the Microsoft identity OAuth tokens redirect port

### ISSUE THREAD

**Issue by loligans** [GitCredentialManager/git-credential-manager#876]
I am using the git-credential-manager-core inside a docker container that's running in WSL2. I have it set up so that xdg-open will use the host's browser. The problem is after authenticating, the `code` given redirects to `localhost:<random port>`. Is there or can there be a configuration to specify the port number to redirect to so that I can forward the port?

If I specify `--net host` when running the docker container, it will work normally. However, I do not want to go down that path.

**Comment by mjcheetham** [comment]
I don't think we can control the redirect URL to fix a port number unfortunately. This is defined behaviour from MSAL and the App registration (which we are currently unable to change). Is this correct @bgavrilMS?

I would suggest that you try using the Device Code flow which doesn't use redirects. To enable this flow, set the following [Git configuration](https://aka.ms/gcm/config#credentialmsauthflow):

```shell
git config --global credential.msAuthFlow devicecode
```

..or set the following [environment variable](https://aka.ms/gcm/env#gcm_msauth_flow):

```shell
GCM_MSAUTH_FLOW=devicecode
```

**Comment by bgavrilMS** [comment]
@mjcheetham - you can specify any port in the redirect uri. If you set just "http://localhost" then MSAL will look for an open port and use it. If you want to provide a port, e.g. "http://localhost:1234" we will use it.

**Comment by mjcheetham** [comment]
> @mjcheetham - you can specify any port in the redirect uri. If you set just "http://localhost" then MSAL will look for an open port and use it. If you want to provide a port, e.g. "http://localhost:1234" we will use it.

Ah right! Does the app registration not matter then (as long as it's not specified a port itself)?

**Comment by bgavrilMS** [comment]
> > @mjcheetham - you can specify any port in the redirect uri. If you set just "http://localhost" then MSAL will look for an open port and use it. If you want to provide a port, e.g. "http://localhost:1234" we will use it.
> 
> Ah right! Does the app registration not matter then (as long as it's not specified a port itself)?

Pretty much. If you add "http://localhost" in the app registration, AAD will allow "http://localhost:<any_port>"

**Comment by ldennington** [comment]
I _think_ you can set one of the following to get the desired behavior (assuming you're using Azure DevOps as your hosting provider):

```
git config --global credential.azreposDevRedirectUri http://localhost:<desired_port>
```

```
GCM_DEV_AZREPOS_REDIRECTURI=http://localhost:<desired_port>
```

**Comment by loligans** [comment]
Thanks I'll give this a try and share my results

**Comment by mjcheetham** [comment]
Hi @loligans just wanted to check if that environment variable worked for you?

**Comment by loligans** [comment]
How can I clear the cache to try this out 😅

**Comment by bgavrilMS** [comment]
On Windows it's a file (encrypted):  "%LocalAppData%\.IdentityService\msal.cache"

**Comment by loligans** [comment]
Okay great! I tested `git config --global credential.azreposDevRedirectUri http://localhost:<desired_port>` and confirmed it works for me.

Also confirmed that you can also set the `GCM_DEV_AZREPOS_REDIRECTURI=http://localhost:<desired_port>` environment variable and it will override the `credential.azreposDevRedirectUri` configuration
