### ISSUE TITLE
Chime (invalid)

### ISSUE THREAD

**Issue by orvillelawrence727** [GitCredentialManager/git-credential-manager#880]
(invalid)

_Originally posted by @deiissyjuarezz in https://github.com/GitCredentialManager/git-credential-manager/pull/778#pullrequestreview-1113196544_

**Comment by orvillelawrence727** [comment]
My money

**Comment by elementary-my-friend** [comment]
Why am I being bombarded with emails from GitCredentialManagers???

Stop these emails NOW.

I have a feeling some asshole who has been hacking me is behind this!
