### ISSUE TITLE
Error in WSL2 : fatal: Failed to enumerate all Git configuration entries [1]

### ISSUE THREAD

**Issue by KiritoXD01** [GitCredentialManager/git-credential-manager#885]
**Which version of GCM are you using?**
2.0.785+6074e4e3d3

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [x] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**
In WSL2 I get this message: fatal: Failed to enumerate all Git configuration entries [1]
And its ask me for the app paswords

**Comment by ldennington** [comment]
Please follow these directions and attach the full logs to help us diagnose your issue:

Set the environment variables `GCM_TRACE=1`,`GIT_TRACE=1`, `GCM_TRACE_MSAUTH` and re-run your
Git command. Review and redact any private information and attach the log.

**Comment by ultram4rine** [comment]
I have the same error. Here is the log from `git push` with these env vars:
```sh
$ git push
01:20:12.613495 git.c:460               trace: built-in: git push
01:20:12.613777 run-command.c:655       trace: run_command: GIT_DIR=.git git remote-https origin https://github.com/ultram4rine/ultram4rine.git
01:20:12.615680 git.c:750               trace: exec: git-remote-https origin https://github.com/ultram4rine/ultram4rine.git
01:20:12.615785 run-command.c:655       trace: run_command: git-remote-https origin https://github.com/ultram4rine/ultram4rine.git
01:20:13.004535 run-command.c:655       trace: run_command: '/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe get'
fatal: Failed to enumerate all Git configuration entries [1]

Username for 'https://github.com':
```

**Comment by ldennington** [comment]
@ultram4rine - thanks for the logs. Would you mind running the following and letting us know if it fails for you? Sharing the output would also be appreciated!

```
git config --null --list
```

**Comment by ultram4rine** [comment]
@ldennington sure
```sh
$ git config --null --list
01:16:30.651936 git.c:460               trace: built-in: git config --null --list
01:16:30.652808 run-command.c:655       trace: run_command: unset GIT_PAGER_IN_USE; LESS=FRX LV=-c pager
user.name
ultram4rine^@user.email
ultramarine730@gmail.com^@credential.helper
/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe^@core.repositoryformatversion
0^@core.filemode
true^@core.bare
false^@core.logallrefupdates
true^@remote.origin.url
https://github.com/ultram4rine/ultram4rine.git^@remote.origin.fetch
+refs/heads/*:refs/remotes/origin/*^@branch.master.remote
origin^@branch.master.merge
refs/heads/master^@
```
It doesn't fails.

**Comment by KiritoXD01** [comment]
My issue was that I installed Git and GCM with scoope on Windows, when I executed the normal installers, it works fine

**Comment by ultram4rine** [comment]
I have git in WSL2 and GCM from git for windows. Previously I installed GCM without git for windows, but I got the same error.

Also git doesn't see `credential-manager-core`.
```sh
$ git credential-manager-core configure
```
give something like `credential-manager-core is not a git command`, so it looks like some problem with $PATH.

**Comment by ldennington** [comment]
I _think_ you're having the same issue as described in #791. Let's go ahead and continue the conversation there - I will prioritize investigating this this week.

**Comment by shango420** [comment]
👍
