### ISSUE TITLE
Unable to build credential-manager-core in WSL2

### ISSUE THREAD

**Issue by sueszli** [GitCredentialManager/git-credential-manager#891]
**Which version of GCM are you using?** None - I can't build it.

**Which Git host provider are you trying to connect to?** None - I haven't built it yet.

---

**Expected behavior**

I install git and run the script and "credential-manager-core" gets installed successfully on my WSL2 / Win10 operating system.

```console
curl -LO https://raw.githubusercontent.com/GitCredentialManager/git-credential-manager/main/src/linux/Packaging.Linux/install-from-source.sh && sh ./install-from-source.sh && git-credential-manager-core configure
```

**Actual behavior**

I get a build error that I can't fix no matter how I install the app.
```console
Build FAILED.

/mnt/c/Users/<username>/dev/git-credential-manager/src/linux/Packaging.Linux/Packaging.Linux.csproj(27,5): error MSB3073: The command "/mnt/c/Users/<username>/dev/git-credential-manager/src/linux/Packaging.Linux/build.sh --install-from-source=true --configuration='Release' --version='2.0.832'" exited with code 127.
    0 Warning(s)
    1 Error(s)
```

**Comment by sueszli** [comment]
Whoops - I might have used the wrong label.
I'm sorry if that's the case.

**Comment by mjcheetham** [comment]
Hi @sueszli!

```log
Build FAILED.

/mnt/c/Users/<username>/dev/git-credential-manager/src/linux/Packaging.Linux/Packaging.Linux.csproj(27,5): error MSB3073: The command "/mnt/c/Users/<username>/dev/git-credential-manager/src/linux/Packaging.Linux/build.sh --install-from-source=true --configuration='Release' --version='2.0.832'" exited with code 127.
    0 Warning(s)
    1 Error(s)
```

When you see the build/compile error, can you include all previous output so we can see exactly where the script fails?

**Comment by sueszli** [comment]
Managed to fix it through configuration:

```
git config --global credential.helper "/mnt/c/Program\
```

As seen in the official docs: https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-git

It would be pretty cool if you could link to this page in the `README.md`.

**Comment by sueszli** [comment]
Whoops my bad - just noticed you did that further down in the docs.
I was just confused because it wasn't under linux.

I'll close this issue.
Thanks for taking your time.
