### ISSUE TITLE
GCM OAuth mode for Azure Repos operations creating PAT instead using AAD Oauth token

### ISSUE THREAD

**Issue by prashantbaroliya290184** [GitCredentialManager/git-credential-manager#912]
We want to avoid usage of PAT's and instead use GCM with oauth for Azure Repos for git operations, however upon testing it seems GCM in turn automatically creates a PAT token in Azure DevOps with 'vso.code_write, vso.packaging' scopes for performing git operations.

**Comment by vtbassmatt** [comment]
There isn't enough in this report to begin troubleshooting. I know from your original email that you aren't comfortable sharing complete logs publicly, but we need to understand what you've tried, what config settings you've set, and (at bare minimum) the version of GCM you're using. Thanks in advance!

**Comment by mjcheetham** [comment]
Hello @prashantbaroliya290184!

Support for Azure Repos 'OAuth mode' was first released in GCM [v2.0.394-beta](https://github.com/GitCredentialManager/git-credential-manager/releases/tag/v2.0.394-beta). This version was first bundled with Git for Windows [2.31.0](https://github.com/git-for-windows/git/releases/tag/v2.31.0.windows.1).

**Please make sure you are using a version of Git for Windows _at least_ 2.31.0.. ideally the [latest version (at the time of writing) 2.38.0](https://github.com/git-for-windows/git/releases/tag/v2.38.0.windows.1).**

**Comment by mjcheetham** [comment]
Confirmed fixed by updating via email.
