### ISSUE TITLE
Unable to install on Mac

### ISSUE THREAD

**Issue by tbraun1551** [GitCredentialManager/git-credential-manager#916]
I have run into the same issue repeatedly when attempting to install GCM on my Mac. 

It is a 2021 MBP M1 Max running the release candidate of MacOS Ventura (although same issue happened on previous releases). 

I get the follow error:
`The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.`

I have tried to install it in two different ways. 

1. I have tried installing using the recommended way via HomeBrew. 
2. I have tried installing GCM by running the installer directly. 

I get the same error both times. I have tried taking a quick look at the Console Logs for installer when running it and nothing popped up as out of the ordinary. 

When attempting install via HomeBrew I got this full error message:
```
Error: Failure while executing;
/usr/bin/sudo -E -- /usr/bin/env LOGNAME=<name> USER=<name> USERNAME=<name /usr/sbin/installer -pkg /opt/homebrew/Caskroom/git-credential-manager-core/2.0.785/qcm-osx-arm64-2.0.785.pkg -target / -allowUntrusted' exited with 1. Here's the output:
installer: Package name Is Git credential Manager
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An Error occurred while running scripts from the package "GCM-osx-arm64-2.0.785.pkg
```

**Comment by ldennington** [comment]
Would you mind attaching the logs from the manual installer run, please? Let the installer run until it hits the error, then do the following:

`cmd-L`, “Detail Level -> Show All Logs”

**Comment by tbraun1551** [comment]
[Installer Log 26-Oct-2022.txt](https://github.com/GitCredentialManager/git-credential-manager/files/9874939/Installer.Log.26-Oct-2022.txt)
Attached is a txt with the logs from the failed install.

**Comment by ldennington** [comment]
Based on the following line in the log, I think the `postinstall` script (by way of the `configure` command) may be struggling with your Git config:

`fatal: Failed to unset all Git configuration multi-valued entries 'credential.helper' [1]`

Would you mind sharing the contents of your config (redacting any sensitive information)? You can use `git config --list` to print the content in your terminal and paste it in a comment here.

**Comment by tbraun1551** [comment]
The contents of my git config are: 
```
credential.helper=osxkeychain
user.name=Thomas Braun
user.email=tbraun****@gmail.com
(END)

```

**Comment by ldennington** [comment]
The `configure` command seems to be failing on the following Git command, but we're not getting the Git logs:

`git config --global --unset-all credential.helper`

Would you mind running that and pasting in the results - hopefully we'll be able to get more detailed output from Git.

If that command ends up running without error, try the installer again - perhaps clearing out the config is all that's needed.

**Comment by tbraun1551** [comment]
When running the command, nothing popped up but when running `git config --list` again this is what I got 
```
credential.helper=osxkeychain
(END)
```

When reinstalling via HomeBrew I got the same error.

**Comment by ldennington** [comment]
Hmm...that's some pretty unexpected behavior. I would have expected the above command to have unset any existing `credential.helper` entries in your global config, but it looks like it unset your `user.name` and `user.email`. (Side note - I assume the `credential.helper=osxkeychain` is set in your system config rather than your global config so the fact that it's still there is expected). What version of Git are you using?

**Comment by ldennington** [comment]
Also, can you run the following in a bash terminal and let me know the number that is output?

`git config --global --unset-all credential.helper | echo $?`

**Comment by mjcheetham** [comment]
```text
Oct 26 18:29:39 Thomass-MacBook-Pro package_script_service[57472]: ./postinstall: Configuring component 'Git Credential Manager'...
Oct 26 18:29:39 Thomass-MacBook-Pro package_script_service[57472]: ./postinstall: fatal: Failed to unset all Git configuration multi-valued entries 'credential.helper' [1]
Oct 26 18:29:39 Thomass-MacBook-Pro package_script_service[57472]: ./postinstall: xcrun: error: active developer path ("/Applications/Xcode-14.0.0-Beta.3.app/Contents/Developer") does not exist
Oct 26 18:29:39 Thomass-MacBook-Pro package_script_service[57472]: ./postinstall: Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
```

It looks like there's a problem with the installer package `postinstall` script calling `git`, because of some problem with the Xcode install?

What happens if you do `which -a git` and `git --version`? Are you using beta versions of Xcode?

**Comment by tbraun1551** [comment]
Hi all,
Currently at work so don't have access to my mac but will provide the necessary information later today. 
I am running a beta version of Xcode primarily but do have the latest release version also installed. I do use the [xcodes app](https://github.com/RobotsAndPencils/xcodes) to manage the downloads but I do not believe that this would cause the issues.

**Comment by tbraun1551** [comment]
`which -a git` produces:
```
/opt/homebrew/bin/git
/usr/bin/git
```
`git --version`: `git version 2.38.1`

`git config --global --unset-all credential.helper | echo $?` outputs a 0
Running a direct install version of Xcode does not change anything.

**Comment by ldennington** [comment]
Can you re-run the command specifically using Apple's version of Git?

`/usr/bin/git config --global --unset-all credential.helper | echo $?`

**Comment by vmipfdr** [comment]
I'm getting:

**Comment by tbraun1551** [comment]
@ldennington I will try this when I get back from work today. 


> @vmipfdr  I'm getting: ``` installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “gcm-osx-x64-2.0.785.pkg”.)
What version of the OS are you running and how are you trying to install it. Trying to understand if we may be having the same issue.

**Comment by tbraun1551** [comment]
I ran `sudo xcode-select --switch path/to/Xcode.app` to change the developer path of the Xcode Developer tools and that appeared to fix the issue.

**Comment by vmipfdr** [comment]
> @ldennington I will try this when I get back from work today.
> 
> > @vmipfdr  I'm getting: ``` installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “gcm-osx-x64-2.0.785.pkg”.)
> 
> What version of the OS are you running and how are you trying to install it. Trying to understand if we may be having the same issue.

I'm on Ventura 13.0

**Comment by ldennington** [comment]
@vmipfdr - please follow [these instructions](https://github.com/GitCredentialManager/git-credential-manager/issues/916#issuecomment-1290730728) and provide us with your full installer logs.

**Comment by ldennington** [comment]
@vmipfdr - are you still experiencing this issue? If so, can you please send along the requested installer logs?

**Comment by vmipfdr** [comment]
@ldennington apologies for the late response.  Yes still having issues.  here are my logs.

**Comment by ldennington** [comment]
Apologies if I'm missing something, but I don't see any logs linked in the previous message?

**Comment by vmipfdr** [comment]
oops.... just fixed it.

**Comment by ldennington** [comment]
Based on this:

`./postinstall: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun`

I believe running either or both of [these commands](https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a) should resolve this for you.

**Comment by vmipfdr** [comment]
Up and running, thanks.

**Comment by megawebmaster** [comment]
The issue for me was invalid owners of `.gitconfig` file in my home directory.

To fix it run this: `sudo chown $(id -u):staff ~/.gitconfig`
