### ISSUE TITLE
Incorrect configure instructions for Debian

### ISSUE THREAD

**Issue by rendall** [GitCredentialManager/git-credential-manager#958]
Per PR #940 

The [installation instructions for Linux: Debian Package](https://github.com/GitCredentialManager/git-credential-manager/blob/release/docs/install.md#debian-package) are incorrect. 

Currently the instructions for .deb installation are:

    Download the latest [.deb package][latest-release], and run the following:
    
    sudo dpkg -i <path-to-package>
    git-credential-manager configure

However, the command `git-credential-manager configure` returns `git-credential-manager: command not found`. 

Using the command `git credential-manager` _(`git` [space, not dash] `credential-manager`)_ returns
```
git: 'credential-manager' is not a git command. See 'git --help'.

The most similar command is
	credential-manager-core
```

Using `git credential-manager-core configure` works correctly as expected. 

I recommend updating the instructions so that the package is properly configured and run after installation. 
1. `git-credential-manager` is not a command while `git credential-manager` responds (git [space] credential-manager)
2. `get credential-manager` is not itself a command, while `get credential-manager-core` is

Also,  the instructions for ["Tarball"](https://github.com/GitCredentialManager/git-credential-manager/blob/release/docs/install.md#tarball) and ["Install from source helper script"](https://github.com/GitCredentialManager/git-credential-manager/blob/release/docs/install.md#install-from-source-helper-script) also use the probably incorrect `git-credential-manager` command.

**Comment by cslovell** [comment]
This helped me install and use the software. Thanks @rendall for describing the solution.

**Comment by rendall** [comment]
Good news. Glad it helped.

**Comment by ldennington** [comment]
The new release can be found [here](https://github.com/GitCredentialManager/git-credential-manager/pull/961).

We plan to promote from pre-release to full release tomorrow. Please feel free to test in the meantime, though!

**Comment by ldennington** [comment]
Closing this under the assumption that the latest release resolved these issues.
