### ISSUE TITLE
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to hub.fastgit.org:443 -tensorflow 

### ISSUE THREAD

**Issue by cssius111** [GitCredentialManager/git-credential-manager#962]
It is a problem when I am trying to download the TensorFlow that fit my computer.
-Mac Pro
-M1(Apple silicon)
-Arm64
I'm using this walkthrough.
cyberlight.xyz/passage/tensorflow-apple-m1
And I delete the Mac version check because there is an error there.
file name: download_and_install.sh
And the error goes like this:
bash download_and_install.sh  

Installation script for pre-release tensorflow_macos 0.1alpha1.  Please visit https://github.com/apple/tensorflow_macos 
for instructions and license information.

**This script will download tensorflow_macos 0.1alpha1 and needed binary dependencies, then install them into a new 
or existing Python 3.8 virtual enviornoment.
Continue [y/N]? y

Downloading installer.
/var/folders/qg/ggt7d3b5509cyb9s5zxvr3lr0000gn/T/tmp.0Cyad1Xi ~/Downloads
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                                          Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0  --:--:-- --:--:-- --:--:--     0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to hub.fastgit.org:443** 

I tried VPN but it doesn't work.

**Comment by mjcheetham** [comment]
Hello! 👋 

I don't think this issue is to do with Git Credential Manager. You are better reaching out to the project owner for TensorFlow_macos (looks to be Apple) for support on download and install.

**Comment by admin-01-web** [comment]
> Hello! wave
> 
> I don't think this issue is to do with Git Credential Manager. You are better reaching out to the project owner for TensorFlow_macos (looks to be Apple) for support on download and install.

[https://www.sublimetext.com/docs/3/linux_repositories.html#apt](url)
