### ISSUE TITLE
checkout #963

### ISSUE THREAD

**Issue by admin-01-web** [GitCredentialManager/git-credential-manager#964]
Originally posted by @trash in https://github.com/GitCredentialManager/git-credential-manager/issues/963#issuecomment-1318811375

**Comment by vathanggwapoco** [comment]
Dear ,

May i apologize fo the inconviences for the Miscommunication that happen on
all my privilleges accounts was lost details on my accounts

Due of this we are lossing all

**Comment by jobrentin1** [comment]
Have a great day,
