### ISSUE TITLE
GCM storing creds in the clear when cloning?

### ISSUE THREAD

**Issue by farraon1981** [GitCredentialManager/git-credential-manager#967]
### Discussed in https://github.com/GitCredentialManager/git-credential-manager/discussions/915

<div type='discussions-op-text'>

<sup>Originally posted by **ntset** October 18, 2022</sup>
I followed the docs to get this setup on Linux and something is missing. This is how I installed/initialized it:
```
    dpkg -i gcm-linux_amd64.2.0.785.deb
    git-credential-manager-core configure
    git config --global credential.credentialStore gpg
    pass init <gpg-id>
```
How does GCM handle credentials in a URL such as the clone below? The token-name and token text are placed in .git/config in the clear anyway. What's weird is I _did_ get prompted via curses pin-entry to unlock my gpg key after hitting [ENTER] so assumed GCM should at least hash the token or otherwise somehow protect it. What am I missing?

`git clone https://my-test-token:glpat-E1...xy@my-gitlab.com/my.username/my-repo.git`
</div>

**Comment by dscho** [comment]
Please use your own fork for practicing how to use GitHub.
