### ISSUE TITLE
Unable to uninstall git-credential-manager

### ISSUE THREAD

**Issue by d3ka** [GitCredentialManager/git-credential-manager#969]
I'm trying to uninstall gcm with the command: `brew uninstall --cask git-credential-manager-core`

But I'm getting this error: 
```
==> Uninstalling Cask git-credential-manager-core
==> Running uninstall script /opt/homebrew/share/gcm-core/uninstall.sh
Error: uninstall script /opt/homebrew/share/gcm-core/uninstall.sh does not exist.
```

I'm using macOS: Ventura 13.0.1 with Apple M1 Chip.

**Comment by mahmoudhossam** [comment]
As a workaround, I downloaded [the uninstall script](https://raw.githubusercontent.com/GitCredentialManager/git-credential-manager/main/src/osx/Installer.Mac/uninstall.sh) to `/opt/homebrew/share/gcm-core/` (had to create this directory) and it uninstalled just fine.

**Comment by ldennington** [comment]
Thanks @mahmoudhossam for supplying the workaround. We are planning to fix this in the next GCM release.

**Comment by ldennington** [comment]
Here is the PR with the proposed fix for reference: https://github.com/GitCredentialManager/git-credential-manager/pull/966/files.

**Comment by ldennington** [comment]
Fixed with https://github.com/microsoft/homebrew-git/pull/72
