### ISSUE TITLE
gcm

### ISSUE THREAD

**Issue by ljones43** [GitCredentialManager/git-credential-manager#992]

**Comment by dscho** [comment]
@ljones43 please use your own fork for practicing how to use GitHub.

**Comment by elementary-my-friend** [comment]
Hello,
I keep getting emails from GitHub, I mean *QUITE A FEW.*
I haven't subscribed to anything. I feel GitHub is over my head.

I have been hacked and I can't get rid of the guy. He's a member of GitHub
actually.

Sincerely,
Anne Marie H.
