### ISSUE TITLE
Can't unpack latest GCM deb package

### ISSUE THREAD

**Issue by dotCore-off** [GitCredentialManager/git-credential-manager#997]
## GCM Version
> 2.0.886

## OS Version
> Debian 11 Bullseye

## Description
> Using ``dpkg -i`` on latest available .deb package returns an error and prevent unpacking GCM

## Error log
```log
~ sudo dpkg -i gcm-linux_amd64.2.0.886.deb
dpkg-deb: error: archive 'gcm-linux_amd64.2.0.886.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive gcm-linux_amd64.2.0.886.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 gcm-linux_amd64.2.0.886.deb
```

## Expected log (using previous GCM release)
```log
~ sudo dpkg -i gcm-linux_amd64.2.0.877.deb
Selecting previously unselected package gcm.
(Reading database ... 20058 files and directories currently installed.)
Preparing to unpack gcm-linux_amd64.2.0.877.deb ...
Unpacking gcm (2.0.877) ...

Setting up gcm (2.0.877) ...
```

**Comment by ldennington** [comment]
This appears to be a bug in Debian's `dpkg` tool (based on what I'm reading [here](https://unix.stackexchange.com/questions/669004/zst-compression-not-supported-by-apt-dpkg)). I would recommend instead attempting to install GCM as a [.NET tool](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/install.md#install-5), using the [tarball](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/install.md#install-3), or [installing from source](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/install.md#install-4).

**Comment by dennmart** [comment]
Not sure if this is related but there might be an issue in Linux builds in general. I noticed when getting the latest Linux tarball from the [v2.0.886 release](https://github.com/GitCredentialManager/git-credential-manager/releases/tag/v2.0.886) that the file is only 481 bytes. Opening the file in a text editor shows a PGP signature.

**Comment by dotCore-off** [comment]
Indeed, it seems to be an issue from ``dpkg``, but something changed on GCM side.
Latest release doesn't work while previous one ([GCM 2.0.877](https://github.com/GitCredentialManager/git-credential-manager/releases/tag/v2.0.877)) does. 
Will ``ZST compression`` remains in future releases? Is it something that could be reverted? @ldennington

**Comment by ldennington** [comment]
The Debian package works as expected on Ubuntu, as you can see from the [workflow validation](https://github.com/GitCredentialManager/git-credential-manager/actions/runs/3699361898/jobs/6267088969), but there were a few things that changed in the last release that I can take a look at. We added signing for the tarball in the latest release, which is probably where the mixup with the signature happened. I will look into it today.

**Comment by ldennington** [comment]
All right, I have done the following:

1. Updated the latest release with the correct tarball. You should be able to install without issue now.
2. Put a fix in place for the next release - I will push this out next week when folks are back to review it.

I have not had a chance to dig into the Debian package issues, though.
